### ISSUE TITLE
AWS_SECURITY_TOKEN is not really optional

### ISSUE THREAD

**Issue by bithavoc** [wal-g/wal-g#10]
Readme states `AWS_SECURITY_TOKEN` is optional, I keep getting:
```
postgres_1  | 2017/08/18 20:44:54 FATAL: Did not set the following environment variables:
postgres_1  | AWS_SECURITY_TOKEN
```

**Comment by katie31** [comment]
Done: https://github.com/wal-g/wal-g/commit/68f31ea9aeab73235224f8dbd4396c63cba97818. The environment variable has also been renamed `AWS_SESSION_TOKEN` to conform to the SDK defaults package.
