### ISSUE TITLE
`wal-g.linux-amd64` for v1 not released?

### ISSUE THREAD

**Issue by Gurpartap** [wal-g/wal-g#1006]
The README suggests downloading `wal-g.linux-amd64` binary.

```md
A precompiled binary for Linux AMD 64 of the latest version of WAL-G can be obtained under the Releases tab.

To decompress the binary, use:

tar -zxvf wal-g.linux-amd64.tar.gz
mv wal-g /usr/local/bin/
```

However, the binaries attached with v1.0 release seem to only be compiled with ubuntu as the target.

**This breaks our deployment/setup scripts.**

The ubuntu based release fails to run on debian 5.8.10-x86_64-linode138 with the following log:

```
/usr/local/bin/wal-g-pg-ubuntu-20.04-amd64: /lib/x86_64-linux-gnu/libm.so.6:
 version `GLIBC_2.29' not found (required by /usr/local/bin/wal-g-pg-ubuntu-20.04-amd64)
```

**Comment by usernamedt** [comment]
Hi!

Try using the `wal-g-pg-ubuntu-18.04-amd64` image, it is compiled with the older glibc version and should work on debian.

**Comment by Gurpartap** [comment]
I ended up using an older version release for convenience. 

Not sure about using an "ubuntu" release on an upstream debian system. What's Ubuntu about it anyway? Just different glibc?

**Comment by jhg03a** [comment]
The 18.04 ubuntu binary works on Centos7.  I am also curious because if the database support is per binary, that means there is no longer a singular wal-g binary which is going to make downstream packaging harder.  So anyone making a deb, rpm, apk, etc. is going to have to switch from a single wal-g package to something like wal-g-pg, wal-g-sql, wal-g-mysql, etc.  The split for versions of glibc is fine because it makes the difference in unbuntu 18.04/20.04 and Centos7/8 for example which would be different end repositories.

**Comment by usernamedt** [comment]
> The 18.04 ubuntu binary works on Centos7. I am also curious because if the database support is per binary, that means there is no longer a singular wal-g binary which is going to make downstream packaging harder. So anyone making a deb, rpm, apk, etc. is going to have to switch from a single wal-g package to something like wal-g-pg, wal-g-sql, wal-g-mysql, etc. The split for versions of glibc is fine because it makes the difference in unbuntu 18.04/20.04 and Centos7/8 for example which would be different end repositories.

Hi! 

There was no change in the build process (prior releases were built on ubuntu too), ubuntu-** suffix is here just to indicate the OS that has been used to make a binary (quote from #1007).

As for per-binary database support, this is also unchanged. In previous releases, `wal-g.linux-amd64` targeted for Postgres only, there were no released binaries for other databases. The only change is that starting from v1.0 release we include pre-compiled WAL-G binaries for other databases too.

**Comment by x4m** [comment]
As far as I understand we link with glibc only to support brotli. If we could find a way to make brotli go-native we could avaoid this dependency, thus making binaries more portable.

**Comment by jhg03a** [comment]
> The only change is that starting from the v1.0 release we include pre-compiled WAL-G binaries for other databases too.

So does that mean if I want mysql support for example, I can't use wal-g-pg?

**Comment by jhg03a** [comment]
> As far as I understand we link with glibc only to support brotli. If we could find a way to make brotli go-native we could avaoid this dependency, thus making binaries more portable.

Yes, linking GLIBC is the reason you can't use the ubuntu 20.04 binary on Centos7.

**Comment by usernamedt** [comment]
> > The only change is that starting from the v1.0 release we include pre-compiled WAL-G binaries for other databases too.
> 
> 
> 
> So does that mean if I want mysql support for example, I can't use wal-g-pg?

Yes, you can't use the WAL-G binary targeted for Postgres to backup MySQL

**Comment by x4m** [comment]
> > The only change is that starting from the v1.0 release we include pre-compiled WAL-G binaries for other databases too.
> 
> So does that mean if I want mysql support, for example, I can't use wal-g-pg?
Binaries for different DBs share a good portion of config settings and CLI commands. But currently, they are separate programs. This is made mostly to save size of the binary. E.g. Postgres runs wal-g as archive command on each wal-push. 

We can easily one-binary-to-rule-all-DBs. But would it have much value? it will contain all drivers and dependencies.

**Comment by jhg03a** [comment]
That means downstream packagers are going to have to start publishing backend specific deb/rpm/apk/etc since the binary name is identical.  It also means that you can't practically have a package manager install two different backends on the same host like before with the single zip.

**Comment by jhg03a** [comment]
> We can easily one-binary-to-rule-all-DBs. But would it have much value? it will contain all drivers and dependencies.

That would help immensely.  It solves packaging and deployment issues lining up with documentation, especially existing unchangeable documentation from 3rd parties.
