### ISSUE TITLE
Azure Storage SASS token access functionality does not appear to work

### ISSUE THREAD

**Issue by apeschel** [wal-g/wal-g#1008]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.

postgresql

# Issue description

### Describe your problem

The storage documentation for Azure suggests that it is possible to use a SASS token rather than an access key. However, attempting to use the SASS token an omitting the access key appears to lead to a fault.

https://github.com/wal-g/wal-g/blob/master/docs/STORAGES.md#azure

This error shows up when attempting to only use the SASS token:

```
ERROR: 2021/06/05 18:55:24.243920 failed to configure folder: Azure error : AZURE_STORAGE_ACCESS_KEY setting is not set: Credential error
```

### Please add config and wal-g stdout/stderr logs for debug purpose

```
AZURE_STORAGE_SAS_TOKEN=XXX
WALG_VERSION=v0.2.19
WALG_AZ_PREFIX=azure://postgres-operator-backups
AZURE_STORAGE_ACCOUNT=XXX
WALE_VERSION=1.1.1
USE_WALG_RESTORE=true
WALE_ENV_DIR=/run/etc/wal-e.d/env
USE_WALG_BACKUP=true
CLONE_USE_WALG_RESTORE=true
```

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

The logs just consist of this line over and over:

<details><summary>If you can, provide logs</summary>
<p>
```bash
ERROR: 2021/06/05 18:55:24.243920 failed to configure folder: Azure error : AZURE_STORAGE_ACCESS_KEY setting is not set: Credential error
```
</p>
</details>

**Comment by serprex** [comment]
Did #1056 resolve this for you?

**Comment by apeschel** [comment]
@serprex I think it should fix the problem, thanks! 👍
