### ISSUE TITLE
backup-push exits with 0 on failure

### ISSUE THREAD

**Issue by qwertys-ru** [wal-g/wal-g#102]
**Release**: 0.1.10.
**Description**: backup-push exits with 0 (success) on failure. In this case it failed to upload to S3 several parts of archive.
**Application log**:

```
Finished writing part 1.
Starting part 2 ...
/global/pg_control
2018/07/23 16:10:58 upload: failed to upload 'test/basebackups_005/base_000000010000000000000077/tar_partitions/part_001.tar.lz4': RequestError: send request failed
caused by: Put https://***/test/basebackups_005/base_000000010000000000000077/tar_partitions/part_001.tar.lz4: net/http: HTTP/1.x transport connection broken: unexpected EOF.
2018/07/23 16:10:58 upload: could not upload 'test/basebackups_005/base_000000010000000000000077/tar_partitions/part_001.tar.lz4'
2018/07/23 16:10:58 FATALRequestError: send request failed
caused by: Put https://***/test/basebackups_005/base_000000010000000000000077/tar_partitions/part_001.tar.lz4: net/http: HTTP/1.x transport connection broken: unexpected EOF
Finished writing part 2.
```

backup-list shows this backup as intact, just as backup-fetch:

```
root@db-postgresql-0:/# wal-g backup-list
BUCKET: ***
SERVER: test
name                          last_modified        wal_segment_backup_start
base_000000010000000000000052 2018-07-19T14:58:19Z 000000010000000000000052
base_00000001000000000000006B 2018-07-23T14:12:05Z 00000001000000000000006B
base_000000010000000000000071 2018-07-23T15:58:46Z 000000010000000000000071
base_000000010000000000000077 2018-07-23T16:11:01Z 000000010000000000000077
root@db-postgresql-0:/#
```

backup-fetch:
```
root@db-postgresql-0:/# wal-g backup-fetch restore/ LATEST
BUCKET: ***
SERVER: test
backup_label
tablespace_map
/global/pg_control

Backup extraction complete.
root@db-postgresql-0:/# ls restore/
backup_label  global  tablespace_map
root@db-postgresql-0:/#
```

**Comment by x4m** [comment]
Reviewing code changes for this I also have finally found what could cause #85. In case of compression errors, WAL-G could treat them as not fatal, which was also a bug.

Thank you! Your report helped both cases.

**Comment by x4m** [comment]
Sorry for the noise, I've marked the commit with "Fix", but, obviously, it is not tested well yet to be closed. @qwertys-ru, may I ask you to verify your case against the current master?

**Comment by qwertys-ru** [comment]
Things have got even worse. WAL-G claims it uploaded 3 files:

```
/postgresql.auto.conf
/postgresql.conf
Finished writing part 1.
Starting part 2 ...
/global/pg_control
Finished writing part 2.
Starting part 3 ...
backup_label
tablespace_map
Finished writing part 3.
Uploaded 3 compressed tar Files.
```

But really it only uploaded 2 of them
![37bb6aa9-ffe7-4ddb-b7fc-ded171e4482f](https://user-images.githubusercontent.com/33905371/43208840-f6109a1a-9033-11e8-97f8-a010120cdd4f.png)

Interestingly it always skips part 2 exactly. WAL-G compliled from master at 24.07.2018 12:45 MSK

**Comment by qwertys-ru** [comment]
It appears that if pg_control is the only file in backup it is named after that.

**Comment by qwertys-ru** [comment]
Didn't work, still part_002 not present.

**Comment by x4m** [comment]
The absance of some numbers in parts is OK. There are two reasons for this:
1. one of the parts is renamed to pg_control to designate it's purpose
2. parts are created by parallel threads. if the thread did not encounter files that need to be uploaded before everything is already taken - thread does not upload his empty part header.

**Comment by qwertys-ru** [comment]
Works fine now, thanks!

**Comment by x4m** [comment]
Thanks for reporting. Feel free to reach out with any problems.

**Comment by qwertys-ru** [comment]
When will this fix hit release? This issue may lead to incomplete backups.

**Comment by x4m** [comment]
I'm currently pushing master branch through QA. I think at the end of next week we can release it.--Отправлено из мобильной Яндекс.Почты02.08.2018, 17:34, "Maxim Vasilev" <notifications@github.com>:When will this fix hit release? This issue may lead to incomplete backups.
