### ISSUE TITLE
Do Not Overwrite WAL Files

### ISSUE THREAD

**Issue by DustinChaloupka** [wal-g/wal-g#104]
Reading the PostgreSQL documentation related to archiving, we came across this (from https://www.postgresql.org/docs/10/static/continuous-archiving.html):

>The archive command should generally be designed to refuse to overwrite any pre-existing archive file. This is an important safety feature to preserve the integrity of your archive in case of administrator error (such as sending the output of two different servers to the same archive directory).
>
>It is advisable to test your proposed archive command to ensure that it indeed does not overwrite an existing file, and that it returns nonzero status in this case. The example command above for Unix ensures this by including a separate test step. On some Unix platforms, cp has switches such as -i that can be used to do the same thing less verbosely, but you should not rely on these without verifying that the right exit status is returned. (In particular, GNU cp will return status zero when -i is used and the target file already exists, which is not the desired behavior.)

So we checked to see if `wal-g` did anything that would prevent it from overwriting files, but looking at https://github.com/wal-g/wal-g/blob/master/tar_uploader.go#L96 it does not appear that it does anything, nor any configuration being available that might help.

Is there something we might be missing? If not, would it be fine for something like that to be added around the upload? Another option would be to have it as a separate command that can be used in the `archive_command` for the PostgreSQL configuration, but then that means doing some command line checks with it.

As a workaround, it's probably possible to just manually check the path with say the `aws` CLI tool, but that would be kinda brittle with [wal-g defining the destination path](https://github.com/wal-g/wal-g/blob/master/tar_uploader.go#L84).

**Comment by x4m** [comment]
That's true, WAL-G overwrites archive. We (me and my colleagues) already had some trouble with this. I will fix this (or happily review PR if you have some suggestions). Thanks for taking the time to test it and report with such a careful analysis.

**Comment by DustinChaloupka** [comment]
#105 Is a try at it.
