### ISSUE TITLE
no rows in result set

### ISSUE THREAD

**Issue by struongvet** [wal-g/wal-g#1047]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.
postgresql94-server-9.4.23-1PGDG.rhel7.x86_64

# Issue description

### Describe your problem
// here is your problem
Using backup-push to back up full postgres DB and it failed with error "no rows in result set".  This DB has 180 gigabytes of data.

I use wal-g of the same version on a smaller DB in my env and it worked for that server.

### Please provide steps to reproduce
// it can really help
/opt/backup/wal-g backup-push /mnt/lib/pgsql/11/data --full
...
INFO: 2021/07/28 21:57:32.123434 Selecting the latest backup as the base for the current delta backup...
DEBUG: 2021/07/28 21:57:32.209807 Initializing tmp connection to read Postgres info
ERROR: 2021/07/28 21:57:32.252577 no rows in result set
github.com/jackc/pgx.init
	/home/runner/work/wal-g/wal-g/vendor/github.com/jackc/pgx/conn.go:316
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5652
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.main
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:191
runtime.goexit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/asm_amd64.s:1374

### Please add config and wal-g stdout/stderr logs for debug purpose
{
 "WALG_S3_PREFIX": "s3://xxxx/backup/postgres/wal-g/server01",
 "WALG_S3_STORAGE_CLASS": "STANDARD",
 "WALG_UPLOAD_CONCURRENCY": 16,
 "WALG_UPLOAD_DISK_CONCURRENCY": 1,
 "WALG_LOG_LEVEL": "DEVEL"
}
also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

DEBUG: 2021/07/28 21:57:32.113334 --- COMPILED ENVIRONMENT VARS ---
DEBUG: 2021/07/28 21:57:32.113352 XDG_SESSION_ID=26694
DEBUG: 2021/07/28 21:57:32.113355 HOSTNAME=server01
DEBUG: 2021/07/28 21:57:32.113358 SHELL=/bin/bash
DEBUG: 2021/07/28 21:57:32.113361 TERM=xterm-256color
DEBUG: 2021/07/28 21:57:32.113363 HISTSIZE=1000
DEBUG: 2021/07/28 21:57:32.113366 USER=postgres
DEBUG: 2021/07/28 21:57:32.113372 LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
DEBUG: 2021/07/28 21:57:32.113388 SUDO_USER=root
DEBUG: 2021/07/28 21:57:32.113391 SUDO_UID=0
DEBUG: 2021/07/28 21:57:32.113393 PGUSER=admin
DEBUG: 2021/07/28 21:57:32.113396 USERNAME=postgres
DEBUG: 2021/07/28 21:57:32.113398 PATH=/sbin:/bin:/usr/sbin:/usr/bin
DEBUG: 2021/07/28 21:57:32.113401 MAIL=/var/spool/mail/root
DEBUG: 2021/07/28 21:57:32.113404 PWD=/opt/backup
DEBUG: 2021/07/28 21:57:32.113406 LANG=en_US.UTF-8
DEBUG: 2021/07/28 21:57:32.113409 PGPASSFILE=/var/lib/pgsql/.pgpass
DEBUG: 2021/07/28 21:57:32.113412 SHLVL=1
DEBUG: 2021/07/28 21:57:32.113414 SUDO_COMMAND=./test.sh
DEBUG: 2021/07/28 21:57:32.113417 HOME=/var/lib/pgsql
DEBUG: 2021/07/28 21:57:32.113420 WALG_S3_PREFIX=s3://xxxxxxx/backup/postgres/wal-g/server01/
DEBUG: 2021/07/28 21:57:32.113423 LOGNAME=postgres
DEBUG: 2021/07/28 21:57:32.113425 SUDO_GID=0
DEBUG: 2021/07/28 21:57:32.113428 _=/opt/backup/wal-g
DEBUG: 2021/07/28 21:57:32.113431 WALG_SENTINEL_USER_DATA=
DEBUG: 2021/07/28 21:57:32.113433 WALG_TAR_SIZE_THRESHOLD=1073741823
DEBUG: 2021/07/28 21:57:32.113436 AZURE_STORAGE_KEY=
DEBUG: 2021/07/28 21:57:32.113439 AWS_ROLE_SESSION_NAME=
DEBUG: 2021/07/28 21:57:32.113441 WALG_PGP_KEY_PATH=
DEBUG: 2021/07/28 21:57:32.113444 WALG_SWIFT_PREFIX=
DEBUG: 2021/07/28 21:57:32.113447 WALG_FETCH_TARGET_USER_DATA=
DEBUG: 2021/07/28 21:57:32.113449 WALG_VERIFY_PAGE_CHECKSUMS=false
DEBUG: 2021/07/28 21:57:32.113452 GOMAXPROCS=
DEBUG: 2021/07/28 21:57:32.113455 AWS_CA_BUNDLE=
DEBUG: 2021/07/28 21:57:32.113457 GCS_CONTEXT_TIMEOUT=
DEBUG: 2021/07/28 21:57:32.113460 WALE_GPG_KEY_ID=
DEBUG: 2021/07/28 21:57:32.113463 WALG_UPLOAD_WAL_METADATA=NOMETADATA
DEBUG: 2021/07/28 21:57:32.113466 PGSSLMODE=
DEBUG: 2021/07/28 21:57:32.113468 HTTP_EXPOSE_EXPVAR=
DEBUG: 2021/07/28 21:57:32.113471 WALG_DELTA_MAX_STEPS=0
DEBUG: 2021/07/28 21:57:32.113474 AZURE_ENVIRONMENT_NAME=
DEBUG: 2021/07/28 21:57:32.113476 AWS_REGION=
DEBUG: 2021/07/28 21:57:32.113479 AWS_DEFAULT_REGION=
DEBUG: 2021/07/28 21:57:32.113482 GCS_NORMALIZE_PREFIX=
DEBUG: 2021/07/28 21:57:32.113484 HTTP_LISTEN=
DEBUG: 2021/07/28 21:57:32.113487 AWS_DEFAULT_OUTPUT=
DEBUG: 2021/07/28 21:57:32.113490 WALE_S3_PREFIX=
DEBUG: 2021/07/28 21:57:32.113492 S3_ENDPOINT_PORT=
DEBUG: 2021/07/28 21:57:32.113495 WALG_STREAM_RESTORE_COMMAND=
DEBUG: 2021/07/28 21:57:32.113497 WALG_LOG_LEVEL=DEVEL
DEBUG: 2021/07/28 21:57:32.113500 WALG_PGP_KEY=
DEBUG: 2021/07/28 21:57:32.113503 WALG_SLOTNAME=
DEBUG: 2021/07/28 21:57:32.113505 SSH_PASSWORD=
DEBUG: 2021/07/28 21:57:32.113508 AWS_SECRET_ACCESS_KEY=
DEBUG: 2021/07/28 21:57:32.113511 PGPORT=
DEBUG: 2021/07/28 21:57:32.113513 AWS_CONFIG_FILE=
DEBUG: 2021/07/28 21:57:32.113516 OS_AUTH_URL=
DEBUG: 2021/07/28 21:57:32.113518 WALG_COMPRESSION_METHOD=lz4
DEBUG: 2021/07/28 21:57:32.113521 OS_PASSWORD=
DEBUG: 2021/07/28 21:57:32.113524 AWS_SESSION_TOKEN=
DEBUG: 2021/07/28 21:57:32.113527 PGPASSWORD=
DEBUG: 2021/07/28 21:57:32.113529 AZURE_MAX_BUFFERS=
DEBUG: 2021/07/28 21:57:32.113532 GCS_ENCRYPTION_KEY=
DEBUG: 2021/07/28 21:57:32.113535 WALG_DOWNLOAD_CONCURRENCY=10
DEBUG: 2021/07/28 21:57:32.113537 WALG_GS_PREFIX=
DEBUG: 2021/07/28 21:57:32.113540 WALG_LIBSODIUM_KEY=
DEBUG: 2021/07/28 21:57:32.113543 YC_SERVICE_ACCOUNT_KEY_FILE=
DEBUG: 2021/07/28 21:57:32.113545 AWS_SECRET_KEY=
DEBUG: 2021/07/28 21:57:32.113548 WALG_S3_STORAGE_CLASS=STANDARD
DEBUG: 2021/07/28 21:57:32.113551 UPLOAD_CONCURRENCY=
DEBUG: 2021/07/28 21:57:32.113553 WALG_DELTA_FROM_USER_DATA=
DEBUG: 2021/07/28 21:57:32.113556 WALG_FILE_PREFIX=
DEBUG: 2021/07/28 21:57:32.113558 WALG_AZURE_BUFFER_SIZE=
DEBUG: 2021/07/28 21:57:32.113561 OS_USERNAME=
DEBUG: 2021/07/28 21:57:32.113564 WALG_S3_SSE_KMS_ID=
DEBUG: 2021/07/28 21:57:32.113566 WALG_S3_MAX_PART_SIZE=
DEBUG: 2021/07/28 21:57:32.113569 WALG_DISK_RATE_LIMIT=
DEBUG: 2021/07/28 21:57:32.113572 S3_MAX_PART_SIZE=
DEBUG: 2021/07/28 21:57:32.113575 AWS_PROFILE=
DEBUG: 2021/07/28 21:57:32.113578 S3_ENDPOINT_SOURCE=
DEBUG: 2021/07/28 21:57:32.113581 AWS_ACCESS_KEY=
DEBUG: 2021/07/28 21:57:32.113584 AZURE_BUFFER_SIZE=
DEBUG: 2021/07/28 21:57:32.113586 WALG_PREFETCH_DIR=
DEBUG: 2021/07/28 21:57:32.113589 WALG_UPLOAD_QUEUE=2
DEBUG: 2021/07/28 21:57:32.113591 AZURE_STORAGE_ACCOUNT=
DEBUG: 2021/07/28 21:57:32.113594 AZURE_STORAGE_ACCESS_KEY=
DEBUG: 2021/07/28 21:57:32.113597 WALG_NETWORK_RATE_LIMIT=
DEBUG: 2021/07/28 21:57:32.113600 GOOGLE_APPLICATION_CREDENTIALS=
DEBUG: 2021/07/28 21:57:32.113603 HTTP_EXPOSE_PPROF=
DEBUG: 2021/07/28 21:57:32.113606 WALG_CSE_KMS_ID=
DEBUG: 2021/07/28 21:57:32.113608 SSH_USERNAME=
DEBUG: 2021/07/28 21:57:32.113611 WALG_LIBSODIUM_KEY_PATH=
DEBUG: 2021/07/28 21:57:32.113613 WALG_CSE_KMS_REGION=
DEBUG: 2021/07/28 21:57:32.113616 WALG_PG_WAL_SIZE=16
DEBUG: 2021/07/28 21:57:32.113619 WALG_USE_WAL_DELTA=false
DEBUG: 2021/07/28 21:57:32.113621 WALG_USE_RATING_COMPOSER=false
DEBUG: 2021/07/28 21:57:32.113624 WALG_S3_CA_CERT_FILE=
DEBUG: 2021/07/28 21:57:32.123221 WALG_INTEGRITY_MAX_DELAYED_WALS=0
DEBUG: 2021/07/28 21:57:32.123231 SSH_PRIVATE_KEY_PATH=
DEBUG: 2021/07/28 21:57:32.123234 S3_STORAGE_CLASS=
DEBUG: 2021/07/28 21:57:32.123237 AZURE_STORAGE_SAS_TOKEN=
DEBUG: 2021/07/28 21:57:32.123239 WALG_DELTA_FROM_NAME=
DEBUG: 2021/07/28 21:57:32.123242 S3_CA_CERT_FILE=
DEBUG: 2021/07/28 21:57:32.123246 PGDATABASE=
DEBUG: 2021/07/28 21:57:32.123249 WALG_SSH_PREFIX=
DEBUG: 2021/07/28 21:57:32.123255 WALG_S3_SSE=
DEBUG: 2021/07/28 21:57:32.123258 S3_USE_LIST_OBJECTS_V1=
DEBUG: 2021/07/28 21:57:32.123260 WALG_AZURE_MAX_BUFFERS=
DEBUG: 2021/07/28 21:57:32.123263 OS_REGION_NAME=
DEBUG: 2021/07/28 21:57:32.123266 AWS_ACCESS_KEY_ID=
DEBUG: 2021/07/28 21:57:32.123268 WALG_PREVENT_WAL_OVERWRITE=false
DEBUG: 2021/07/28 21:57:32.123271 AWS_SHARED_CREDENTIALS_FILE=
DEBUG: 2021/07/28 21:57:32.123273 OS_TENANT_NAME=
DEBUG: 2021/07/28 21:57:32.123276 GCS_MAX_RETRIES=
DEBUG: 2021/07/28 21:57:32.123279 WALG_STREAM_CREATE_COMMAND=
DEBUG: 2021/07/28 21:57:32.123281 WALG_PGP_KEY_PASSPHRASE=
DEBUG: 2021/07/28 21:57:32.123284 WALG_USE_REVERSE_UNPACK=false
DEBUG: 2021/07/28 21:57:32.123286 AWS_ENDPOINT=
DEBUG: 2021/07/28 21:57:32.123289 PGDATA=
DEBUG: 2021/07/28 21:57:32.123291 WALG_DELTA_ORIGIN=
DEBUG: 2021/07/28 21:57:32.123294 S3_SSE_KMS_ID=
DEBUG: 2021/07/28 21:57:32.123297 GCS_MAX_CHUNK_SIZE=
DEBUG: 2021/07/28 21:57:32.123299 AWS_S3_FORCE_PATH_STYLE=
DEBUG: 2021/07/28 21:57:32.123302 PG_READY_RENAME=
DEBUG: 2021/07/28 21:57:32.123304 S3_SSE=
DEBUG: 2021/07/28 21:57:32.123308 WALG_STORE_ALL_CORRUPT_BLOCKS=false
DEBUG: 2021/07/28 21:57:32.123310 TOTAL_BG_UPLOADED_LIMIT=32
DEBUG: 2021/07/28 21:57:32.123313 YC_CSE_KMS_KEY_ID=
DEBUG: 2021/07/28 21:57:32.123315 SSH_PORT=
DEBUG: 2021/07/28 21:57:32.123318 WALG_SKIP_REDUNDANT_TARS=false
DEBUG: 2021/07/28 21:57:32.123321 PGHOST=
DEBUG: 2021/07/28 21:57:32.123323 WALG_AZ_PREFIX=
DEBUG: 2021/07/28 21:57:32.123326 WALG_GPG_KEY_ID=
INFO: 2021/07/28 21:57:32.123434 Selecting the latest backup as the base for the current delta backup...
DEBUG: 2021/07/28 21:57:32.209807 Initializing tmp connection to read Postgres info
ERROR: 2021/07/28 21:57:32.252577 no rows in result set
github.com/jackc/pgx.init
	/home/runner/work/wal-g/wal-g/vendor/github.com/jackc/pgx/conn.go:316
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5652
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.doInit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:5647
runtime.main
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/proc.go:191
runtime.goexit
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/asm_amd64.s:1374
<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

**Comment by struongvet** [comment]
/opt/backup/wal-g --version
wal-g version v1.0	2611d11	2021.05.31_12:37:24	PostgreSQL

**Comment by x4m** [comment]
Hi!
9.4 and 9.5 are not supported by 1.0.
There's a fix for 9.5 #1020

**Comment by struongvet** [comment]
@x4m Thank you for the response.  Would there be a release note somewhere to allow me to read to understand which versions of postgres are supported by wal-g releases?  I need to make sure I have this figured out or my backups are bad and then we are toasted.   Thank you.

**Comment by usernamedt** [comment]
This should be fixed in https://github.com/wal-g/wal-g/releases/tag/v1.1, can you have a look and check if it works for you now?
