### ISSUE TITLE
open pg_wal/.wal-g/prefetch: too many open files

### ISSUE THREAD

**Issue by victor-sudakov** [wal-g/wal-g#1074]
### Database name
postgresql-12/buster-pgdg,now 12.8-1.pgdg100+1 amd64 
wal-g version v1.0      2611d11 2021.05.31_12:37:24     PostgreSQL

# Issue description
After a standby Postgres is restarted, while running `restore_command = '/usr/local/bin/wal-g wal-fetch %f %p'`, wal-g complains of too many open files:
Aug 23 03:19:13 XXXXXXXX postgres[25024]: [6-1] <%%%>LOG:  database system is ready to accept read only connections
```
INFO: 2021/08/23 03:19:13.485546 WAL-prefetch file:  000000040000EC310000000E
INFO: 2021/08/23 03:19:13.495684 WAL-prefetch file:  000000040000EC310000000F
ERROR: 2021/08/23 03:19:13.495713 open pg_wal/.wal-g/prefetch/running/000000040000EC310000000F: too many open files
INFO: 2021/08/23 03:19:13.506045 WAL-prefetch file:  000000040000EC3100000010
ERROR: 2021/08/23 03:19:13.506128 open pg_wal/.wal-g/prefetch/running/000000040000EC3100000010: too many open files

ERROR: 2021/08/23 03:19:13.546309 open pg_wal/.wal-g/prefetch/running/000000040000EC3100000014: too many open files
WARNING: 2021/08/23 03:19:13.556362 WAL-prefetch cleanup failed, :  open pg_wal/.wal-g/prefetch: too many open files  cannot enumerate files in dir:  pg_wal/.wal-g/prefetch
WARNING: 2021/08/23 03:19:13.556379 WAL-prefetch cleanup failed, :  open pg_wal/.wal-g/prefetch/running: too many open files  cannot enumerate files in dir:  pg_wal/.wal-g/prefetch/running

```
The systemd limits should be more than enough:
```
# systemctl show postgresql.service | grep -i NOFILE
LimitNOFILE=128000
LimitNOFILESoft=128000
```

**Comment by Pluies** [comment]
Running into the same issue here FWIW.
As far as I can tell, this _appears_ to be harmless, as the DB then starts up nicely, but this is worrying still!

@victor-sudakov , how can I try the proposed fix? Is it a matter of rebuilding a wal-g executable from your branch and trying to reprovision a standby server with it?

**Comment by usernamedt** [comment]
> Running into the same issue here FWIW.
> 
> As far as I can tell, this _appears_ to be harmless, as the DB then starts up nicely, but this is worrying still!
> 
> 
> 
> @victor-sudakov , how can I try the proposed fix? Is it a matter of rebuilding a wal-g executable from your branch and trying to reprovision a standby server with it?

Hi! You need to build the branch of my PR to test it.

**Comment by victor-sudakov** [comment]
> @victor-sudakov can you try the proposed fix and see if it helped?

Actually this seems to be my fault. It was not enough setting LimitNOFILE limits on the postgresql.service (template). Setting the same limits on the postgresql@13-XXXX.service instance fixes the "too many open files" problem.

**Comment by mikeb-syncro** [comment]
Also ran into this issue with the 1.1 compiled release.  Is there a compiled release that has the file-closing fix?
