### ISSUE TITLE
wal-show command errors out with: Incorrect logSegNoLo in WAL file name

### ISSUE THREAD

**Issue by siepkes** [wal-g/wal-g#1078]
### Database name

PostgreSQL

# Issue description

### Describe your problem

The `wal-show` command runs in to an "Incorrect logSegNoLo in WAL file name" error when trying to parse the name of the base backup:

```
/opt/walg/wal-g --config /etc/walg/walg.json wal-show
ERROR: 2021/08/25 14:26:28.706255 Failed to add backups info: Incorrect logSegNoLo in WAL file name: 00000019000000000000177F
```

Ultimately the check here triggers the error: https://github.com/wal-g/wal-g/blob/cadf598e1c2a345915a21a44518c5a4d5401e2e3/internal/databases/postgres/timeline.go#L134-L137

If I deduced it correctly `xLogSegmentsPerXLogID` is always `256`. The value of `logSegNoLo` would be way higher then that with a base backup file name `00000019000000000000177F`. 

I'm a bit confused by `logSegNoLo >= xLogSegmentsPerXLogID` since that seems like a sane check for an actual WAL but not for an base backup?

### Please provide steps to reproduce

Make a full backup with `wal-g backup-push`

### Please add config and wal-g stdout/stderr logs for debug purpose

```
----8<---------------------
DEBUG: 2021/08/25 14:03:03.396137 WALG_USE_REVERSE_UNPACK=false
DEBUG: 2021/08/25 14:03:03.396141 WALG_USE_WAL_DELTA=false
DEBUG: 2021/08/25 14:03:03.396145 WALG_VERIFY_PAGE_CHECKSUMS=false
DEBUG: 2021/08/25 14:03:03.396149 YC_CSE_KMS_KEY_ID=
DEBUG: 2021/08/25 14:03:03.396153 YC_SERVICE_ACCOUNT_KEY_FILE=
DEBUG: 2021/08/25 14:03:03.396157 _=/opt/walg/wal-g
DEBUG: 2021/08/25 14:03:03.740582 Selected crypter: Opengpg/Crypter
DEBUG: 2021/08/25 14:03:03.893006 Selected crypter: Opengpg/Crypter
ERROR: 2021/08/25 14:03:04.756975 Failed to add backups info: Incorrect logSegNoLo in WAL file name: 00000019000000000000177F
github.com/wal-g/wal-g/internal/databases/postgres.newIncorrectLogSegNoError
        /root/wal-g-fork/internal/databases/postgres/timeline.go:40
github.com/wal-g/wal-g/internal/databases/postgres.ParseWALFilename
        /root/wal-g-fork/internal/databases/postgres/timeline.go:135
github.com/wal-g/wal-g/internal/databases/postgres.getBackupsInRange
        /root/wal-g-fork/internal/databases/postgres/wal_show_handler.go:197
github.com/wal-g/wal-g/internal/databases/postgres.addBackupsInfo
        /root/wal-g-fork/internal/databases/postgres/wal_show_handler.go:182
github.com/wal-g/wal-g/internal/databases/postgres.HandleWalShow
        /root/wal-g-fork/internal/databases/postgres/wal_show_handler.go:142
github.com/wal-g/wal-g/cmd/pg.glob..func13
        /root/wal-g-fork/cmd/pg/wal_show.go:41
github.com/spf13/cobra.(*Command).execute
        /root/wal-g-fork/vendor/github.com/spf13/cobra/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /root/wal-g-fork/vendor/github.com/spf13/cobra/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /root/wal-g-fork/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute
        /root/wal-g-fork/cmd/pg/pg.go:44
main.main
        /root/wal-g-fork/main/pg/main.go:8
runtime.main
        /opt/local/go116/src/runtime/proc.go:225
runtime.goexit
        /opt/local/go116/src/runtime/asm_amd64.s:1371

```

Storage (Backblaze over S3) looks like this:

```
# /opt/walg/wal-g --config /etc/walg/walg.json st ls
size     last modified                 name
112662   2021-08-24 11:38:34 +0000 UTC basebackups_005/base_00000019000000000000177F_backup_stop_sentinel.json
773      2021-08-24 11:38:20 +0000 UTC wal_005/000000180000001700000076.br
113      2021-08-24 11:38:21 +0000 UTC wal_005/000000180000001700000076.json
790      2021-08-24 11:38:50 +0000 UTC wal_005/000000180000001700000077.br
113      2021-08-24 11:38:50 +0000 UTC wal_005/000000180000001700000077.json
763      2021-08-24 11:38:27 +0000 UTC wal_005/00000019000000170000007F.00000028.backup.br
129      2021-08-24 11:38:30 +0000 UTC wal_005/00000019000000170000007F.00000028.backup.json
796      2021-08-24 11:38:27 +0000 UTC wal_005/00000019000000170000007F.br
113      2021-08-24 11:38:29 +0000 UTC wal_005/00000019000000170000007F.json
790      2021-08-24 11:39:27 +0000 UTC wal_005/000000190000001700000080.br
113      2021-08-24 11:39:27 +0000 UTC wal_005/000000190000001700000080.json
757      2021-08-24 11:43:26 +0000 UTC wal_005/000000190000001700000081.br
113      2021-08-24 11:43:26 +0000 UTC wal_005/000000190000001700000081.json
800      2021-08-24 11:44:29 +0000 UTC wal_005/000000190000001700000082.br
113      2021-08-24 11:44:29 +0000 UTC wal_005/000000190000001700000082.json
780      2021-08-24 12:06:00 +0000 UTC wal_005/000000190000001700000083.00000028.backup.br
129      2021-08-24 12:06:03 +0000 UTC wal_005/000000190000001700000083.00000028.backup.json
770      2021-08-24 12:06:00 +0000 UTC wal_005/000000190000001700000083.br
113      2021-08-24 12:06:01 +0000 UTC wal_005/000000190000001700000083.json
782      2021-08-24 12:07:00 +0000 UTC wal_005/000000190000001700000084.br
113      2021-08-24 12:07:00 +0000 UTC wal_005/000000190000001700000084.json
835      2021-08-24 12:54:02 +0000 UTC wal_005/0000001A.history.br
105      2021-08-24 12:54:04 +0000 UTC wal_005/0000001A.history.json
839      2021-08-24 12:55:02 +0000 UTC wal_005/0000001A0000001700000085.br
113      2021-08-24 12:55:02 +0000 UTC wal_005/0000001A0000001700000085.json
782      2021-08-24 12:56:03 +0000 UTC wal_005/0000001A0000001700000086.00000028.backup.br
128      2021-08-24 12:56:09 +0000 UTC wal_005/0000001A0000001700000086.00000028.backup.json
754      2021-08-24 12:56:03 +0000 UTC wal_005/0000001A0000001700000086.br
112      2021-08-24 12:56:04 +0000 UTC wal_005/0000001A0000001700000086.json
727      2021-08-24 12:56:04 +0000 UTC wal_005/0000001A0000001700000087.br
112      2021-08-24 12:56:10 +0000 UTC wal_005/0000001A0000001700000087.json
786      2021-08-24 12:57:04 +0000 UTC wal_005/0000001A0000001700000088.br
113      2021-08-24 12:57:06 +0000 UTC wal_005/0000001A0000001700000088.json
839      2021-08-24 14:51:39 +0000 UTC wal_005/0000001B.history.br
105      2021-08-24 14:51:39 +0000 UTC wal_005/0000001B.history.json
824      2021-08-24 14:51:40 +0000 UTC wal_005/0000001B0000001700000089.br
112      2021-08-24 14:51:44 +0000 UTC wal_005/0000001B0000001700000089.json
385      2021-08-24 11:38:34 +0000 UTC basebackups_005/base_00000019000000000000177F/metadata.json
42670112 2021-08-24 11:38:24 +0000 UTC basebackups_005/base_00000019000000000000177F/tar_partitions/part_001.tar.br
865      2021-08-24 11:38:33 +0000 UTC basebackups_005/base_00000019000000000000177F/tar_partitions/pg_control.tar.br

```

**Comment by usernamedt** [comment]
Can you please also provide the version of WAL-G? Also, did you create the remote backup (`wal-g backup-push`) or regular backup (`wal-g backup-push`)?

**Comment by siepkes** [comment]
> Can you please also provide the version of WAL-G? Also, did you create the remote backup (`wal-g backup-push`) or regular backup (`wal-g backup-push /path/to/pgdir`)?

This was with WAL-G 1.1 running on SmartOS with PostgreSQL 13.4 using remote `wal-g backup-push`.

**Comment by moreinhardt** [comment]
I can confirm this happens with wal-g 1.1 and PostgreSQL 11.13 too.

This error also appears when running the `integrity` check and results in wal-g apparently missing a bunch of WAL files...

```
$ wal-g wal-verify integrity
INFO: 2021/09/01 15:29:23.116045 Current WAL segment: 0000000B00006C0B000000D3
INFO: 2021/09/01 15:29:23.983188 Building check runner: integrity
WARNING: 2021/09/01 15:29:24.032894 Failed to detect earliest backup WAL segment no: 'Incorrect logSegNoLo in WAL file name: 0000000A000000000069137F',will scan until the 0000000X0000000000000001 segment.
```

**Comment by moreinhardt** [comment]
I "fixed" this by deleting the "faulty" backup and now it works again.

@usernamedt tbh I don't really understand the difference between

>remote backup (wal-g backup-push) or regular backup (wal-g backup-push /path/to/pgdir)

The documentation isn't really clear on that IMO.

I think the first (faulty) backup was created using just `wal-g backup-push` while all newer ones (that seem to be identified correctly) were created using `wal-g backup-push /path/to/pgdir`.

**Comment by sebasmannem** [comment]
Hi @moreinhardt,
sorry you ran into this...

I just had a look at this, and indeed as @usernamedt mentions, the issue is in naming of remote backups.
Basically I was not aware that ParseWALFilename was also called for backup names, and was a bit too loose with the naming. Definitely, the name of the backup does not resemble a proper WAL filename at the moment.

We could aim for using the same way as we do for [a regular backup](https://github.com/wal-g/wal-g/blob/22282b5755bb139aacdd4f16914ad1fb174b4f95/internal/databases/postgres/bundle.go#L179), but that would require a regular connection, and the pgConn that is parsed is a streaming pgConn. So executing the query on that does not work.

I propose to make a small helper function to basically do the reverse of ParseWALFilename (create a WALFilename from a timelineID and a LSN) in the proper way.
I will setup something and issue a small PR with the fix somewhere this upcoming week...

On the difference between leaving the path out or not, [these](https://github.com/wal-g/wal-g/blob/master/docs/PostgreSQL.md#remote-backup) docs describe the difference.
Also the backup command shows this (example):

> INFO: 2021/12/04 10:35:55.993717 Running remote backup through Postgres connection.
> INFO: 2021/12/04 10:35:55.993806 Features like delta backup are disabled, there might be a performance impact.
> INFO: 2021/12/04 10:35:55.993836 To run with local backup functionalities, supply [db_directory].

But if you have any recommendations on improving the documentation, just let me know, and I will take that into account for this PR as well...
