### ISSUE TITLE
Cannot use latest (v1) release as code dependency in golang

### ISSUE THREAD

**Issue by maboehm** [wal-g/wal-g#1082]
# Issue description
Hi, I'm importing "github.com/wal-g/wal-g/utility" in my code, and cannot update the dependency to the latest tags, since they are not complete semVer (i.e. `v1.1` instead of `v1.1.0`, see also https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions)

### Please provide steps to reproduce
a minimal example:
```
$ cat go.mod           
module example.com/test
go 1.16
require github.com/wal-g/wal-g v1.1

$ go mod tidy                       
go: errors parsing go.mod:
/tmp/tmp.07rCLs2fep/go.mod:5: no matching versions for query "v1.1"
```
similarly:
```
$ go get github.com/wal-g/wal-g@v1.1
go get github.com/wal-g/wal-g@v1.1: no matching versions for query "v1.1"
```

Can you please in the future use complete major.minor.patch tags for releases? Thank you

**Comment by usernamedt** [comment]
Hi! Thanks, this looks like a good idea. I think we have no reasons not to use this approach.

**Comment by usernamedt** [comment]
> @DaniilKurlovich can you create an additional tag `v1.1.0` that points to the `v1.1` version?

I've created an [additional v1.1.0 tag](https://github.com/wal-g/wal-g/releases/tag/v1.1.0).

**Comment by usernamedt** [comment]
Looks like the extra tag is not an option since it results in failing builds. I've removed the `v1.1.0` tag.
