### ISSUE TITLE
(pg) What wal-verify integrity do?

### ISSUE THREAD

**Issue by iget-master** [wal-g/wal-g#1084]
### Database name
Postgres

# Issue description

I would like to know what exactly `wal-verify integrity` do. 

Let me explain why: with the raise of ransomware attacks, I'm checking for any king of vulnerability in our backups, and one concern is:

If some ransomware tool encrypt my data dir right before I run `backup-push`, so my backup will be "contaminated". Since I do `delete retain FULL n` after every backup-push, my backup might be fully "contaminated" with encrypted files.

My questions: 

1. Will `wal-verify integrity` check if the existing backup and wal segments are valid?
2. Will `backup-push` work if data directory is corrupted/encrypted?

**Comment by usernamedt** [comment]
Hi!

> My questions:
> 
> 1. Will `wal-verify integrity` check if the existing backup and wal segments are valid?

No. `wal-verify integrity checks that there are no `holes` in the storage WAL archive. It does not inspect backup contents/wal archive contents.
 
> 2. Will `backup-push` work if data directory is corrupted/encrypted?

If this corruption won't affect the Postgres pg_start_backup()/pg_stop_backup() calls I guess that it might work. Frankly, I don't think that pg_start_backup() call will succeed in case of serious corruption because it performs CHECKPOINT internally.

**Comment by usernamedt** [comment]
> Also, you can use the `WALG_VERIFY_PAGE_CHECKSUMS` option to verify Postgres paged file checksums during the backup creation (if they are enabled cluster-wide).

I've just realized that this functionality is not documented :(  I will provide a fix soon.

**Comment by x4m** [comment]
+1
monitoring of WALG_VERIFY_PAGE_CHECKSUMS + intact objects in S3 almost guarantees that you are not affected by any ransomewhere. If it's not specifically designed to attack PG+WAL-G, of cause, then it might substitute CRCs with recomputed. Keep in mind that you only protect data that is archived, so archive_timeout seconds will not be present in S3.
