### ISSUE TITLE
Errors during wal-fetch return exit code 1

### ISSUE THREAD

**Issue by fischerman** [wal-g/wal-g#1126]
### Database name

Postgres

# Issue description

### Describe your problem

Postgres uses `restore_command` to fetch WAL segments from the archive. This is implemented by `wal-g wal-fetch`. If `restore_command` fails, Postgres distinguishes two cases:

1. Postgres has reached the end of the timeline (no more WAL segments to process, i.e. recovery target time is set to a point in the future). Postgres completes recovery.
2. The restore_command received a signal or failed to execute (shell error). The recovery fails.

The way that Postgres distinguishes those cases is not well documented. The best explanation is in the code (e.g. see [code](https://github.com/postgres/postgres/blob/96b665083eb72570e226cf2d25c960b3acc62040/src/backend/access/transam/xlogarchive.c#L233) or [StackOverflow](https://stackoverflow.com/a/40244365/1863595)). TL;DR For most exit codes incl. exit code 1 Postgres assumes case 1.

WAL-G behaves correctly in this case:
```
# wal-g wal-fetch 000000020000000000000003 /tmp/test1
ERROR: 2021/10/18 12:07:12.891104 Archive '000000020000000000000003' does not exist.
# echo $?
1
```

However, if WAL-G is misconfigured or there are any network related errors, it will return the same exit code.
```
# wal-g wal-fetch 001 001
ERROR: 2021/10/18 13:57:27.599022 Failed to find any configured storage
# echo $?
1
```

Postgres will assume that it has reached the end of the timeline and will complete recovery. I think WAL-G should indicate to Postgres that the WAL fetching failed by mimicking a shell error.

**Comment by sebasmannem** [comment]
@fischerman , this is an awesome question, as it is architectural, practical and philosophical.
So, this will be a verbose answer, still trying to find if and what we should do.

My first comment is that this issue is not exclusive to wal-g. As an example, [rsync](https://linux.die.net/man/1/rsync) (scroll down or search for Exit Values), also does not have exit codes between 126 and 255.
Furthermore, just looking for a generic approach at exit codes I ran into [this](https://tldp.org/LDP/abs/html/exitcodes.html) summary. Everything above 126 seems more like outside of the process.
And I ran into [this](https://unix.stackexchange.com/questions/110348/how-do-i-get-the-list-of-exit-codes-and-or-return-codes-and-meaning-for-a-comm) page.
The page also states:

> According to the above table, exit codes 1 - 2, 126 - 165, and 255 [1] have special meanings, and should therefore be avoided for user-specified exit parameters. Ending a script with exit 127 would certainly cause confusion when troubleshooting (is the error code a "command not found" or a user-defined one?). However, many scripts use an exit 1 as a general bailout-upon-error. Since exit code 1 signifies so many possible errors, it is not particularly useful in debugging.

All of this drills down to me like wal-g (or any other tool) should return 78 on misconfiguration, and PostgreSQL should add that to the list of error codes it errors out on (if I where a purist).

On the other hand, I do get your point, and I don't see huge issues into having wal-g issuing a very specific error code (like  128+SIGUSR1). I can test with that and see f it works as we expect.

Another thing: You mentioned 'Failed to find any configured storage'. That is a specific error (albeit the issue you usually run into when misconfiguration is at hand). It calls `tracelog.ErrorLogger.FatalOnError(err)` which always does an exit(1). So we should change that into something like
```
	if err != nil {
				tracelog.ErrorLogger.PrintError(err)
				os.Exit(128+int(syscall.SIGUSR1))
			}
```
But we probably want to call that in other places too, so a function might even be better.

Does this resemble your request?
@usernamedt , @x4m do you have any thoughts on this?

**Comment by fischerman** [comment]
@sebasmannem Thanks for your response. I agree that this problem is not directly related to WAL-G but is rather a problem with Postgres. I just wanted to make sure that I got this right and I didn't miss anything. As you mentioned, rsync or other tools suffer from the same problem. The exit codes that Postgres considers are all special, so in a perfect world WAL-G should never use them directly. On the other hand, Postgres is currently not designed to handle failing archive commands (for any other reason than "not found".

> All of this drills down to me like wal-g (or any other tool) should return 78 on misconfiguration, and PostgreSQL should add that to the list of error codes it errors out on (if I where a purist).

Changing Postgres would definitely fix the problem altogether. Your proposal is technically a breaking change in Postgres and misconfiguration is only one reason while restore might fail. Here are my thoughts: Postgres needs to distinguish two cases. 

1. File is not present in the archive and continue (or complete) with the recovery. 
2. File couldn't be fetched for any other reason. Postgres should retry until it succeeds. If the error comes from a misconfiguration then recovery will hang until the configuration is fixed.

Case 1 is most likely a single exit code while case 2 can be many exit codes. So a backwards compatible solution would be to introduce a new _optional_ config parameter `restore_command_not_found_exit_code`. If provided, Postgres will only complete the recovery if the specified exit code was returned. Then it would be up the the archive tools to document their exit codes and have a dedicated one for 404s.

IMHO that's the most optimal solution and it would clean up the problem at the root. However, this requires patching Postgres (and back patching older versions as well). If we want to solve it for WAL-G I think there are 3 options:

1. Change WAL-G to reflect Postgres behavior, meaning WAL-G would have to return special exit codes for everything other than 404s. This is not only hacky but requires a lot of care in WAL-G. Anywhere, where WAL-G might exit, it has to return a special exit code, incl. `FATAL` and panics.
2. WAL-G defines a dedicated exit code for "not found", e.g. exit code 2. Using a wrapper shell script to map everything but exit code 2 to 126. If Postgres accepts the patch the wrapper script would be replaced by the config parameter.
3. Parsing stdout of WAL-G in a wrapper shells script, look for "Archive ... does not exist" and manipulate the exit code accordingly. That is an option that we are considering in the short term. It ain't pretty but doesn't require any changes in WAL-G.

P.S.:

> Another thing: You mentioned 'Failed to find any configured storage'. That is a specific error (albeit the issue you usually run into when misconfiguration is at hand).

I picked an arbitrary error for clarification. Looking at the WAL-G code it seems that it always (e.g. network problems) returns exit code 1.

**Comment by sebasmannem** [comment]
Yes, I 100% agree.
One thing to add, is that (to make it a bit more complicated), this errorcode return stuff should only be fixed for wal-fetch for Postgres, and wal-g handles more then just wal-fetch, and more then just Postgres.
I don't like your proposals 2, and 3. wrapper scripts should not be used. And it sounds error prone to me at least.
Over the next 2 weeks I have some more time, and I will see if I can cook something up for option 1, hoping that it isn;t hacky and heavy maintenance. I will keep you posted...

**Comment by fischerman** [comment]
Personally I was surprised to find little information about this behavior. I agree that 2 and 3 are not ideal, but neither is 1. Having to mimic shell errors doesn't exactly sound like a good idea. I think whatever approach we chose we should add a section to the WAL-G docs. I'm happy to write something up.

As mentioned before, if we bring this upstream with Postgres then approach 2 would work without a wrapper script. I think that would be the cleanest option in the long run.

**Comment by sebasmannem** [comment]
I looked into this from the code and decided best we can do is distinguish missing archives from other errors.
I did a dry-run test and it looks good so far, but I still want to run a restore with this to see what the exact behaviour is.

I have submitted a PR just to share the idea.

Can you have a look?

btw:

> Personally I was surprised to find little information about this behavior. I agree that 2 and 3 are not ideal, but neither is 1. Having to mimic shell errors doesn't exactly sound like a good idea.
+1. With the PR now have a way to distinguish, but still require a script. Probably all we should do in wal-g...

> I think whatever approach we chose we should add a section to the WAL-G docs. I'm happy to write something up.
If we agree on the fix, indeed we need doc. A writeup would be very helpful.

> As mentioned before, if we bring this upstream with Postgres then approach 2 would work without a wrapper script. I think that would be the cleanest option in the long run.
[I have brought it to the PG community.](https://www.postgresql.org/message-id/7f385d14be564e5d8fecf9a3c201c8b5@mannem.nl) No responses so far.
I will give it another push once we have decided on this approach, so they have the end fix as reference...
