### ISSUE TITLE
What is the difference between FULL and FIND_FULL?

### ISSUE THREAD

**Issue by airblade** [wal-g/wal-g#1134]
### Database name
Postgresql 14

I'm using wal-g v1.1 on Ubuntu 20.04 LTS.

### Describe your problem
I have a cronjob which regularly makes and stores a full backup.

I want to set up a cronjob to delete old backups.  I was reading the docs for `delete retain`:

> `retain FULL 5` will keep 5 full backups and all deltas of them
>
> `retain FIND_FULL 5` will find necessary full for 5th and keep everything after it

But I don't understand the difference between FULL and FIND_FULL.  Please could you help me understand?

Does "deltas" mean WAL logs?

Also the docs say:

> `retain 5 --after 2019-12-12T12:12:12` keep 5 most recent backups and backups made after 2019-12-12 12:12:12

It seems neither FULL nor FIND_FULL is need when using `--after`.  Does this keep deltas too?

I'm sorry if this is the wrong place to ask usage questions – I couldn't where I should though.

Thank you!

**Comment by airblade** [comment]
Thank you @usernamedt.

With `WALG_DELTA_MAX_STEPS`'s default value of `0`, I presume there's no difference between `retain FULL 5` and `retain FIND_FULL 5`?

**Comment by usernamedt** [comment]
> Thank you @usernamedt.
> 
> With `WALG_DELTA_MAX_STEPS`'s default value of `0`, I presume there's no difference between `retain FULL 5` and `retain FIND_FULL 5`?

Yes, sure.
