### ISSUE TITLE
backup-list, backup-fetch and wal-fetch got error

### ISSUE THREAD

**Issue by tppl13** [wal-g/wal-g#114]
Writing to S3 with backup-push and wal-push works fine.
Getting data from S3 takes several minutes and give error:

$ wal-g backup-list
BUCKET: walshipping-bucket-test
SERVER: pg_dev
2018/09/11 13:11:42 GetLatest: s3.ListObjectsV2 failed: NotImplemented: A header you provided implies functionality that is not implemented.
        status code: 501, request id: cdfc8e4ef84e916fc435, host id: cdfc8e4ef84e916fc435

$ wal-g wal-fetch 000000010000000000000003 /tmp/000000010000000000000003a
BUCKET: walshipping-bucket-test
SERVER: pg_dev
2018/09/11 11:44:30 unexpected EOF
DecompressLz4: lz4 write failed
github.com/wal-g/wal-g.Lz4Decompressor.Decompress
        /home/travis/gopath/src/github.com/wal-g/wal-g/lz4_decompressor.go:15
github.com/wal-g/wal-g.(*Lz4Decompressor).Decompress
        <autogenerated>:1
github.com/wal-g/wal-g.decompressWALFile
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:558
github.com/wal-g/wal-g.DownloadAndDecompressWALFile
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:581
github.com/wal-g/wal-g.HandleWALFetch
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:515
main.main
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:131
runtime.main
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/proc.go:198
runtime.goexit
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361

$ wal-g backup-fetch /tmp/ LATEST
BUCKET: walshipping-bucket-test
SERVER: pg_dev
2018/09/11 11:56:08 NotImplemented: A header you provided implies functionality that is not implemented.
        status code: 501, request id: a03480c978409a4b45e5, host id: a03480c978409a4b45e5
GetLatest: s3.ListObjectsV2 failed
github.com/wal-g/wal-g.(*Backup).GetBackups
        /home/travis/gopath/src/github.com/wal-g/wal-g/backup.go:56
github.com/wal-g/wal-g.(*Backup).GetLatest
        /home/travis/gopath/src/github.com/wal-g/wal-g/backup.go:30
github.com/wal-g/wal-g.deltaFetchRecursion
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:151
github.com/wal-g/wal-g.HandleBackupFetch
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:110
main.main
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:140
runtime.main
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/proc.go:198
runtime.goexit
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361

**Comment by x4m** [comment]
Hi! Thanks for reporting!

Your S3 implementation does not allow ListObjectsV2. Which one do you use?

ListObjects[V1] is considered somewhat deprecated.... But it is the only way to list in some S3 versions.

**Comment by tppl13** [comment]
Thank you! Indeed, seems like it is not supported.

**Comment by x4m** [comment]
No problem.
Is it important for you?
Actually, I use myself WAL-G version in github.com/x4m/wal-g that uses old ListObjects() for the same reason. It seems incorrect to use old API, but sometimes I need it.

**Comment by tppl13** [comment]
Hi!
For some reason wal-g taken from https://github.com/x4m/wal-g is not able
to fetch whole wal file. It gets only 1258912 bytes and ends also with
error: DecompressLz4: lz4 write failed

Restoring database fails as expected with an error:
FATAL:  archive file "00000001000000000000003D" has wrong size: 12582912
instead of 16777216

In addition, backup-getch works but only with keyword LATEST.

Kontakt Andrey Borodin (<notifications@github.com>) kirjutas kuupäeval R,
14. september 2018 kell 11:32:

**Comment by x4m** [comment]
Hi @tppl13 ! did you compile master or used some of release versions?

**Comment by tppl13** [comment]
I used v0.1.3x4m10 release.

**Comment by x4m** [comment]
Is the problem persistent?
When you wal-fetch that WAL you get same error every time?
Were some previous files extracted from archive successfully?

**Comment by tppl13** [comment]
Yes, I get this error every time. 
Only backup history file (00000001000000000000003D.00000028.backup, 337 bytes) is fetched without error.
The only way for me to get files successfully from S3 is to use aws client and unzip files after that.

**Comment by x4m** [comment]
May I ask you to test release v0.1.12x4m11 ?
