### ISSUE TITLE
usage question on restore

### ISSUE THREAD

**Issue by jakeo** [wal-g/wal-g#115]
I'm performing the following operations to restore a database:

```
$ wal-g backup-fetch 9.6/main LATEST
$ cp recovery.conf 9.6/main/recovery.conf
$ rm -f 9.6/main/backup_label
```

contents of my `recovery.conf`
```
restore_command = '/usr/local/sbin/wal-restore %f %p'
```
and contents of `/usr/local/sbin/wal-restore`
```
#!/bin/bash

source /etc/default/wal-g

/usr/bin/wal-g wal-fetch $1 $2 >> /var/log/postgresql/wal.log
```
Next - after starting up postgres, I get this in the postgres logs
```
2018-09-12 02:24:46.211 UTC,,,30150,,5b9878ee.75c6,5,,2018-09-12 02:24:46 UTC,,0,LOG,00000,"invalid primary checkpoint record",,,,,,,,,""
2018-09-12 02:24:46.211 UTC,,,30150,,5b9878ee.75c6,6,,2018-09-12 02:24:46 UTC,,0,LOG,00000,"invalid secondary checkpoint record",,,,,,,,,""
2018-09-12 02:24:46.211 UTC,,,30150,,5b9878ee.75c6,7,,2018-09-12 02:24:46 UTC,,0,PANIC,XX000,"could not locate a valid checkpoint record",,,,,,,,,""
```
when doing this, there is no `./9.6/main/pg_xlog/.wal-g/prefetch` directory created, I have to manually fetch one of the WALs
```
/usr/bin/wal-g wal-fetch 00000001000000440000008C 9.6/main/pg_xlog/00000001000000440000008C
```
then `./9.6/main/pg_xlog/.wal-g/prefetch` exists and the database starts up.

Am I doing something wrong? Why does this manual `wal-fetch` have to happen? I've tested this with `0.1.12`, `0.1.11`, and `0.1.10`.

Thanks a ton!

**Comment by x4m** [comment]
Hi! Looks like wal-restore could not write to ./9.6/main/pg_xlog/
What's in /var/log/postgresql/wal.log?

chances are that you've launched wal-g backup-fetch from superuser and ?

**Comment by jakeo** [comment]
@x4m thanks for replying!

All the commands above are run as user `postgres` - and the logs I'm capturing from restore command isn't logging anything. Running the manual `wal-fetch` then restarting postgres always work. Almost like the restore command is never getting called.

```
postgres@db:~$ /usr/bin/wal-g wal-fetch 00000001000000440000008C 9.6/main/pg_xlog/00000001000000440000008C
BUCKET: <redacted>
SERVER: <redacted>
postgres@db:~$ find 9.6/main/pg_xlog/
9.6/main/pg_xlog/
9.6/main/pg_xlog/archive_status
9.6/main/pg_xlog/00000001000000440000008C
9.6/main/pg_xlog/.wal-g
9.6/main/pg_xlog/.wal-g/prefetch
9.6/main/pg_xlog/.wal-g/prefetch/running
9.6/main/pg_xlog/.wal-g/prefetch/00000001000000440000008D
9.6/main/pg_xlog/.wal-g/prefetch/000000010000004400000090
9.6/main/pg_xlog/.wal-g/prefetch/000000010000004400000094
9.6/main/pg_xlog/.wal-g/prefetch/000000010000004400000093
9.6/main/pg_xlog/.wal-g/prefetch/000000010000004400000091
9.6/main/pg_xlog/.wal-g/prefetch/00000001000000440000008E
9.6/main/pg_xlog/.wal-g/prefetch/00000001000000440000008F
9.6/main/pg_xlog/.wal-g/prefetch/000000010000004400000092
```

**Comment by x4m** [comment]
we do not know what's wrong with normal wal-fetch from restore_command
btw it'd be good to add something like -e so that exit code of wal-g would be returned to postgres
also, I think it's better to call wal-g directly from postgres without script so that pglog can catch outputs from restore_command
something like source ... && wal-g wal-fetch ....

**Comment by jakeo** [comment]
A giant derp from me for not moving the commands out of the wrapper and into `restore_command` while debugging. 

I've inlined the command, as well as turned up debugging.

```
< 2018-09-12 22:19:46.925 UTC >DEBUG:  restore_command = '. /etc/default/wal-g && /usr/local/bin/wal-g wal-fetch "%f" "%p"'
< 2018-09-12 22:19:46.925 UTC >LOG:  starting archive recovery
< 2018-09-12 22:19:46.925 UTC >DEBUG:  could not open file "pg_xlog/0000000100000044000000A5": No such file or directory
< 2018-09-12 22:19:46.925 UTC >LOG:  invalid primary checkpoint record
```

```
postgres@db:~$ aws s3 ls s3://<redacted>/wal_005/ | grep 0000000100000044000000A5
2018-09-12 22:55:03        236 0000000100000044000000A5.00000028.backup.lz4
2018-09-12 22:55:03      88945 0000000100000044000000A5.lz4
```

The only thing that works is fetching the WAL manually - then recovery continues and the database starts up.

```
postgres@db:~$ . /etc/default/wal-g && wal-g backup-list
BUCKET: <redacted>
SERVER: <redacted>
name	last_modified	wal_segment_backup_start
base_0000000100000044000000A5	2018-09-12T22:55:08Z	0000000100000044000000A5
postgres@db:~$ . /etc/default/wal-g && /usr/local/bin/wal-g wal-fetch 0000000100000044000000A5 9.6/main/pg_xlog/0000000100000044000000A5
BUCKET: <redacted>
SERVER: <redacted>
```

**Comment by x4m** [comment]
As far as i understand according to this log
```
< 2018-09-12 22:19:46.925 UTC >DEBUG:  restore_command = '. /etc/default/wal-g && /usr/local/bin/wal-g wal-fetch "%f" "%p"'
< 2018-09-12 22:19:46.925 UTC >LOG:  starting archive recovery
< 2018-09-12 22:19:46.925 UTC >DEBUG:  could not open file "pg_xlog/0000000100000044000000A5": No such file or directory
< 2018-09-12 22:19:46.925 UTC >LOG:  invalid primary checkpoint record
```
restore_command was not called. And I do not see why...
When you call it manually - it fetches necessary WAL.

**Comment by jakeo** [comment]
Yep - it's mind boggling. I'll continue to debug.

**Comment by x4m** [comment]
@tetronoz Thanks! This explains perfectly what is going on.
WAL-G does not delete backup_label, surely. But we should clearly warn user that provided PGDATA is not PGDATA. I can imagine how this causes troubles in many various ways. I even think that we should check that it is exactly the same PGDATA that we connected to... (eventually we will do offline backups, so I think that we still should keep this arg in CLI)

**Comment by x4m** [comment]
I'll explain a bit here:
Almost all files are picked from filesystem by scanning FS tree. But backup label and tablespace map are provided by pg_stop_backup(). Thus, we archive this files in last tar as if they were in the root of the archive.
When we do backup-fetch they are placed accordingly, but PostgreSQL expects them in ```data```. The absence of these files means that database crashed and it needs to do WAL replay from the last checkpoint of local WAL (even if this was archived - it still must be nearby, anything else means local data is corrupted).

In nearest versions I'll add user warnings on unusual PGDATA.

**Comment by x4m** [comment]
> Should I file the `PATH` to `gpg` issue in another issue or are we expected to define it in our wrappers/args?

There are few related open items #59 #92 . But they do not mention this problem directly.
This problem becomes more important with #111 : now you do not have to supply a lot of env vars, but with PATH you still have to do something.

I believe this problem must be addressed somehow unless we get rid of external gpg binary. But right now I do not have enough resources to investigate why Postgres do not pass PATH myself.

So, I think issue on this is welcome, but I do not expect it will be resolved soon.
