### ISSUE TITLE
Increase WAL archival speed

### ISSUE THREAD

**Issue by nikhil-postgres** [wal-g/wal-g#1155]
**### Database name**
PostgreSQL 11.7

wal-g version v0.2.14	d372cbd	2019.12.04_06:14:06	PostgreSQL

**# Issue description**
Increase speed of WAL archival upload

**### Describe your problem**

How can we make wal archival faster (wal-push)? can below parameters help increase the speed?

WALG_DISK_RATE_LIMIT
To configure disk read rate limit during backup-push in bytes per second.

WALG_NETWORK_RATE_LIMIT To configure the network upload rate limit during backup-push in bytes per second.
Concurrency values can be configured using:

WALG_UPLOAD_CONCURRENCY
To configure how many concurrency streams to use during backup uploading, use WALG_UPLOAD_CONCURRENCY. By default, WAL-G uses 16 streams.

WALG_UPLOAD_DISK_CONCURRENCY
To configure how many concurrency streams are reading disk during backup-push. By default, WAL-G uses 1 stream.

TOTAL_BG_UPLOADED_LIMIT (e.g. 1024) Overrides the default number of WAL files to upload during one scan. By default, at most 32 WAL files will be uploaded.

Archival speed works fine when there is minimum load but when there are high number of transactions during peak load then the archiving is slow and we get a lot of WALs (to be archived) resulting in high disk usage.We are archiving to S3.

Thanks,
Nikhil

**Comment by nikhil-postgres** [comment]
Hi @x4m , Is it possible to speed up WAL archival by Wal-g using parallel processes?

Thanks,
Nikhil

**Comment by x4m** [comment]
Hi!
WALG_DISK_RATE_LIMIT, WALG_NETWORK_RATE_LIMIT, WALG_UPLOAD_DISK_CONCURRENCY do not apply to wal-push.
To increase speed of archival I recommend switching to brotli compression and setting WALG_UPLOAD_CONCURRENCY to ~256, TOTAL_BG_UPLOADED_LIMIT ~1024.

**Comment by nikhil-postgres** [comment]
Hi,

Sure, I will test with these settings.

Thanks,
Nikhil

**Comment by t-ushar** [comment]
Hi @x4m 

How we can make archive upload parallel in version v0.2.19  as since v0.2.16  new feature is implemented for "parallel WAL upload"  [feature Commit](https://github.com/wal-g/wal-g/commit/5d45df8190a95ad98ee6d7c72f4387d874424252) ? Is there any different flags which we need to enable ? Also as you mentioned above with "WALG_UPLOAD_CONCURRENCY" can we see those many streams into the process to make sure this many files being uploading 


Thanks,
Tushar Takate

**Comment by serprex** [comment]
The various knobs to tune wal-g are documented [here](https://github.com/wal-g/wal-g/tree/master/docs)
