### ISSUE TITLE
What are the MySQL limitations

### ISSUE THREAD

**Issue by mkroman** [wal-g/wal-g#1180]
Hello!

I'm considering WAL-G for MySQL backups, but according to the [MySQL setup docs](https://github.com/wal-g/wal-g/blob/master/docs/MySQL.md#wal-g-for-mysql) it's unstable.

I'm hoping someone can tell me if there are any limitations or issues that I should be aware of - and I'd also like to know why it's considered unstable.

Thanks!

**Comment by x4m** [comment]
Hi Mikkel! Thank you for your interest in WAL-G.

In Postgres we have a standard API to collect history for point-in-time recovery. Namely, WAL-G must conform to the requirements of so-called ```archive_command```. We invented a bunch of performance tricks to help parallelizing ```archive_command``` interface, yet PITR setup will not change until it's changed in Postgres. And even if\when Postgres will have new ```archive modles``` technology, the current WAL-G setup process will not change much.

OTOH MySQL does not have a standard blessed way to collect\apply binlogs. From time to time we invent something better: better scan for new files, better restoration process etc. Or fix bugs in existing methods, like better computation of what binlogs may be deleted. Sometimes such fixes\enhancements are accompanied by breaking changes in WAL-G API. If you want to upgrade to a newer WAL-G you will probably have to read docs again and change something.

Maybe @mialinx can shed some more light on when we will consider MySQL API stable. But I pretty much doubt we can do it without steps taken by MySQL\MariaDB first...

**Comment by mialinx** [comment]
There are several issues:
1) Enabling GTID is highly recommended. Without GTID enabled, Point-In-Time recovery will not work properly.
2) Wal-G keeps cache about last uploaded binlog  (in `~/.walg_mysql_binlogs_cache`).  Do not forget to clear it when you wipe-and-restore your MySQL instance. Otherwise, wal-g may skip uploading some binlogs
3) Wal-G performs PITR by replaying binlogs one-by-one. Each binlog is replayed in the separate MySQL connection. This lead to problems if you are using temporary tables. (when a temporary table is created in one binlog and used in the next one).

**Comment by mkroman** [comment]
Thank you very much for your replies! It's greatly appreciated - and notes have been taken.

Are there any version-specific compatibility issues that's worth knowing about?

**Comment by mialinx** [comment]
> Are there any version-specific compatibility issues that's worth knowing about?
If you are going to do physical backups (which are recommended) - you should use xtrabackup tool appropriate for your MySQL version.

And, btw, xtrabackup have some limitations by itself: It does not work when some DDL operations (alter, etc..) are running. 
So we recommend you to take backups of replica node, and start xtrabackup tool with `--lock-ddl --lock-ddl-timeout=3600` options

**Comment by mkroman** [comment]
Closing this as I got a bunch of useful answers. Thanks!
