### ISSUE TITLE
MySQL support for incremental backup-restore?

### ISSUE THREAD

**Issue by AlexIvamoto** [wal-g/wal-g#1188]
Hello,

Is there support for incremental backups-restore for MySQL?

**Comment by jstaf** [comment]
I don't think so, but with the point-in-time restore capability, there is no point in having incremental backups. Why limit yourself to incremental backups at specific points in time when you can instead restore to any point in time down to the second?

**Comment by brunoprietog** [comment]
#1571 solves this?

**Comment by ostinru** [comment]
> #1571 solves this?

I think, yes. However, I haven't seen this used widely in production, so be careful.
And... note that you should use `xtrabackup-push` command to create backups otherwise, wal-g will not have enough metadata to restore backup.

**Comment by brunoprietog** [comment]
Great! So I guess you might want to close it then? Or it stays open for testing yet. Do you plan any release soon for this feature? Thanks!

**Comment by ostinru** [comment]
I will close this issue - tests prove that it works.

We have release ticket - #1522. Here you can track release process. However it takes loooong time, so I can suggest building `wal-g` on your own =(
