### ISSUE TITLE
[wal-g-pg 1.0(1)] delete retain error

### ISSUE THREAD

**Issue by EnochTheWise** [wal-g/wal-g#1203]
### Database name
PostgreSQL 13

# Issue description

### Describe your problem
We have an installation with wal-g version 1.0.
With automatic cleaning of obsolete backups:
```
...
[Service]
Type=oneshot
ExecStartPre=/usr/local/bin/wal-g delete retain FULL 4 --confirm
ExecStart=/usr/local/bin/wal-g backup-push /var/lib/postgres/data --full
User=postgres
Group=postgres
...
```
and it works great while there are four or more backups in the remote storage.
But if the number of full backups is less than that specified in the retention parameter, then it fails with an error:
```
# sudo -u postgres wal-g-pg delete retain FULL 4
INFO: 2022/01/25 06:41:53.471611 retrieving permanent objects
ERROR: 2022/01/25 06:41:53.960803 not found
```

**Comment by usernamedt** [comment]
Hi! This issue has been already fixed in [this PR](https://github.com/wal-g/wal-g/pull/1125)
