### ISSUE TITLE
wal-g greenplum,  function gp_create_restore_point(unknown)

### ISSUE THREAD

**Issue by nowost** [wal-g/wal-g#1219]
### Database name
GREENPLUM

# Issue description

### Describe your problem
can't create restore point

INFO: 2022/02/17 12:33:15.723572 Creating restore point with name backup_20220217T122815Z
WARNING: 2022/02/17 12:33:15.735675 GetSystemIdentifier: Unable to get system identifier
ERROR: 2022/02/17 12:33:15.736410 ERROR: function gp_create_restore_point(unknown) does not exist (SQLSTATE 42883)

### Please add config and wal-g stdout/stderr logs for debug purpose

wal-g --version
wal-g version   c2fc0a6  2022.02.17_07:42:22  GreenplumDB

[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.18.2 build 6.18.2_arenadata30-762.gitefee477.el7'
[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.18.2 build 6.18.2_arenadata30-762.gitefee477.el7) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit compiled on Dec 15 2021 16:44:42'

<details><summary>If you can, provide logs</summary>
gpadmin@adb-master-01 default]$ wal-g backup-push --config /etc/default/walg_config.yaml
WARNING: 2022/02/17 12:28:15.268988 GetSystemIdentifier: Unable to get system identifier
INFO: 2022/02/17 12:28:15.272072 Greenplum version: PostgreSQL 9.4.24 (Greenplum Database 6.18.2 build 6.18.2_arenadata30-762.gitefee477.el7) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit compiled on Dec 15 2021 16:44:42
INFO: 2022/02/17 12:28:15.276788 Checking backup prerequisites
INFO: 2022/02/17 12:28:15.276816 Checking for the existing running backup...
WARNING: 2022/02/17 12:28:15.282253 GetSystemIdentifier: Unable to get system identifier
INFO: 2022/02/17 12:28:15.306855 No running backups were found
INFO: 2022/02/17 12:28:15.306875 Checking backup prerequisites: OK
INFO: 2022/02/17 12:28:15.306882 Disconnecting from the Greenplum master.
INFO: 2022/02/17 12:28:15.310586 Running wal-g on segments
INFO: 2022/02/17 12:28:15.310919 Command to run on segment -1: nohup wal-g seg-backup-push --content-id=-1 backup_20220217T122815Z '/data1/master/gpseg-1 --add-user-data={"id":"30540c3d-2e41-4756-9f66-052a586cfa23"} --pgport=5432 --full=false --permanent=false' --config=/etc/default/walg_config.yaml >> /var/log/wal-g-log-seg-1.log 2>&1 &
INFO: 2022/02/17 12:28:15.311009 Command to run on segment 0: nohup wal-g seg-backup-push --content-id=0 backup_20220217T122815Z '/data1/primary/gpseg0 --add-user-data={"id":"1e852af9-ba16-48e5-be62-c74ba9a0f4dd"} --pgport=10000 --full=false --permanent=false' --config=/etc/default/walg_config.yaml >> /var/log/wal-g-log-seg0.log 2>&1 &
INFO: 2022/02/17 12:28:15.311042 Command to run on segment 1: nohup wal-g seg-backup-push --content-id=1 backup_20220217T122815Z '/data1/primary/gpseg1 --add-user-data={"id":"501de4d1-2f5c-4949-97aa-8d89a4a6dee5"} --pgport=10000 --full=false --permanent=false' --config=/etc/default/walg_config.yaml >> /var/log/wal-g-log-seg1.log 2>&1 &
INFO: 2022/02/17 12:33:15.677428 Poll segment backup-push state STDERR (segment -1):

INFO: 2022/02/17 12:33:15.677546 Poll segment backup-push state STDOUT (segment -1):
{"ts":"2022-02-17T12:28:23.195843273Z","status":"success"}
INFO: 2022/02/17 12:33:15.677555 Poll segment backup-push state STDERR (segment 0):

INFO: 2022/02/17 12:33:15.677559 Poll segment backup-push state STDOUT (segment 0):
{"ts":"2022-02-17T12:28:20.390383395Z","status":"success"}
INFO: 2022/02/17 12:33:15.677563 Poll segment backup-push state STDERR (segment 1):

INFO: 2022/02/17 12:33:15.677567 Poll segment backup-push state STDOUT (segment 1):
{"ts":"2022-02-17T12:28:22.859200004Z","status":"success"}
INFO: 2022/02/17 12:33:15.678399 backup-push states:
INFO: 2022/02/17 12:33:15.678614 content ID: -1, status: success, ts: 2022-02-17 12:28:23.195843273 +0000 UTC
INFO: 2022/02/17 12:33:15.678630 content ID: 0, status: success, ts: 2022-02-17 12:28:20.390383395 +0000 UTC
INFO: 2022/02/17 12:33:15.678635 content ID: 1, status: success, ts: 2022-02-17 12:28:22.859200004 +0000 UTC
INFO: 2022/02/17 12:33:15.678639 No running backups left.
INFO: 2022/02/17 12:33:15.678672 Connecting to Greenplum master.
INFO: 2022/02/17 12:33:15.723533 WAL-G output (segment -1):

INFO: 2022/02/17 12:33:15.723553 WAL-G output (segment 0):

INFO: 2022/02/17 12:33:15.723556 WAL-G output (segment 1):

INFO: 2022/02/17 12:33:15.723572 Creating restore point with name backup_20220217T122815Z
WARNING: 2022/02/17 12:33:15.735675 GetSystemIdentifier: Unable to get system identifier
ERROR: 2022/02/17 12:33:15.736410 ERROR: function gp_create_restore_point(unknown) does not exist (SQLSTATE 42883)
</details>

**Comment by usernamedt** [comment]
Hi! This error means that you need to enable the `gp_pitr` extension. Also, be aware that [this patch](https://github.com/greenplum-db/gpdb/commit/b5de722ce37c4a7b2b80a784b1de623c092ee2fc) is required to perform the correct backup restoration. It means that you should either apply and build it by yourself or use the GPDB [6.19.2+](https://github.com/greenplum-db/gpdb/releases/tag/6.19.2)

**Comment by nowost** [comment]
Thank You!
