### ISSUE TITLE
Usage of s3.DeleteObjectsInput not compatible with some 3rd party S3 implementations

### ISSUE THREAD

**Issue by Mynom** [wal-g/wal-g#123]
Hi,

the delete function uses s3.DeleteObjectsInput to remove old WALs and backups.

Unfortunately the S3 Storage we are using, doesn’t support deleting via s3.DeleteObjectsInput when versioning is enabled on a bucket. Disabling versioning is not possible due to our policy.

As I have no real GO skills, I cannot create a pull request, which would satisfy anyone who can code.

Therefore my question is, if adding an option to wal-g to use s3.DeleteObjectInput instead of s3.DeleteObjectsInput would be something you would implement into the software?

**Comment by x4m** [comment]
The change will look like this
`x4mmm-osx:wal-g x4mmm$ git diff delete.go 
diff --git a/delete.go b/delete.go
index 369da2b..62a76c4 100644
--- a/delete.go
+++ b/delete.go
@@ -158,15 +158,13 @@ func dropBackup(folder *S3Folder, backupTime BackupTime) {
        keys := append(tarFiles, sentinelKey, folderKey)
        parts := partition(keys, 1000)
        for _, part := range parts {
-
-               input := &s3.DeleteObjectsInput{Bucket: folder.Bucket, Delete: &s3.Delete{
-                       Objects: partitionToObjects(part),
-               }}
-               _, err = folder.S3API.DeleteObjects(input)
-               if err != nil {
-                       log.Fatal("Unable to delete backup ", backupTime.Name, err)
+               for _, key := range part {
+                       input := &s3.DeleteObjectInput{Bucket: folder.Bucket, Key: &key}
+                       _, err = folder.S3API.DeleteObject(input)
+                       if err != nil {
+                               log.Fatal("Unable to delete backup ", backupTime.Name, err)
+                       }
                }
-
        }
 }
 
@@ -187,12 +185,12 @@ func deleteWALBefore(walSkipFileName string, folder *S3Folder) {
        }
        parts := partitionObjects(objects, 1000)
        for _, part := range parts {
-               input := &s3.DeleteObjectsInput{Bucket: folder.Bucket, Delete: &s3.Delete{
-                       Objects: part,
-               }}
-               _, err = folder.S3API.DeleteObjects(input)
-               if err != nil {
-                       log.Fatal("Unable to delete WALS before ", walSkipFileName, err)
+               for _, key := range part {
+                       input := &s3.DeleteObjectInput{Bucket: folder.Bucket, Key: &key}
+                       _, err = folder.S3API.DeleteObject(input)
+                       if err != nil {
+                               log.Fatal("Unable to delete WALS before ", walSkipFileName, err)
+                       }
                }
        }
 }`

**Comment by Mynom** [comment]
Hi,

the idea was not to replace the current functions, but to add the modified ones.

So the function dropBackup and deleteWALBefore would be untouched, but there would be new functions like dropBackupSingle and  deleteWALBeforeSingle (or something like that) and I could call wall-g like "wal-g --single delete retain 123" or something like that.

**Comment by x4m** [comment]
Look, here's the patch in +12 lines. It does what you want.
It will be much more work to maintain ```--single``` option for WAL-G maintainers than for you to compile and test version you want with this patch.
I will have to test this option before every release. It will add code complications. It has to be documented.

**Comment by Mynom** [comment]
OK. Thanks for the feedback. That is what I thought would be the answer, but you never know until you ask.

I will check how I can implement patching and building of wal-g in my environment.
Thanks again for your time and input.

**Comment by x4m** [comment]
The easiest way to setup build if to fork this repo and update travis config. You will get your own releases.

**Comment by Mynom** [comment]
Fork created and convinced travis to build stuff. Thanks again. Im closing this Issue.

**Comment by x4m** [comment]
Cool! Have fun :)
