### ISSUE TITLE
wal-g-pg does not take PGDATA from json in backup-push operation

### ISSUE THREAD

**Issue by mcgru** [wal-g/wal-g#1233]
### Database name
Postrgesql-13

# Issue description

### Describe your problem
wal-g-pg needs the path to cluster to be written as arguments while it is writen already as PGDATA in wal-g.json config file
i use SSH way to store backups

### Please provide steps to reproduce
1. write .walg.json with "PGDATA":"/var/lib/postgresql/data" and other necessary items
2. run FAIL: wal-g-pg backup-push --config .walg.json
it creates file like basebackups_005/base_0000000300000000000000BF/tar_partitions/part_001.tar.lz4
but breaks on start to fill it
in postgresql logs: LOG:  could not send data to client: Broken pipe
3. run OK: wal-g-pg backup-push --config .walg.json /var/lib/postgresql/13/data.test

So why should i duplicate passing PGDATA to the process? 

### Please add config and wal-g stdout/stderr logs for debug purpose

{
    "PGHOST": "/var/run/postgresql",
    "__comment__PGHOST": "w2",
    "PGPORT": "5432",
    "PGUSER": "postgres",
    "PGDATA": "/var/lib/postgresql/13/data.test",
    "WALG_LOG_LEVEL": "DEVEL",
    "WALG_COMPRESSION_METHOD": "lz4",
    "WALG_SSH_PREFIX": "ssh://w2/var/backups/postgresql/w2_5432/walg",
    "SSH_PORT": "22",
    "SSH_USERNAME": "postgres",
    "SSH_PRIVATE_KEY_PATH": "/var/lib/postgresql/.ssh/id_ed25519",
    "WALG_DELTA_MAX_STEPS": "0"
}

ERROR: 2022/03/18 06:17:31.031604 CompressAndEncrypt: compression failed
github.com/wal-g/wal-g/internal.newCompressingPipeWriterError
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/compress_and_encrypt.go:21
github.com/wal-g/wal-g/internal.CompressAndEncrypt.func1
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/compress_and_encrypt.go:55
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1581
SSH error : Fail write content to file '/var/backups/postgresql/w2_5432/walg/basebackups_005/base_0000000300000000000000BF/tar_partitions/part_001.tar.lz4'
github.com/wal-g/wal-g/pkg/storages/storage.NewError
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/storage/errors.go:27
github.com/wal-g/wal-g/pkg/storages/sh.NewFolderError
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/sh/folder.go:38
github.com/wal-g/wal-g/pkg/storages/sh.(*Folder).PutObject
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/sh/folder.go:242
github.com/wal-g/wal-g/internal.(*Uploader).Upload
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/uploader.go:136
github.com/wal-g/wal-g/internal/databases/postgres.(*StreamingBaseBackup).Upload
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/databases/postgres/streaming_base_backup.go:135
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).runRemoteBackup

**Comment by mcgru** [comment]
another issue near to the current: 

`wal-g-pg delete retain 3 --confirm` duplicates WALG_SSH_PREFIX value and tries to remove WALG_SSH_PREFIX/WALG_SSH_PREFIX/file

logs:

DEBUG: 2022/03/23 10:08:41.487767 WALG_SLOTNAME=
DEBUG: 2022/03/23 10:08:41.487775 WALG_SSH_PREFIX=ssh://w2//var/backups/postgresql/w2=5432=data.test/walg
DEBUG: 2022/03/23 10:08:41.487782 WALG_STORAGE_PREFIX=
...
INFO: 2022/03/23 10:08:41.650398 retrieving permanent objects
DEBUG: 2022/03/23 10:08:42.039726 processing base_0000000300000000000000DE_backup_stop_sentinel.json
DEBUG: 2022/03/23 10:08:42.039757 processing base_0000000300000000000000DD_backup_stop_sentinel.json
DEBUG: 2022/03/23 10:08:42.039763 processing base_0000000300000000000000DB_backup_stop_sentinel.json
INFO: 2022/03/23 10:08:42.039771 Start delete
...
INFO: 2022/03/23 10:08:42.058443        will be deleted: /var/backups/postgresql/w2=5432=data.test/walg/basebackups_005/base_0000000300000000000000D7/metadata.json
...
ERROR: 2022/03/23 10:05:32.411032 file does not exist
SSH error : Fail to get object stat '/var/backups/postgresql/w2=5432=data.test/walg/var/backups/postgresql/w2=5432=data.test/walg/basebackups_005/base_0000000300000000000000D9_backup_stop_sentinel.json': file does not exist
github.com/wal-g/wal-g/pkg/storages/storage.NewError
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/storage/errors.go:27
github.com/wal-g/wal-g/pkg/storages/sh.NewFolderError
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/sh/folder.go:38
github.com/wal-g/wal-g/pkg/storages/sh.(*Folder).DeleteObjects
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/sh/folder.go:160
github.com/wal-g/wal-g/pkg/storages/storage.DeleteObjectsWhere
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/pkg/storages/storage/folder.go:51
github.com/wal-g/wal-g/internal.(*DeleteHandler).DeleteBeforeTarget
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/delete_handler.go:338
github.com/wal-g/wal-g/internal.(*DeleteHandler).HandleDeleteRetain
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/internal/delete_handler.go:144
github.com/wal-g/wal-g/cmd/pg.runDeleteRetain
        /var/tmp/portage/app-backup/wal-g-1.1-r5/work/wal-g-1.1/cmd/pg/delete.go:88
github.com/spf13/cobra.(*Command).execute

**Comment by mcgru** [comment]
Please, correct that minor bug with double (or multiple) slashes after ssh://HOST////dir .

this is buggy one: WALG_SSH_PREFIX=ssh://w2//var/backups/postgresql/w2=5432=data.test/walg
this is OK: WALG_SSH_PREFIX=ssh://w2/var/backups/postgresql/w2=5432=data.test/walg

I think as far as i can `cd ////` wal-g-pg should be able to correctly operate with WALG_SSH_PREFIX=ssh://w2////////var/backups/postgresql/w2=5432=data.test/walg

**Comment by usernamedt** [comment]
The reason of this behavior is that WAL-G is trying to create the remote backup when being called without the `PGDATA` provided as the command line argument. 

For more details, see the [remote backup](https://github.com/wal-g/wal-g/blob/master/docs/PostgreSQL.md#remote-backup) section of the documentation.

**Comment by usernamedt** [comment]
Feel free to re-open this issue if you still have any questions :)

**Comment by mcgru** [comment]
I know that this behavior is due to the lack of PGDATA in command line arguments to wal-g-pg. Issue is not about the error itself.
In my opinion, if i've already set PGDATA in .wal-g.json (or in exported environment variable) - there is no need to repeat it in command line.
Please, show me the case when it IS necessary to pass PGDATA both in .wal-g-pg and as an argument.

**Comment by mcgru** [comment]
> Feel free to re-open this issue if you still have any questions :)

Issue is not resolved. Could not find how to re-open this issue.
Should i re-create another one with same name?
