### ISSUE TITLE
backup-push hangs

### ISSUE THREAD

**Issue by Drewster727** [wal-g/wal-g#124]
Hi--
I'm running wal-g in a production AWS environment to handle pushing my backups to S3.
I had thoroughly tested this in our stage environment previously and the backup-push / backup-fetch worked flawlessly. However, stage doesn't see much load.

`AWS_REGION=us-east-1 WALE_S3_PREFIX=s3://pgbackups/production/backups/ /usr/local/bin/wal-g backup-push /mnt/ebs/postgresql-data/10/main`

The backup-push appears to work and runs for a while, but at some point it hangs writing a part file. I can see the files in S3 but the push job just never finishes. The S3 bucket is not size-restricted or anything. So, when I get up in the morning I'll see the backup-push process still running, but not doing anything.

I originally had the backup-push running on our master node, which is the only server that receives write queries (update/insert). I thought that perhaps the writes were causing some additional locking, so I moved the backup-push to the slave node (read-only queries). It worked yesterday afternoon when I ran it directly, but lo-and-behold when it ran this morning (via cron) it just never completed, but the processes remained running, not doing anything.

Is there any way I can enable some additional logging and see what's going on here? Any tips?

Thanks,
Drew

**Comment by x4m** [comment]
Hi, Drew! Plz check Postgres logs, that it does not complain about pushed WALs

**Comment by Drewster727** [comment]
@x4m hey man -- I'm not seeing anything of value in the logs other than some queries that run and a warning when I killed the backup-push process:

> 2018-10-24 14:52:14 UTC WARNING:  aborting backup due to backend exiting before pg_stop_backup was called

My disk activity (due to the backup) just kind of stops all of a sudden about 1h 28min into the backup:
![image](https://user-images.githubusercontent.com/4528753/47458713-dea61b80-d79f-11e8-8788-ae8ff5ef624c.png)

**Comment by x4m** [comment]
Which PG do you use?
What version of WAL-G do you use?
Are you doing a backup-push on master or on standby?

**Comment by Drewster727** [comment]
@x4m 

wal-g v0.1.12
PostgreSQL 10.5 (Ubuntu 10.5-2.pgdg16.04+1)

I was initially doing a backup-push on the master, the process was hanging. 
I am now running the backup-push on the standby node (I thought maybe the lack of writes on the slave would help). Just checked this morning, the push job was started 4 hours ago and it's still running (should have been done in 1.5 hours or so).

**Comment by Drewster727** [comment]
Just ran it again on the slave node.

You'll see below that the last backup file was at 11:07am.
The current time is 11:29 and I have not seen any new logs from wal-g. Nothing in the postgresql logs either. Any way to turn on additional logging?

![image](https://user-images.githubusercontent.com/4528753/47515693-2d5bc000-d849-11e8-9f12-65414c5542e6.png)

Disk activity basically says it's not doing anything after ~11:07am:
![image](https://user-images.githubusercontent.com/4528753/47515881-9b07ec00-d849-11e8-88b7-84643cf79c31.png)

It never completes and finalizes the backup.

**Comment by x4m** [comment]
WAL-G has no additional logging..
seems like a deadlock or something like this...
Do you observe pg_contol.tar.lz4 in tar_partitions?
are there json files in backups?

**Comment by x4m** [comment]
Drew, is there only one PG instance on that machine?
Do you have WAL segment number 862C and a base with half of a terabyte of data? WAL segment number seems quite small...

**Comment by Drewster727** [comment]
Only one PG instance per node. Master has one, slave has one. Both on the same version.
I don't see that WAL segment. The database size is roughly 630GB.
I just ran the backup-push manually this afternoon and it succeeded... I'm confused.

**Comment by x4m** [comment]
>I don't see the 862C WAL segment -- where did you see that?
basebackups are named after WAL seg no of pg_backup_start() call, there are 6 nonsignificant zeroes, thus, your database generated 0x862C WAL files through it's life, it's about a terabyte of WAL.
But all this does not give us anything usefull, that was just a wild guess that you connect to one database but backup files of another...

>I just ran the backup-push manually this afternoon and it succeeded... 
This seems very much like deadlock caused by race conditions. But it's not 100%, there may be other external causes.
I have no goods ideas how to debug your case, but I'm thinking about it. Plz post updates when you have some new data.

**Comment by Drewster727** [comment]
@x4m I moved the job to before our ETLs run and it appears to be working better. I'm not sure why this was occurring but it must have been deadlocks as you said. I'm closing for now and will update if I find anything else related.
