### ISSUE TITLE
How to restore PostgreSQL backup to point in time

### ISSUE THREAD

**Issue by dmekhov** [wal-g/wal-g#1244]
I couldn't find in the documentation how to restore PG backup to point in time.  
Now we use the latest point on changing backup and wal-g continues to fetch the changes and cant finish.

We want to fix point for resoring at the moment when command is run. 

We use PostgreSQL 13

**Comment by usernamedt** [comment]
Hi! I think that this question is relevant to PostgreSQL, not WAL-G itself. You can read about recovery targets [in this doc](https://www.postgresql.org/docs/14/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET).

**Comment by usernamedt** [comment]
Feel free to re-open if you still have any questions.
