### ISSUE TITLE
Using backup-fetch for stage restores

### ISSUE THREAD

**Issue by Drewster727** [wal-g/wal-g#125]
I have the following process in place using wal-g:

Nightly production PostgreSQL 10.5 backup
- **backup-push** to S3

Nightly stage PostgreSQL 10.5 restore
- stop postgresql service
- **backup-fetch** from S3
- [pg_resetwal](https://www.postgresql.org/docs/10/static/app-pgresetwal.html)
- start postgresql service

Essentially we're blowing out the existing $PGDATA directory on stage and letting backup-fetch recreate it for us with the fresh backup from S3.

This appears to work fine.. i.e. the tables exist and we can query, etc..

**Problem**
Various queries are throwing errors relating to either missing indexes or tables needing to be reindexed:
> index "sometable_pkey" contains unexpected zero page at block 287641 HINT: Please REINDEX it.

When we kick off a reindex on the stage database, we get:
> ERROR:  could not access status of transaction 184681164
> DETAIL:  Could not open file "pg_subtrans/0B02": No such file or directory.
> CONTEXT:  while checking uniqueness of tuple (1,6) in relation "pg_statistic"

If we can't restore from an S3 backup and be fully available, I can't really trust it...

**Questions**
Is this something that could be caused by creating a live backup in prod when it's mid-transaction?
Is there are protocol to follow after restoring from the S3 backup via the backup-fetch process?
Any thoughts or ideas?

**Versions**
wal-g v0.1.12
PostgreSQL 10.5 (Ubuntu 10.5-2.pgdg16.04+1)

**PG Extensions**:
btree_gist 1.5
hstore 1.4
pg_buffercache 1.3
pg_stat_statements 1.5
plpgsql 1.0
postgis 2.5.0

**Comment by x4m** [comment]
Hi!
No, backuping mid-anywhere should be safe.
```pg_resetwal``` is not safe, you should restore db to consistent state with WALs from archive.
Postgres online backups are working like this:
0. you setup archive_command to save WALs (for example ```/usr/bin/wal-g wal-push %p```)
1. call pg_start_backup() it sets specific WAL mode when all neccesary data is written to WAL and select start point
2. simply copy inconsistent backup
3. call pg_stop_backup() to inform db that it can get back to normal WAL and save consistency point.

Now you have inconsisten backup and WALS between start point and consistensy point that are necessary to make copy consistent. Without this WALs DB cannot be restored.
When you start a db, you give it restore.conf with restore_command (for example /usr/bin/wal-g wal-fetch "%f" "%p" ) and it will retrieve all necessary WALs from archive and restore db to the consistency point.

After that, it will keep applying WALs until it gets to recovery target, but that is another story called PITR.

**Comment by Drewster727** [comment]
@x4m  ahhh, so... you're saying:

- Stop running pg_resetwal
- Once the backup-fetch completes, drop in a recovery.conf file that fetches WALs to return it to a consistent state?

Keep in mind this is a **stage** database, so I don't necessarily want it to keep up with prod WALs consistently during the day. I just want a point-in-time restore each night and call it good.

**Comment by Drewster727** [comment]
@x4m I think I got it figured out. 

Per [this](https://www.postgresql.org/docs/10/static/recovery-target-settings.html) link on setting the recovery_target to "immediate" my stage postgres will quickly catch up to a consistent state then pause WAL fetching once it reaches that state -- then I can remove the recovery.conf file.

That did the trick. Thanks!

**Comment by x4m** [comment]
Thanks for reporting! Bug reports make WAL-G better, we all want safe backups :)

**Comment by Drewster727** [comment]
@x4m 

Well, I thought I had this resolved. The restore process today left my stage database in a not-so-good state.

`
2018-10-31 18:28:37 UTC LOG:  request to flush past end of generated WAL; request 185/D27A6A38, currpos 185/D1CEAA78
2018-10-31 18:28:37 UTC CONTEXT:  writing block 3277944 of relation base/16386/51478
2018-10-31 18:28:37 UTC ERROR:  xlog flush request 185/D27A6A38 is not satisfied --- flushed only to 185/D1CEAA78
2018-10-31 18:28:37 UTC CONTEXT:  writing block 3277944 of relation base/16386/51478
2018-10-31 18:28:37 UTC WARNING:  could not write block 3277944 of base/16386/51478
2018-10-31 18:28:37 UTC DETAIL:  Multiple failures --- write error might be permanent.
`

`
2018-10-31 19:59:38 UTC ERROR:  index "survey_x_created_date" contains unexpected zero page at block 289519
2018-10-31 19:59:38 UTC HINT:  Please REINDEX it
`

It's like it couldn't properly get to a consistent state with the WALs after restoring from the backup.

Any ideas?

**Comment by x4m** [comment]
@Drewster727 , are you sure you did not do pg_resetwal on this cluster? somehow cluster thinks that it was in consistent state while it have not yet been there.

**Comment by Drewster727** [comment]
@x4m I was originally doing the pg_resetwal before you had mentioned not to do that. My latest process does not resetwal on the stage box I'm restoring to.

**Comment by x4m** [comment]
@Drewster727 do you constantly get broken cluster after restore?
Is your production cluster consistent?

There are various smote tests to check postgres consistency. Most common ways:
1. To check heap files you can pg_dump or COPY TO  to /dev/null data.
2. To verify indexes you can use amcheck extension

Do you have data_checksums enabled?

**Comment by Drewster727** [comment]
@x4m we're still seeing some odd behavior but it appears to be working now after restarting the pg service once it gets caught up. Prod cluster is consistent.

I'm going to close this for now, but if we see any further odd behavior I'll reopen and get more details added.

Thanksf or your help!

-Drew

**Comment by x4m** [comment]
Drew, thanks! Bug reporting is doing WAL-G better. But I hope you DB will be OK :)
