### ISSUE TITLE
Failure to find files in S3 results in stack traces..

### ISSUE THREAD

**Issue by diranged** [wal-g/wal-g#126]
When Postgres is running in its normal `recovery_command`.. mode (pulling from S3), the 0.1.12 and 0.1.13 releases of WAL-G throw these giant stack traces all the time:
```
BUCKET: xxx
SERVER: xxx/xxx
2018/11/02 19:28:59 Archive '%s' does not exist 00000003.history
github.com/wal-g/wal-g.DownloadAndDecompressWALFile
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:590
github.com/wal-g/wal-g.HandleWALFetch
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:515
main.main
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:131
runtime.main
	/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/proc.go:198
runtime.goexit
	/home/travis/.gimme/versions/go1.10.4.linux.amd64/src/runtime/asm_amd64.s:2361
```

**Comment by x4m** [comment]
@diranged plz check that this stacks are gone in recent releases.

**Comment by diranged** [comment]
Thanks we'll try to roll this out today or next week.

**Comment by x4m** [comment]
In 0.2+ releases WAL-G will report errors with stacks iff WALG_LOG_LEVEL is DEVEL.
I'll close this, for now, please reopen if you have more questions. Thanks!
