### ISSUE TITLE
Is 2.0.x close to GA

### ISSUE THREAD

**Issue by luss** [wal-g/wal-g#1265]
if not, is there a punchlist of remaining blockers?

**Comment by alexmv** [comment]
Same question!  The last tag which wasn't tagged as an rc was 1.1, in August 2021.  It looks like there's been a bunch of exciting work since then -- but it isn't clear to outside observers what the stability of it is.

**Comment by usernamedt** [comment]
I am happy to tell you that v2.0 is finally available on our [releases page](https://github.com/wal-g/wal-g/releases/tag/v2.0.0) :)

**Comment by luss** [comment]
Great.  Congrats to all who contributed.  Sadly I have not yet (other than
whining for GA).  :-)

**Comment by x4m** [comment]
@luss in fact this issue contirbutes a lot to developers spirit :) It's inspiring to see someone is looking forward to the release, thank you and @alexmv !

But, anyway, we would be happy to see pull requests and feature requests from you. And bug reports if you observe one...
