### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by solo-untld** [wal-g/wal-g#1283]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Issue description
https://github.com/wal-g/wal-g/blob/master/docs/PostgreSQL.md
all install instruction is not applicable for v2.0.0 and go 1.18.3
wal-g now cannot be install like module so how install it by another way is mistake.
### Describe your problem
// here is your problem
I've tried to use installation guide on
Oracle Linux 8
CentOS 8 stream
ubuntu 20.04
all systems fail

you change syntax of install now it pg_install instead of make install and so one... Please  keep wiki in current status.

By Wiki User can use your tool only by binary, that builded only for Ubuntu :|
### Please provide steps to reproduce
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

**Comment by OrangeDog** [comment]
See #1294

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1294
