### ISSUE TITLE
Support for WAL-E

### ISSUE THREAD

**Issue by ratclick** [wal-g/wal-g#1286]
### Database name
PostgreSQL-12.10

# Issue description
Will wal-g always support wal-fetch and backup-fetch, wal-restore from GCP that was created by wal-e

### Describe your problem
- We have wal-e running on our production serverr and we have wal-e pushing backup files and wal files into Google cloud storage
- We have a read-replica database setup with wal-g doing backup-fetch and wal-restore to keep the databases in sync

**Will all future versions of wal-g support this?**

**Comment by x4m** [comment]
Predicting future is hard. Predicting _all_ future version is even harder.
We don't have any plans on deprecating commands ```wal-push```, ```wal-fecth```, ```backup-push``` and ```backup-fetch``` for Postgres. WAL-G will turn 5 yo this summer. I doubt such deprecation can take place in next 5 years.
But I also doubt that it will be most efficient WAL-G's interface for a long. Postgres 15 will bring us archive modules. So we will support this cool new feature. And new archive_module will be slightly better than old ```wal-push```. But these versions is yet to come.

**Comment by ratclick** [comment]
Thank you for a prompt answer :) .
