### ISSUE TITLE
Debug logs may leak storage secrets

### ISSUE THREAD

**Issue by x4m** [wal-g/wal-g#1324]
Currently WALG_LOG_LEVEL=DEVEL will output all S3\GCP\Azure keys. I think we should mark some storage params as secrets and never under any circumstances output it.

**Comment by LeGEC** [comment]
as mentioned in the PR I opened :

PR #1368 proposes a fix, currently coded on top of :
#1367 - Only dump relevant env variables with LOG_LEVEL=DEVEL

PR #1368 requires a review of the settings marked as "secret" :  
I built that list by trying to make educated guesses from the names of the constants, and their usage in wal-g's code, but I am in no way an expert in many of the involved libraries (sqlserver, gp, aws, swift ...), and someone should check whether the list I built is correct (do we want to hide all of these values ?) and complete (are these all the settings that need to be hidden ?)

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1368 and https://github.com/wal-g/wal-g/pull/1367
