### ISSUE TITLE
Unable to complete full backup

### ISSUE THREAD

**Issue by petr-tichy** [wal-g/wal-g#1336]
### Database
Postgres 13 with Citus
wal-g version v2.0.1    b7d53dd 2022.08.25_09:34:18     PostgreSQL

# Issue description

### Describe your problem
I'm unable to complete a full backup. It takes 2-3 hours to upload the data to Azure Blob, and then fails with 
```
Failed to stop backup: QueryRunner StopBackup: stop backup failed: ERROR: non-exclusive backup is not in progress (SQLSTATE 55000)
```

In PG log, the backup starts with usual
```
2022-09-14 13:23:59.261 UTC [17834] LOG:  checkpoint starting: immediate force wait
2022-09-14 13:24:01.991 UTC [17834] LOG:  checkpoint complete: wrote 59320 buffers (1.1%); 0 WAL file(s) added, 0 removed, 14 recycled; write=2.534 s, sync=0.120 s, total=2.730 s; sync files=3739, longest=0.053 s, average=0.001 s; distance=223187 kB, estimate=734685 kB
```
then in few minutes the following line appears
```
2022-09-14 13:27:00.479 UTC [18319] postgres@mydb WARNING:  aborting backup due to backend exiting before pg_stop_backup was called
```
Since this point the backup will fail with
```
INFO: 2022/09/14 13:27:35.319264 Calling pg_stop_backup()
WARNING: 2022/09/14 13:27:35.329946 Failed to stop backup: QueryRunner StopBackup: stop backup failed: ERROR: non-exclusive backup is not in progress (SQLSTATE 55000)
```
in wal-g log and 
```
2022-09-14 13:27:35.324 UTC [23913] postgres@mydb ERROR:  non-exclusive backup is not in progress
2022-09-14 13:27:35.324 UTC [23913] postgres@mydb HINT:  Did you mean to use pg_stop_backup('t')?
2022-09-14 13:27:35.324 UTC [23913] postgres@mydb STATEMENT:  SELECT labelfile, spcmapfile, lsn FROM pg_stop_backup(false)
```
in PG log
### Please provide steps to reproduce
`wal-g backup-push --full /var/lib/postgresql/13/main`

### Please add config and wal-g stdout/stderr logs for debug purpose
```
{
        "WALG_AZ_PREFIX": "###",
        "AZURE_STORAGE_ACCOUNT": "###",
        "TOTAL_BG_UPLOADED_LIMIT": 1024,
        "WALG_COMPRESSION_METHOD": "brotli",
        "WALG_UPLOAD_CONCURRENCY": 24,
        "WALG_UPLOAD_DISK_CONCURRENCY": 32,
        "WALG_DELTA_MAX_STEPS": 5,
        "PGDATA": "/var/lib/postgresql/13/main",
        "PGUSER": "postgres",
        "PGPORT": 5433
}
```
running with WALG_LOG_LEVEL=DEVEL gives no clue

This might be something in our environment but I wasn't able to find it.

Any help is appreciated.

**Comment by x4m** [comment]
It looks like you are using connection pooler (pgbouncer?) in transaction mode. WAL-G is compatible only with session mode.

**Comment by petr-tichy** [comment]
Thanks for quick reply. Yes, that was it.
We are using pgbouncer on port 5432. That is the reason for `"PGPORT": 5433` in the `.walg.json` above, which apparently doesn't do anything, but is accepted. By looking at https://github.com/wal-g/wal-g/blob/v2.0.1/internal/config.go#L719 I got the impression that this should work. Is that so?

**Comment by petr-tichy** [comment]
Yes, that was it, thanks for quick reply.
I my case, the pgbouncer runs on port 5432 while Postgres listens on 5433. The issue with the above config might have been in the missing quotes around port number on the `"PGPORT": 5433` line. Strange that the pg library doesn't complain about it.
