### ISSUE TITLE
Unable to restore big database on Postgresql 9.6

### ISSUE THREAD

**Issue by nicholasklem** [wal-g/wal-g#1338]
### Database name
Postgresql 9.6 (9.6.3-1.pgdg16.04+1) on ubuntu 1604. wal-g on machine doing backup is 0.2.15.

# Issue description
Postgresql is unable to start up from a backup.

### Describe your problem
We have multiple databases using wal-g as an acrhive and backup solution. 

On our biggest one (12T) restore fails.

wal-g backup-fetch completes successfully. But upon startup postgresql fails with 
```
 FATAL:  WAL ends before end of online backup
 ```
like this:

```
Sep 15 19:26:05 postgresql-prod-1008-03-c postgresql[23558]: [2736-1] db=,app=,user=,rhost= LOG:  restored log file "0000000100005F68000000FC" from archive
Sep 15 19:26:05 postgresql-prod-1008-03-c postgresql[23558]: [2737-1] db=,app=,user=,rhost= LOG:  restored log file "0000000100005F68000000FD" from archive
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23558]: [2738-1] db=,app=,user=,rhost= LOG:  redo done at 5F68/FDFFF7F0
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23558]: [2739-1] db=,app=,user=,rhost= LOG:  last completed transaction was at log time 2022-09-12 20:06:41.008747+00
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23558]: [2740-1] db=,app=,user=,rhost= LOG:  restored log file "0000000100005F68000000FD" from archive
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23558]: [2741-1] db=,app=,user=,rhost= FATAL:  WAL ends before end of online backup
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23558]: [2741-2] db=,app=,user=,rhost= HINT:  All WAL generated while online backup was taken must be available at recovery.
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23556]: [3-1] db=,app=,user=,rhost= LOG:  startup process (PID 23558) exited with exit code 1
Sep 15 19:26:06 postgresql-prod-1008-03-c postgresql[23556]: [4-1] db=,app=,user=,rhost= LOG:  terminating any other active server processes
Sep 15 19:26:07 postgresql-prod-1008-03-c postgresql[23556]: [5-1] db=,app=,user=,rhost= LOG:  database system is shut down
```

recovery.conf:
```
standby_mode = 'off'
recovery_target = 'immediate'
restore_command = 'envdir /etc/wal-g/env wal-g wal-fetch %f %p'
```

The machine running the backups is running `wal-g 0.2.15`. Upgrade of wal-g is hard because it is running Ubuntu 16.04.
We have tested restore with both `wal-g 0.2.15` and `wal-g 2.0.1` with the same result.

Restore testing has been working fine for years, but started failing recently. We suspect it is related to the growth and size of database.

Any tips on how to get restore working again?

**Comment by x4m** [comment]
Can you use wal-show command to check if WAL is actually there? it's only in 2.0 but 100% compatible with WAL storage

**Comment by nicholasklem** [comment]
The wal-show command did not return.

Backporting `wal-g` version 2.0.1 to Ubuntu 1604, and doing both the backup and restore with this version has resolved the challenge, this database is now has restorable backups again :-)
