### ISSUE TITLE
Add option to restore specific PostgreSQL database

### ISSUE THREAD

**Issue by MANnsz** [wal-g/wal-g#1339]
I have postgresql cluster with n database: db1, db2, db3.
wal-g backuped all databases from this cluster.
Can you add option to restore specific database?
Example: wal-g backup-fetch destination_directory backup_name --database db1 --database db2

**Comment by parisni** [comment]
[There is an experimental parial restore feature](https://wal-g.readthedocs.io/PostgreSQL/)
```bash
wal-g backup-fetch /path LATEST --restore-only=my_database,"another database",database/my_table
```
