### ISSUE TITLE
Run WAL-G for Postgres data stored as Docker volume

### ISSUE THREAD

**Issue by devaskim** [wal-g/wal-g#1347]
### Database name
Postgres 12

### Describe your problem
We are using monolith Docker [Thingsboard](https://thingsboard.io/docs/getting-started-guides/what-is-thingsboard/) (IoT platform) image ([Docker hub link](https://hub.docker.com/r/thingsboard/tb-postgres/) ) where Postgres [is installed](https://github.com/thingsboard/thingsboard/blob/master/msa/tb/docker-postgres/Dockerfile#L43) from Debian `apt` repository while building the image. All data is stored on the host machine through Docker volume feature. So we have access to Postgres `data` directory and `postgresql.conf` file.

Is it possible to use WAL-G with this architecture? Or do we need to patch [Thingsboard  Dockerfile file](https://github.com/thingsboard/thingsboard/blob/master/msa/tb/docker-postgres/Dockerfile) to install WAL-G in the same manner as it is already done for Postgres database?

Thanks in advance

**Comment by usernamedt** [comment]
WAL-G needs two things to make a successful backup:
1. Read access to data directory
2. Connection to Postgres cluster instance (by default, through 5432 port)

If you can provide these, you should be good to go.

**Comment by devaskim** [comment]
Thanks @usernamedt I will expose postgres port from Docker and try to run.
