### ISSUE TITLE
Fail to compile from source

### ISSUE THREAD

**Issue by tamalsaha** [wal-g/wal-g#138]
I am trying to rebuild the binary on a Ubuntu 18.04 machine. I am getting the following error:

```console
~/g/s/g/wal-g $ go get github.com/wal-g/wal-g
# github.com/wal-g/wal-g/vendor/github.com/google/brotli/go/cbrotli
wal-g/vendor/github.com/google/brotli/go/cbrotli/reader.go:13:10: fatal error: brotli/decode.h: No such file or directory
 #include <brotli/decode.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

What do I need to do for `brotli` ?

Thanks.

**Comment by x4m** [comment]
I do not know, maybe you can add something to build.sh to produce necessary build? Or add script that will produce version you want?

Also, we could make brotli built with gotags like lzo. This will partially solve the problem, but I really expect that this compression algorithm is far superior to lz4 for typical database workloads.

**Comment by tamalsaha** [comment]
I just tried with an Alpine specific (need to install compiler and removed docker-compose parts) `build-alpine.sh` and run it inside `golang:1.11.2-alpine` Docker image using `make alpine` command. You can see my change here: https://github.com/kubedb/wal-g/commit/d83b9b08f519adcbc4db5135ba992d4194801882

But I am getting a new error from zstd:

```
+ make
(cd cmd/wal-g && go build  -ldflags "-s -w -X main.BuildDate=`date -u +%Y.%m.%d_%H:%M:%S` -X main.GitRevision=`git rev-parse --short HEAD` -X main.WalgVersion=`git tag -l --points-at HEAD`")
../../zstd_decompressor.go:4:2: build constraints exclude all Go files in /go/src/github.com/wal-g/wal-g/vendor/github.com/DataDog/zstd
make: *** [Makefile:30: cmd/wal-g/wal-g] Error 1
Makefile:33: recipe for target 'alpine' failed
```

Do you know where this build tag is defined?

**Comment by tamalsaha** [comment]
The error was fixed after I removed `CGO_ENABLED=0` .
https://github.com/golang/go/issues/24433

**Comment by tamalsaha** [comment]
Looks like it worked 

```
~/g/s/g/w/wal-g (alpine) $ file cmd/wal-g/wal-g 
cmd/wal-g/wal-g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped

```

**Comment by Tinsane** [comment]
HI!
The possibility of the Alpine build is very cool! Unfortunately, none of the active WAL-G developers use Alpine so for us, it's impossible to validate the correctness of the build. You can maintain it by yourself but in such a case it gonna be easier for you if you refactor the Alpine build logic in such a manner, that we shouldn't make build process changes in both scripts for Alpine and other OSs.
