### ISSUE TITLE
commit reverted updates on debug logging

### ISSUE THREAD

**Issue by LeGEC** [wal-g/wal-g#1387]
For some reason :

the following commit

https://github.com/wal-g/wal-g/commit/273930d41ceb66df247f985e97224730a9e99d49

completely reverted #1367 and #1368

setting LOG_LEVEL=DEVEL will once again dump *all* variables and display secrets

**Comment by usernamedt** [comment]
That's sad. I'll have a look

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1389
