### ISSUE TITLE
Why pg_wal/*.history are excluded?

### ISSUE THREAD

**Issue by asyd** [wal-g/wal-g#1388]
### Database name

* postgresql (13)

# Issue description

After upgrade wal-g from a (very) old version (without any other issue!) I'm surprised to notice that `pg_wal/*.history` seem to lacks in full backup, that prevent me to fix a `recovery_target_timeline` in `postgresql.auto.conf`. Off course, I can restore by omitting the `target_timeline` but I'm wondering if there a good reason to not include them in backup.

No particular configuration except requirements (s3 variables) 

### Please provide steps to reproduce

* Perform a full backup
* Restore with a `recovery_target_timeline` in `postgresql.auto.conf`

### Please add config and wal-g stdout/stderr logs for debug purpose

```
ERROR: 2022/11/23 14:22:49.899876 Archive '00000004.history' does not exist
2022-11-23 14:22:49.904 UTC [23905] FATAL:  recovery target timeline 4 does not exist
```

Thanks!

**Comment by usernamedt** [comment]
Hi! We intentionally do not include the `pg_wal` directory contents into some specific backup. `.history` files and WAL segments are stored in a separate `wal_005` backup storage directory, that is shared for all of the backups. `.history` files should be archived among the regular WAL files by the Postgres archiver via the `archive_command`.

Can you please attach the output of the `wal-g st ls wal_005` command?

**Comment by asyd** [comment]
@usernamedt all I have are `wal` files, but `.history` files are present in the master:

```
% ls -1 pg_wal/*.history
pg_wal/00000002.history
pg_wal/00000003.history
pg_wal/00000004.history
```

The command I used to perform a backup:

```
/usr/bin/envdir /etc/wal-g.d/env /usr/local/bin/wal-g backup-push /home/postgres/data/${PG_VERSION}/main
```

and variables defined by the `envdir`:

```
AWS_ACCESS_KEY_ID
AWS_ENDPOINT
AWS_REGION
AWS_SECRET_ACCESS_KEY
http_proxy
https_proxy
no_proxy
PATH
PGHOST
WALE_S3_PREFIX
WALG_PGP_KEY_PATH
```

In `files_metadata` I can see:
```
❯ cat /tmp/files_metadata.json | jq '.Files|keys' | grep pg_wal
  "/pg_wal",
```

but I'm not sure if all files are included or only directories
