### ISSUE TITLE
Logs for upload retry errors

### ISSUE THREAD

**Issue by bithavoc** [wal-g/wal-g#14]
It's a bit hard to debug what the issue is with failed uploads, the following error doesn't tell much:
```
postgres_1  | 2017/08/19 11:54:20 upload: failed to upload 'pg_xlog/000000010000000000000091'. Restarting in 1.75 seconds
```

A more useful output would be:
```
2017/08/19 11:56:27 upload: failed to upload 'pg_xlog/000000010000000000000091': RequestError: send request failed
postgres_1  | caused by: Put https://backups.s3.amazonaws.com/wal-g/wal_005/000000010000000000000091.lz4: x509: certificate signed by unknown authority. Restarting in 2.02 seconds
service_1   | Insert
```

upload.go
```
if multierr, ok := e.(s3manager.MultiUploadFailure); ok {
				log.Printf("upload: failed to upload '%s' with UploadID '%s'. Restarting in %0.2f seconds", path, multierr.UploadID(), et.wait)
			} else {
				log.Printf("upload: failed to upload '%s': %s. Restarting in %0.2f seconds", path, e.Error(), et.wait)
			}
```

**Comment by fdr** [comment]
That sounds reasonable.

**Comment by x4m** [comment]
I think this code still worth attention. From time to time I get there "Bucket not found" error...

**Comment by x4m** [comment]
@bithavoc, thanks, pushed.
It is not perfect still. 
`2017/10/26 11:37:24 upload: failed to upload 'walg_test_local/basebackups_005/base_0000000100000002000000E3/tar_partitions/part_001.tar.lz4': NoSuchBucket: The specified bucket does not exist.
	status code: 404, request id: 8d475e73d6de54a2, host id: . Restarting in 1.78 seconds
2017/10/26 11:37:25 upload: failed to upload 'walg_test_local/basebackups_005/base_0000000100000002000000E3/tar_partitions/part_001.tar.lz4': NoSuchBucket: The specified bucket does not exist.
	status code: 404, request id: e997ca91b04ede6d, host id: . Restarting in 2.19 seconds
2017/10/26 11:37:28 upload: failed to upload 'walg_test_local/basebackups_005/base_0000000100000002000000E3/tar_partitions/part_001.tar.lz4': NoSuchBucket: The specified bucket does not exist.
	status code: 404, request id: 04b65d435dfadd97, host id: . Restarting in 4.26 seconds
2017/10/26 11:37:32 upload: failed to upload 'walg_test_local/basebackups_005/base_0000000100000002000000E3/tar_partitions/part_001.tar.lz4': NoSuchBucket: The specified bucket does not exist.
	status code: 404, request id: 16c1df37a4e56311, host id: . Restarting in 8.75 seconds`

There is no hope that bucket will magically appear.

**Comment by x4m** [comment]
I'll close this issue, but if you will have some more nice code please create new.
