### ISSUE TITLE
Problem when building from source code for the Red Hat family

### ISSUE THREAD

**Issue by vitabaks** [wal-g/wal-g#1412]
There is no problem with the build for Debian based linux, but there is a problem for Red Hat-based distributions 
similar to this https://github.com/wal-g/wal-g/issues/453

although I have installed the `lzo-devel` package

```
[root@pgnode01 wal-g]# ls -l /usr/lib64 | grep lzo
lrwxrwxrwx  1 root root      16 May 11  2019 liblzo2.so -> liblzo2.so.2.0.0
lrwxrwxrwx  1 root root      16 May 11  2019 liblzo2.so.2 -> liblzo2.so.2.0.0
-rwxr-xr-x  1 root root  167584 May 11  2019 liblzo2.so.2.0.0
lrwxrwxrwx  1 root root      15 May 11  2019 libminilzo.so -> libminilzo.so.0
-rwxr-xr-x  1 root root   16160 May 11  2019 libminilzo.so.0
```

I tried to export LD_LIBRARY_PATH=/usr/lib64 with no effect.

Steps:

```
git clone --branch v2.0.1 --single-branch https://github.com/wal-g/wal-g.git
cd wal-g
export PATH=$PATH:/usr/local/go/bin
export USE_BROTLI=1
export USE_LIBSODIUM=1
export USE_LZO=1
make deps
GOBIN=/usr/local/bin make pg_install
```

Result:

```
(cd main/pg && go build -mod vendor -tags "brotli libsodium lzo" -o wal-g -ldflags "-s -w -X github.com/wal-g/wal-g/cmd/pg.buildDate=`date -u +%Y.%m.%d_%H:%M:%S` -X github.com/wal-g/wal-g/cmd/pg.gitRevision=`git rev-parse --short HEAD` -X github.com/wal-g/wal-g/cmd/pg.walgVersion=`git tag -l --points-at HEAD`")
# github.com/wal-g/wal-g/main/pg
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -llzo2
collect2: error: ld returned 1 exit status

make: *** [Makefile:39: pg_build] Error 2
```

I checked on CentOS versions 7, 8, 9, and RockyLinux, the problem is the same.

Without LZO built successfully. But I understand that without this option, the compression modes `lz4`, `lzma` will not work.

**Comment by usernamedt** [comment]
Hi! You can build with `lz4` and `lzma` without `lzo` enabled.

**Comment by vitabaks** [comment]
@usernamedt Thanks for the reply, that's great!

Could you tell me what exactly the lZO option is for?  What functionality can I lose if I build wal-g for postgresql without this option?

**Comment by usernamedt** [comment]
> @usernamedt Thanks for the reply, that's great!
> 
> Could you tell me what exactly the lZO option is for? What functionality can I lose if I build wal-g for postgresql without this option?

The main consequence is that you'll loose the WAL-E backward compatibility, so most probably you won't be able to restore backups taken with WAL-E.

**Comment by usernamedt** [comment]
Closing this for now. Feel free to reopen if you have any questions.
