### ISSUE TITLE
Question: Should I be worried about extraction errors?

### ISSUE THREAD

**Issue by drjeep** [wal-g/wal-g#1432]
When restoring backups from S3 using `wal-g backup-fetch` I occasionally see error logs like these

```
INFO: 2023/02/08 08:29:02.319700 Finished extraction of part_171.tar.lz4
ERROR: 2023/02/08 08:29:02.319750 Extraction error in part_171.tar.lz4: extractOne: Interpret failed: Interpret: copy failed: read tcp 10.72.23.46:49298->10.1.129.53:443: read: connection timed out
```

Should I be worried about these or does the INFO log mean the download was retried and restored successfully?

**Comment by x4m** [comment]
Hi! Failed downloads will be retries for some time. If WAL-G have zero exit code - extraction is complete.
Either way to check - you won't be able to start incomplete database download - WAL-G will place pg_control file last if everything is already correct.

**Comment by drjeep** [comment]
Thank you
