### ISSUE TITLE
wal-g 2.0.1 do not support glibc 2.17

### ISSUE THREAD

**Issue by MathCharton** [wal-g/wal-g#1438]
### Database name
PostgreSQL 12 on centos7

# Issue description
I cant use wal-g 2.0.1 on my centos7 instances

### Describe your problem
I cant install c because i use glibc 2.17 and wal-g needs glibc 2.25 and i dont want to use glibc 2.25

How can I solve this problem ??
Do you think it is a good idea to build my own RPM with wal-g 2.0.1 and glibc 2.17 from centos7 ??

Thanks

**Comment by usernamedt** [comment]
> ### Database name
> PostgreSQL 12 on centos7
> 
> # Issue description
> I cant use wal-g 2.0.1 on my centos7 instances
> 
> ### Describe your problem
> I cant install c because i use glibc 2.17 and wal-g needs glibc 2.25 and i dont want to use glibc 2.25
> 
> How can I solve this problem ?? Do you think it is a good idea to build my own RPM with wal-g 2.0.1 and glibc 2.17 from centos7 ??
> 
> Thanks

Hi! Yes, you should be able to build your own RPM without any problem :)

**Comment by MathCharton** [comment]
@usernamedt 
 I have succeeded but without "make deps" command because i have this error 
`git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
make: *** [go_deps] Error 128`

Do u have an idea ?
