### ISSUE TITLE
Asks for WALG_STREAM_CREATE_COMMAND in Postgres

### ISSUE THREAD

**Issue by Vsevosemnog** [wal-g/wal-g#1441]
postgresql runs, all good

su - postgres -c '/usr/local/bin/wal-g --config /media/.walg.json backup-push /var/lib/postgresql/14/main'
Error
```
WARNING: 2023/03/09 18:00:06.356865 PGHOST is unknown
WARNING: 2023/03/09 18:00:06.356933 PGDATA is unknown
WARNING: 2023/03/09 18:00:06.356938 We found that some variables in your config file detected as 'Unknown'. 
  If this is not right, please create issue https://github.com/wal-g/wal-g/issues/new
ERROR: 2023/03/09 18:00:06.357410 Required variable WALG_STREAM_CREATE_COMMAND is not set. You can set is using --walg-stream-create-command flag or variable WALG_STREAM_CREATE_COMMAND
```

Config:
```
{
    "WALG_S3_PREFIX": "MY s3",
    "AWS_ACCESS_KEY_ID": "My Key ID",
    "AWS_SECRET_ACCESS_KEY": "My Key",
    "WALG_COMPRESSION_METHOD": "brotli",
    "WALG_DELTA_MAX_STEPS": "5",
    "PGDATA": "/var/lib/postgresql/14/main",
    "PGHOST": "/var/run/postgresql/.s.PGSQL.5432"
}
```

**Comment by AdilkhanKTR** [comment]
I have same issue
how do you resolve it?

**Comment by Vsevosemnog** [comment]
> I have same issue how did you resolve it?

Hello
I switched to using pg_basebackup for making backups with wal-files. So i can execute Point in time recovery (PITR). 
I just don`t use wal-g

**Comment by AdilkhanKTR** [comment]
@Vsevosemnog а у pg_basebackup есть возможность класть в s3 bucket?

**Comment by usernamedt** [comment]
Hi! This error looks strange. I would double-check that you're actually running WAL-G for Postgres. What is the output of `wal-g --version`?
