### ISSUE TITLE
AWS Linux 2 - Setup with Postgres

### ISSUE THREAD

**Issue by alexwilliamsdr** [wal-g/wal-g#1443]
I'm coming from WAL-E using centos 6 servers in AWS that worked well with Postgres 9.5 

We've now moved to AWS Linux 2 servers (I believe they are Fedora based) and setup Postgres 14 on two servers and again want to do a hot standby setup using WAL-G in lieu of WAL-E to push up the segments from postgres to AWS S3 from the main instance and the hot standby pull them down and commit those WAL segments. I see no instructions anywhere for AWS Linux 2 and only binaries for Ubuntu here. I saw this as an open issue, but it's unresolved:  [ https://github.com/wal-g/wal-g/issues/1409 ] and that I tried and got the same result...it doesn't work. 

Any help would be greatly appreciated. Thanks!

**Comment by usernamedt** [comment]
Please, see the answer in[ the linked issue](https://github.com/wal-g/wal-g/issues/1274.). If you have any questions, feel free to reopen.

**Comment by alexwilliamsdr** [comment]
Thanks, I couldn't get it to work with AWS 2 Linux; I reverted back to wal-e and got that to work in about an hour.
