### ISSUE TITLE
Question: command to download sentinel file - "files_metadata.json" for analysis?  

### ISSUE THREAD

**Issue by zurikus** [wal-g/wal-g#1450]
We are using wal-g for postgresql backups and looking forward to enable verification of the page checksums during the backup-push via WALG_VERIFY_PAGE_CHECKSUMS env variable. 

Is there any wal-g command that allow to download wal-g backup's sentinel file - "files_metadata.json" for further analysis? 
So, the idea is to get this file from backup, verify it for "CorruptBlocks" records and take further actions depending on results.

**Comment by usernamedt** [comment]
Hi! As for now, the only way to do that is to use a special [storage-related wal-g commands](https://github.com/wal-g/wal-g/blob/master/docs/StorageTools.md). For example:

`wal-g st get basebackups_005/[BACKUP NAME]/files_metadata.json [LOCAL_PATH] --no-decrypt --no-decompress`

or 

`wal-g st cat basebackups_005/[BACKUP NAME]/files_metadata.json`

**Comment by zurikus** [comment]
Thank you very much for response. Commands are working as intended.
