### ISSUE TITLE
Does wal-g support HDFS API?

### ISSUE THREAD

**Issue by kishenkoilya** [wal-g/wal-g#1472]
Hello, Team!
I just wanted to know, whether wal-g support HDFS API and are there plans on that matter? I suppose i know the answer,  want to make sure.

**Comment by usernamedt** [comment]
Hi! Unfortunately, WAL-G doesn't support it atm. But you can implement it by creating a new storage in the [storages package](https://github.com/wal-g/wal-g/tree/master/pkg/storages) using HDFS go client [like this one](https://github.com/colinmarc/hdfs).
