### ISSUE TITLE
Warning: parameters "WALG_S3_MAX_RETRIES", "WALG_S3_RANGE_BATCH_ENABLED", "WALG_S3_RANGE_MAX_RETRIES" are unknown

### ISSUE THREAD

**Issue by woblerr** [wal-g/wal-g#1487]
### Database name
GP

# Issue description

### Describe your problem

According to docs, I should use parameters `WALG_S3_MAX_RETRIES`, `WALG_S3_RANGE_BATCH_ENABLED`, `WALG_S3_RANGE_MAX_RETRIES`.

When specifying these parameters, I get some warnings like `WALG_S3_MAX_RETRIES is unknown`.

When using `S3_MAX_RETRIES`, `S3_RANGE_BATCH_ENABLED`, `S3_RANGE_MAX_RETRIES`, the warning are absent.

It seems the parameters should be replaced in `CommonAllowedSettings` [config.go#L346-L348](https://github.com/wal-g/wal-g/blob/master/internal/config.go#L346-L348).

It looks like a similar problem for `WALG_S3_USE_LIST_OBJECTS_V1` [config.go#L344](https://github.com/wal-g/wal-g/blob/master/internal/config.go#L344).

### Please provide steps to reproduce
```bash
wal-g backup-push --config=/path/to/wal-g.yaml --walg-log-level=DEVEL
```

### Please add config and wal-g stdout/stderr logs for debug purpose

<details><summary>With WALG_S3_* variables</summary>
<p>

```bash
$ wal-g backup-push --config=/path/to/wal-g.yaml --walg-log-level=DEVEL
WARNING: 2023/06/07 18:39:38.445317 WALG_S3_RANGE_BATCH_ENABLED is unknown
WARNING: 2023/06/07 18:39:38.445415 WALG_S3_MAX_RETRIES is unknown
WARNING: 2023/06/07 18:39:38.445450 WALG_S3_RANGE_MAX_RETRIES is unknown
WARNING: 2023/06/07 18:39:38.445467 We found that some variables in your config file detected as 'Unknown'. 
  If this is not right, please create issue https://github.com/wal-g/wal-g/issues/new
DEBUG: 2023/06/07 18:39:38.446587 --- COMPILED ENVIRONMENT VARS ---
	...
	WALG_S3_MAX_RETRIES=6
	WALG_S3_RANGE_BATCH_ENABLED=true
	WALG_S3_RANGE_MAX_RETRIES=4
	WALG_SERIALIZER_TYPE=json_default
	WALG_SKIP_REDUNDANT_TARS=false
	...
WARNING: 2023/06/07 18:39:38.795593 GetSystemIdentifier: Unable to get system identifier
INFO: 2023/06/07 18:39:38.818579 Greenplum version: PostgreSQL 9.4.26 (Greenplum Database 6.23.3 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Apr 12 2023 04:43:43
INFO: 2023/06/07 18:39:38.868695 Checking backup prerequisites
...
```
</p>
</details>

<details><summary>With S3_* variables</summary>
<p>

```bash
$ wal-g backup-push --config=/path/to/wal-g.yaml --walg-log-level=DEVEL
DEBUG: 2023/06/07 18:43:04.339502 --- COMPILED ENVIRONMENT VARS ---
    ...
	PGUSER=gpadmin
	S3_MAX_RETRIES=6
	S3_RANGE_BATCH_ENABLED=true
	S3_RANGE_MAX_RETRIES=4
	TOTAL_BG_UPLOADED_LIMIT=32
	...
WARNING: 2023/06/07 18:43:04.718651 GetSystemIdentifier: Unable to get system identifier
INFO: 2023/06/07 18:43:04.740180 Greenplum version: PostgreSQL 9.4.26 (Greenplum Database 6.23.3 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Apr 12 2023 04:43:43
INFO: 2023/06/07 18:43:04.786743 Checking backup prerequisites
...
```
</p>
</details>

**Comment by anikin-aa** [comment]
Hi,

Yes, can confirm that facing same issue for PostgreSQL, and I think that this problem affects all the databases.

After adding `WALG_` prefix to https://github.com/wal-g/wal-g/blob/master/internal/config.go#L346-L348 variables warning from the logs is gone and it's possible to change values via both `S3_MAX_RETRIES` and `WALG_S3_MAX_RETRIES`.

I can open PR if this is really an issue or just not correct documentation info.

**Comment by usernamedt** [comment]
> Hi,
> 
> Yes, can confirm that facing same issue for PostgreSQL, and I think that this problem affects all the databases.
> 
> After adding `WALG_` prefix to https://github.com/wal-g/wal-g/blob/master/internal/config.go#L346-L348 variables warning from the logs is gone and it's possible to change values via both `S3_MAX_RETRIES` and `WALG_S3_MAX_RETRIES`.
> 
> I can open PR if this is really an issue or just not correct documentation info.

Hi! Yes, that would be great to make these changes. Thank you!
