### ISSUE TITLE
pause wal-g (no-backup)

### ISSUE THREAD

**Issue by WeSTManCoder** [wal-g/wal-g#1491]
### Database name
greenplum

# Issue description
wal-g command:
wal-g backup-push --config=/home/gpadmin/wal-g.json

### Describe your problem
run wal-g command:
wal-g backup-push --config=/home/gpadmin/wal-g.json
but this command pause on:

INFO: 2023/06/14 09:48:13.802070 Initializing tmp connection to read Greenplum info
WARNING: 2023/06/14 09:48:13.847268 GetSystemIdentifier: Unable to get system identifier
INFO: 2023/06/14 09:48:13.849182 Greenplum version: PostgreSQL 9.4.26 (Greenplum Database 6.24.4 build commit:d1b94743b5e665888e0a72c921daf04bdbe77528 Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jun  7 2023 19:40:28
INFO: 2023/06/14 09:48:13.852177 Connecting to Greenplum master.
INFO: 2023/06/14 09:48:13.891252 Checking backup prerequisites
INFO: 2023/06/14 09:48:13.891285 Checking for the existing running backup...
WARNING: 2023/06/14 09:48:13.898978 GetSystemIdentifier: Unable to get system identifier

config
{
   "PGHOST": "localhost",
   "PGDATABASE": "postgres",
   "PGUSER": "gpadmin",
   "PGDATA": "/usr/local/greenplum-db/data/master/seg-1",
   "WALG_UPLOAD_CONCURRENCY": "2",
   "WALG_DOWNLOAD_CONCURRENCY": "2",
   "WALG_UPLOAD_DISK_CONCURRENCY": "2",
   "WALG_DELTA_MAX_STEPS": "7",
   "WALG_COMPRESSION_METHOD": "brotli",
   "WALG_GP_LOGS_DIR": "/var/log/greenplum",
   "WALG_FILE_PREFIX":"/mnt/backup",
   "WALG_LOG_LEVEL": "DEVEL"
}

**Comment by WeSTManCoder** [comment]
Backup prerequisites check failed: ERROR: interconnect encountered a network error, please check your network  (seg1 slice1 192.168.44.143:6001 pid=87150) (SQLSTATE 58M01)

but telnet is access on port
[root@localhost gpadmin]# telnet 192.168.44.143 6001
Trying 192.168.44.143...
Connected to 192.168.44.143.
Escape character is '^]'.

**Comment by WeSTManCoder** [comment]
Greenplum wrong settings. Thanks

**Comment by usernamedt** [comment]
> Greenplum wrong settings. Thanks

Thanks for your report! It would be great to share which settings resulted in such behavior.
