### ISSUE TITLE
Support alternative S3 implementations

### ISSUE THREAD

**Issue by bithavoc** [wal-g/wal-g#15]
Additionally, in order to support other non-official S3 implementations such as https://minio.io/ we would need to be able to setup a few custom settings:

```
Endpoint:         aws.String(os.Getenv("AWS_ENDPOINT")),
S3ForcePathStyle: aws.Bool(os.Getenv("AWS_S3_FORCE_PATH_STYLE") == "true"),
```

Example:
```
WALE_S3_PREFIX: s3://backups/wal-g
AWS_ENDPOINT: http://minio:9000
```

`S3ForcePathStyle` is required so the aws go sdk doesn't try to call `http://backups.s3.amazonaws.com/wal-g` and instead reach the minio server using sub path resources as in `http://minio:9000/backups/wal-g`.

Source https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-go-with-minio.md

**Comment by fdr** [comment]
Closing in favor of PR.
