### ISSUE TITLE
Plans for a new release

### ISSUE THREAD

**Issue by zamazan4ik** [wal-g/wal-g#1522]
Hi!

Are there plans for making a new release? The latest release (if we don't count a Release Candidate) was almost a year ago. I think during the last year there were enough changes for making a new release/tag. In this case, will be easier to update versions for the maintainers and end-users.

Thanks in advance!

**Comment by x4m** [comment]
+1

**Comment by alexmv** [comment]
Just bumping this -- it'd be great to see a numbered release!

**Comment by jirizaloudek** [comment]
+1 we are waiting for a new version to mitigate some CVEs

**Comment by thomas315** [comment]
+1

**Comment by gabrielmocan** [comment]
+1

**Comment by OlleLarsson** [comment]
Yes, please give us an update on the status of this project.

**Comment by x4m** [comment]
@usernamedt let's cut a release? Do we have open items? failover storage seems stable enough...

**Comment by gabrielmocan** [comment]
storage failover is a very anticipated feature 😎

**Comment by siepkes** [comment]
Since it there hasn't been a release for a while, does this mean most people are simply running the latest commit? Or are people running `2.0.1`?

**Comment by x4m** [comment]
We will have release soon. Some days, maybe a week. Just need a little more time to ensure reachable level of absance of known bugs.

At Y.Cloud we run on master branch, but that's not what I would recommend to anyone. Backup system must be bulletproof, you can experiment with it only with good monitoring and on-call SRE ready to cope with new features.

**Comment by gabrielmocan** [comment]
@x4m great to hear, looking forward for this very anticipated release 😎

**Comment by x4m** [comment]
Here we go
https://github.com/wal-g/wal-g/releases/tag/v3.0.0

**Comment by gabrielmocan** [comment]
@x4m gratitude is the only expression I can say. Congratulations to everyone involved in this effort.
