### ISSUE TITLE
Does it support backup to GCS?

### ISSUE THREAD

**Issue by carolfly86** [wal-g/wal-g#155]
WAL-E supports backup to GCS, does WAL-G supports GCS as well?

**Comment by x4m** [comment]
Hi @carolfly86 !
Yes, most probably we will support GCP. I cannot give you a proper ETA. But to give you some idea when GCP will be supported by WAL-G I'll describe what is between WAL-G and GCP.
1. Separate storage logic from code. Most hard technical part. Is done here #146
2. Implement GCP interaction: read configs as in WAL-E and implement one interface StrageFolder. This seems quite easy, I hope it will be there soon.
3. Cut pre-release. This is the point where you can start playing with WAL-G+GCP. Probably, there will be bugs at this point.
4. Wait for release. This will definitely take time. On average we do release one per 3 months. And chances are that this time it will be even not a year 2018.
3. Add GCP test logic to integration tests. We need some docker GCP container to put WALs and backups on every commit. This will ensure that future prereleases will not break GCP interaction.

Hope this will give you some insight when you can start using GCP with WAL-G.

**Comment by carolfly86** [comment]
Thanks @x4m for your reply! 
Should I expect official GCP support in the next release possibly 2-3 months from now?

**Comment by x4m** [comment]
Most probably yes.
Moreover, you can change it do "definitely yes" by sending PR on point 2. We'll be happy to review it.

**Comment by x4m** [comment]
done, plz test it

**Comment by carolfly86** [comment]
Thank you very much! will test it today and let you know

**Comment by carolfly86** [comment]
I tested backup-push on a 711GB database instance. With the latest pre-release version to GCS it took 3hr 51 mins, but with the previous 0.1.15 version to S3 it only took around 70 mins. Is it expected to have such significant performance difference?
In both tests, I only set the credential and storage prefix, all other params are just default values.

**Comment by x4m** [comment]
Thanks for testing!

Currently, I have only one hypothesis: in S3 we use multipart uploads, they are uploaded in parallel.
Looks like GCS does not have this (but I'm not a GCP expert!)
I've found this https://godoc.org/google.golang.org/api/option#WithGRPCConnectionPool , but looks like it's not what we want.
Here https://cloud.google.com/storage/docs/composite-objects#_Uploads they recommend doing parallel uploads by hand: uploading many objects, then composing it. Not an easy-breathy, but quite possible.
Finally, you can do WALG_UPLOAD_DISK_CONCURRENCY. It will create separate uploader for every 1Gb of data. But there are two dangerous things:
1. If the network connection is slower than disk (and unparalleled connection will be, for sure), there will be a buffer of up to 1Gb between disk reader and net uploader (actually there will be consumption about 400Mb). This buffer will eat RAM, not a good thing for db. I'd recommend trying 3-6 readers.
2. If the network becomes really good parallel disk read will use all available disk bandwidth. When you have only 1 disk reader (default) you do not actually compete with DB for disk. But many readers will saturate nvme controller. E.g. 25Gb network with S3 will saturate software raid of 4 disks.

Also, you can use brotli compression to reduce time of network-constained backup. But this has nothing to do with S3 vs GCP storage folder development.

**Comment by carolfly86** [comment]
Thanks for your investigation! I'll try  WALG_UPLOAD_DISK_CONCURRENCY.

**Comment by carolfly86** [comment]
@x4m I tried set WALG_UPLOAD_DISK_CONCURRENCY to 5, now it finished around 30mins. the performance seems to be ok, thanks for checking!

**Comment by x4m** [comment]
Cool! So, I'll close the issue until some other GCP users will find out that there is no multipart uploads and will venture a PR :)
BTW, do you observe acceptable memory consumption?
Also, if you will find out that WAL-G consumes too much of disk bandwidth you can use WALG_DISK_RATE_LIMIT (bytes per second).

**Comment by carolfly86** [comment]
memory consumption is fine. Disk i/o was 2-3 times of the wal-e backup, but the duration is also much less then half of wal-e. I guess this may be fine since we are backing up from a read replica. Will definitely try WALG_DISK_RATE_LIMIT if needed. thanks again for your work!
