### ISSUE TITLE
simple FileSystem backup System?

### ISSUE THREAD

**Issue by gannebamm** [wal-g/wal-g#156]
Hello
I would like to create a continous replication system from a corporate LAN to a on premise hosted network on the WWW. The LAN has read and write permission to our WWW network, but WWW is not allowed to read or write to our LAN. Could this kind of 'mirroring' be achieved with wal-g / wal-e? I am not shure about that. What about the filesystem backup, which was in wal-e, is it allready in wal-g or are there plans to implement it?

**Comment by x4m** [comment]
Hi @gannebamm !
Thanks for your question. Please read the answer in #155 with s/GCP/FileSystem/g
And remove point about docker image, we do not need docker image to backup on FS.
Besides what is there, I can add that yeah, backup on file systems is a feature that we want. Chances are that we will do it soon. If you have some spare time I'll happily review a PR.
Thanks!

**Comment by x4m** [comment]
done
