### ISSUE TITLE
wal-push .history file and error S3: ObjectNotFound

### ISSUE THREAD

**Issue by godzilla-s** [wal-g/wal-g#1580]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Issue description

### Describe your problem
When I use the wal-g tool to package a backup of the .history file in the wal directory of the postgresql database, it reports an error:
```
Couldn't check whether there is an overwrite attempt due to inner error: failed to read object: 'wal_005/00000002.history.lz4' from S3. ObjectNotFound: object not found
```
I found something wrong relative with description in the code as follows:
```
// TODO : unit tests
func checkWALOverwrite(uploader *WalUploader, walFilePath string) (overwriteAttempt bool, err error) {
	walFileReader, err := internal.DownloadAndDecompressStorageFile(internal.NewFolderReader(uploader.Folder()), filepath.Base(walFilePath))
	if err != nil {
		tracelog.ErrorLogger.Println("download storage file fail: error:", err)
		if _, ok := err.(internal.ArchiveNonExistenceError); ok {
			err = nil
		}
		return false, err
	}

	archived, err := io.ReadAll(walFileReader)
	if err != nil {
		return false, err
	}
      ....
```
 the error handling here is not a bit of a problem, if the error returned by S3 is ObjectNotFound this kind of situation, and did not do processing. So it world add some error check as below:
```
      if err != nil {
		tracelog.ErrorLogger.Println("download storage file fail: error:", err)
		if _, ok := err.(internal.ArchiveNonExistenceError); ok {
			err = nil
		}
                // todo error with S3: ObjectNotFound like:
               if  strings.Contain(err.Error(), "ObjectNotFound") {
                        err = nil
               }
		return false, err
	}
```

### Please provide steps to reproduce
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

**Comment by x4m** [comment]
Uhm, thanks for spotting this problem. The code is far from perfect.
1.
> tracelog.ErrorLogger.Println("download storage file fail: error:", err)
This logging is superflous, it is expected behaviour that file is absent. Why print this as an error?

2. We had implicit contract that download should return ArchiveNonExistenceError. This contract is broken. We should not mask this with checking error message, but instead find why where where it was broken.

**Comment by x4m** [comment]
Anyway, PR fixing this would be greatly appreciated. It's definitely a bug. I suspect this reproduces when object is not compressed or is not encrypted.

**Comment by godzilla-s** [comment]
> 2\. We had implicit contract that download should return ArchiveNonExistenceError. This contract is broken. We should not mask this with checking error message, but instead find why, when and where it was broken.

you're welcome, I'm just pointing out the problem in code， Looking forward to your updates

**Comment by x4m** [comment]
I've created PR with potential fix. Can you please try if this helps?

**Comment by x4m** [comment]
uhhm...nope, sorry, that does not fix anything. I have to dig deeper...

**Comment by x4m** [comment]
What storage do you use? It seems to me you get non-standard response code. And it is not parsed correctly here.
https://github.com/wal-g/wal-g/blob/2e0d92cfb06acbf3f19ce8963ebe1085479083d6/pkg/storages/s3/folder.go#L390

**Comment by godzilla-s** [comment]
> What storage do you use? It seems to me you get non-standard response code. And it is not parsed correctly here.
> 
> https://github.com/wal-g/wal-g/blob/2e0d92cfb06acbf3f19ce8963ebe1085479083d6/pkg/storages/s3/folder.go#L390

I use MinIO as storage

**Comment by godzilla-s** [comment]
> isAwsNotExist

sorry, I found it' my fault, I use MinIO as Storage but I found that our internal middleware does a layer of encapsulation of the standard S3 interface，some error has been wrapper by internal handle.  

I'm confirming this.

thank you for your reply so much

**Comment by godzilla-s** [comment]
sorry again， it's my fault， error has been replace by internal middleware, we fixed it ,  thank you again

**Comment by x4m** [comment]
No problem, thanks for keeping an eye on possible bugs. Together we make reliable systems :)
