### ISSUE TITLE
Greenplum, Couldn't get current timeline because of error: 'ERROR: function pg_control_checkpoint() does not exist (SQLSTATE 42883)'

### ISSUE THREAD

**Issue by nowost** [wal-g/wal-g#1616]
greenplum database  got error

INFO: 2024/01/11 06:48:59.010354 Calling pg_start_backup()
WARNING: 2024/01/11 06:48:59.749748 Couldn't get current timeline because of error: 'ERROR: function pg_control_checkpoint() does not exist (SQLSTATE 42883)'

**Comment by usernamedt** [comment]
Hi! It is a warning from common Postgres/Greenplum code that indicates that WAL-G could not read pg_control data by querying the `pg_control_checkpoint()` function. It is reasonable since this function does not exist in Greenplum 6X. This warning can be safely ignored in GP 6X.
