### ISSUE TITLE
base_*_backup_stop_sentinel.json much smaller with Postgresql 16 than 14

### ISSUE THREAD

**Issue by airblade** [wal-g/wal-g#1619]
### Database name
Postgresql 16

# Issue description

### Describe your problem
I recently moved my data to a new server.  The previous database was Postgresql 14; the new one is Postgresql 16.

Before the move the sentinel files were 235.0 KB (see screenshot from my S3 bucket).  After the move they are 375.0 B.

Is that expected?

<img width="827" alt="Screenshot 2024-01-12 at 2 57 34 pm" src="https://github.com/wal-g/wal-g/assets/7265/27f9acb1-90ee-4958-9bac-2fd8416d150c">

**Comment by x4m** [comment]
Hi! AFAIK newer version of WAL-G store heavy data in separate metadata inside the backup.
Sentinel object is here to be a sign of finished backup. It has minimum of information which can be of use to end user during backup listing. Metadata on a contrary contains information on each file in the backup.

**Comment by x4m** [comment]
But this is not expected if you use same WAL-G version

**Comment by airblade** [comment]
@x4m Thanks!  When I changed server, as well as Postgresql changing versions, my WAL-G changed from 1.1 to 2.0.1 – I should have mentioned that, sorry.
