### ISSUE TITLE
"go get" Build instructions in README are no longer correct

### ISSUE THREAD

**Issue by colincoghill** [wal-g/wal-g#1632]
### Database name
any

# Issue description

Ubuntu Build instructions in README are wrong for recent versions of go.

### Describe your problem
The README mentions that to build wal-g under Ubuntu,
```go get github.com/wal-g/wal-g```

I believe go changed the way this works a few versions ago and now gives:
```
% go get github.com/wal-g/wal-g
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

```
(This was with go 1.21.5 on darwin and Linux but I'd expect similar from others)

I got it working by `git clone`ing the repo and building it that way, but trying to follow the instructions in the README had me lost for a little while.

I'm not sure what the correct command would be, `go install` didn't work (for me) either, I'm not familiar with go.

### Please provide steps to reproduce
Start with a reasonably clean Ubuntu or MacOSX install and follow the build instructions in README.md

```
# Install latest Go compiler
sudo add-apt-repository ppa:longsleep/golang-backports 
sudo apt update
sudo apt install golang-go

# Install lib dependencies
sudo apt install libbrotli-dev liblzo2-dev libsodium-dev curl cmake

# Fetch project and build
go get github.com/wal-g/wal-g
```
^ error happens here

### Please add config and wal-g stdout/stderr logs for debug purpose

n/a

**Comment by x4m** [comment]
Hi Colin!
Thank you for taking the time to make WAL-G better.
I agree that our documentation leaves much to be desired.
May I ask you to do a pull request with fixes?
