### ISSUE TITLE
problem with using wal-push archive_command to GCS 

### ISSUE THREAD

**Issue by carolfly86** [wal-g/wal-g#166]
Hi, 
I'm trying to use wal-push as archive_command to archive to GCS. `/usr/bin/envdir /etc/wal-g.d/env /opt/wal-g/bin/wal-g wal-push %p`  the command runs fine (exit code 0) when I ran it manually as postgres user , but in postgres log it still complains the `archive command failed with exit code 141.` 
We used strace to trace the process and found that it seems to choke on stdout `write(1, "Path:  pitr-wale-v1/\n", 21) = -1 EPIPE (Broken pipe)` . 
So we redirected stdout/stderr to a log file `/usr/bin/envdir /etc/wal-g.d/env /opt/wal-g/bin/wal-g wal-push %p &>/tmp/walg.log`  this seems to work fine.  Is this expected behavior?

**Comment by carolfly86** [comment]
This issue may not be related to wal-g. This archive command only fails on the patroni cluster but runs fine on postgres instances. It's more likely to be related to patroni https://github.com/zalando/patroni/blob/master/patroni/postmaster.py#L163
While wal-g runs fine with patroni because it uses syslog instead of stdout.

**Comment by x4m** [comment]
>While wal-g runs fine with patroni because it uses syslog instead of stdout.
it's wal-e, right?

We use unified logging subsystem, it is not very difficult to add syslog as log destination...

**Comment by x4m** [comment]
@Tinsane let's add this task for students? ```Allow redirecting log to syslog```
Unfortunately, this task can be completed only by those students who mastered Linux VM instantiation.

**Comment by carolfly86** [comment]
> While wal-g runs fine with patroni because it uses syslog instead of stdout.

sorry, my mistake, I meant wal-e runs fine because it uses syslog
