### ISSUE TITLE
Questions about 3.0 release

### ISSUE THREAD

**Issue by OrangeDog** [wal-g/wal-g#1667]
I tried [asking on Slack](https://postgresteam.slack.com/archives/CA25P48P2/p1710757509766579), but the channel is dead, and I don't have Telegram.

How exactly does the new failover storage work?
Does it automatically sync the failover back to the primary storage once it comes back, or does that need to be set up externally?
Do you get warnings (or higher) logged when it's failing-over, or is it silent?
Can you set a limit for the amount of failover to use before it returns to the previous behaviour, making the DB retry until it's working again?

Also, I assume due to no mention in the release notes, that there's no breaking changes and you can just upgrade without changing anything?

**Comment by x4m** [comment]
@rdjjke can you please answer some questions about the feature that you implemented?
And maybe let's consider adding these answers to documentation.

**Comment by OrangeDog** [comment]
Can someone at least confirm that the upgrade path is just "install the new version"?

**Comment by x4m** [comment]
```wal-push``` and ```wal-fetch``` are forward and backward compatible across all 0.1.4+ versions.
Backups are backward-compatible: wal-g 3.0.0 can restore any backup made by any release of wal-g since 0.1.4 and some releases of pgbackrest.
Sorry for our docs, I hope we will improve it.

**Comment by x4m** [comment]
There are some issues with ```backup-list --json --details``` when reading backup metadata of older versions.

**Comment by jorsol** [comment]
Hi @x4m, what kind of issues with `backup-list --json --details`?

**Comment by psyd01986** [comment]
we also have problems with version 3.0.0-3.0.1.
running the command in version 3:
 wal-g backup-list --pretty --json --detail on storage with backups made by version 2.0.1 hangs for an unreasonably long time.
If you run this command in version 2, the response is almost instantaneous.
What information should be provided to help solve this problem?

**Comment by x4m** [comment]
@psyd01986 there's known issue in 3.0.1 #1736 but it is not expected to reproduce in 3.0.0
are you sure you observe it in 3.0.0?

**Comment by x4m** [comment]
> Hi @x4m, what kind of issues with `backup-list --json --details`?

--details flag reads metadata which was absent in old versions (before 2.0.0, or, perhaps, earlier)

**Comment by psyd01986** [comment]
> @psyd01986 в 3.0.1 есть известная проблема [# 1736](https://github.com/wal-g/wal-g/issues/1736), но ожидается, что она не будет воспроизведена в 3.0.0 вы уверены, что заметили ее в 3.0.0?

I double-checked, the problem was observed in version 3.0.1, version 3.0.0 was not used.
I apologize for the confusion.
Today I checked version 3.0.0

**Comment by psyd01986** [comment]
tested, confirm, in version 3.0.0 and version 3.0.2
command wal-g backup-list --pretty --json --detail
works quickly.
Thanks to all.
