### ISSUE TITLE
Support backups located in the root of a bucket

### ISSUE THREAD

**Issue by jonjomckay** [wal-g/wal-g#17]
It looks like backups are expected to be located in subfolders inside an S3 bucket, but our WAL-E backups are located in the root - it'd be great if this were supported too! Currently, a lot of `panic: runtime error: index out of range` messages are thrown when trying to hack around this by changing the locations in the configuration.

**Comment by fdr** [comment]
I'd take a patch unless it is really, really ugly for some reason.

**Comment by jonjomckay** [comment]
@fdr I attempted to try and build this locally to patch it myself, but I found the whole Go build chain pretty confusing... any tips? I think this should be quite a small change - checking the length of the array/slice before operating on it :)

**Comment by fdr** [comment]
Did you set up $GOPATH? Did you see https://github.com/wal-g/wal-g#development?

**Comment by x4m** [comment]
I think PR #33 will fix this. @jonjomckay , can you please check your scenario against that pull request?

**Comment by x4m** [comment]
Fixed.
