### ISSUE TITLE
"Invalid page header" warnings during backup-push

### ISSUE THREAD

**Issue by vstax** [wal-g/wal-g#171]
Hello, I'm trying out wal-g on barely loaded database and sometimes getting warnings like this (here `wal-g backup-push /var/lib/pgsql/11/data` was started at 2:02 AM:
```
Path:  
INFO: 2019/01/25 02:02:01.649327 Delta backup from base_000000010000005900000010_D_00000001000000590000000C with LSN 5910000028. 
INFO: 2019/01/25 02:02:01.780709 Walking ...
INFO: 2019/01/25 02:02:01.780992 Starting part 1 ...
WARNING: 2019/01/25 02:02:27.105408 Invalid page  0  page header  &{0 0 30859 0 64 8176 8176 8196}
WARNING: 2019/01/25 02:02:27.105722 failed to read file '/base/27057/880656' as incremented
WARNING: 2019/01/25 02:02:27.109879 Invalid page  0  page header  &{0 0 30859 0 64 8176 8176 8196}
WARNING: 2019/01/25 02:02:27.109894 failed to read file '/base/27057/880660' as incremented
INFO: 2019/01/25 02:02:27.480395 Finished writing part 1.
INFO: 2019/01/25 02:02:27.864803 Starting part 2 ...
INFO: 2019/01/25 02:02:27.864846 /global/pg_control
INFO: 2019/01/25 02:02:27.869397 Finished writing part 2.
INFO: 2019/01/25 02:02:28.901469 Starting part 3 ...
INFO: 2019/01/25 02:02:28.901515 backup_label
INFO: 2019/01/25 02:02:28.901523 tablespace_map
INFO: 2019/01/25 02:02:28.904414 Finished writing part 3.
INFO: 2019/01/25 02:02:29.078008 Uploaded 3 compressed tar Files.
```

Wal-g 0.2.4, postgresql 11.1 running on EL 7.6, settings are
```
WALG_UPLOAD_CONCURRENCY=4
WALG_DELTA_MAX_STEPS=6
WALG_COMPRESSION_METHOD=brotli
```
Backup is done from local connection (PGHOST=/var/run/postgresql). Nothing unusual in postgresql.conf.

postgresql log file shows that 3 WAL files were pushed at the same time:
```
Path:  
INFO: 2019/01/25 02:02:03.088336 FILE PATH: 000000010000005900000033.br
Path:  
INFO: 2019/01/25 02:02:28.821981 FILE PATH: 000000010000005900000034.00000028.backup.br
INFO: 2019/01/25 02:02:28.866876 FILE PATH: 000000010000005900000034.br
```

What does it mean?

**Comment by x4m** [comment]
Hi!

When you are making delta backup WAL-G reads data pages to find what changed. To understand that page changed we read LSN from the page header. But before reading LSN we check some invariants to verify that page header looks sane.
If the page header does not look like usual page header https://github.com/wal-g/wal-g/blob/master/internal/postgres_page_header.go#L23-L31 we consider a page in an unknown state. And, being a little paranoid, copy not just this page, but a whole file.
This is just a precaution measure. We were observing such pages even on fresh inited cluster under several hours of pgbench.

So, I believe there is nothing to worry about.

Your page contains 0 LSN, that's what triggered precautions of WAL-G. This is not a sign of data corruption, but just in case you can verify checksums with pg_verify checksums (if checksums are enabled on your cluster) or do amcheck if relation 880656 is index.

**Comment by vstax** [comment]
Thanks for the explanation. Relations 880656 and 880660 are indexes from the same table; amcheck doesn't show any problems. Cannot do pg_verify because it requires to stop the database :) but nothing seems to be wrong.
This might be related or not, but the table and both these indexes are "unlogged". Well it should only affect the WAL, not the table on disk itself, I think...

Anyhow, feel free to close the issue if it's not a problem, but maybe this information (that such warning during delta backup is harmless) should be in documentation?
