### ISSUE TITLE
Question: how to reduce number of full backup ?

### ISSUE THREAD

**Issue by garry-t** [wal-g/wal-g#1721]
Problem that if i specified for delete backup command like this 
`wal-g delete retain FULL 2 --confirm` I see in s3 storage always 5 full backup. to reduce costs it would be nice reduce full backup amounts to 2. 

Or I made some misconfigurations ? 

my config

```
cat /var/lib/postgresql/.walg.json 
{
  "AWS_ACCESS_KEY_ID": "XX",
  "AWS_SECRET_ACCESS_KEY": "XX",
  "WALG_S3_PREFIX": "s3://backup",
  "AWS_REGION": "eu-central-1",
  "WALG_COMPRESSION_METHOD": "brotli",
  "WALG_DELTA_MAX_STEPS": "1",
  "WALG_S3_STORAGE_CLASS": "STANDARD",
  "PGDATA": "/var/lib/postgresql/15/main",
  "PGHOST": "/var/run/postgresql",
  "PGPORT": "5432",
  "PGUSER": "postgres"
}
```
`wal-g wal-show ` shows backup count 5. I want to see 2 here :) 

Thanks

**Comment by OrangeDog** [comment]
Have you checked whether that key has permission to delete?
What is the output from the delete command?

**Comment by garry-t** [comment]
Ok, I removed delta backups from config, since it was set to 3. So anyway now I see correct number in storage. Problem in user side. closing.
