### ISSUE TITLE
miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [wal-g/wal-g#1722]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Issue description

### Describe your problem

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242986885/job/25426524275 

```
====================================================================================================
append to slice `errMsgs` with non-zero initialized length at https://github.com/wal-g/wal-g/blob/master/internal/multistorage/storage.go#L114:13
====================================================================================================
```

the `errMsgs := make([]string, len(ce.specificStorageErrs))` should be `errMsgs := make([]string, 0, len(ce.specificStorageErrs))`

### Please provide steps to reproduce
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

**Comment by ostinru** [comment]
https://github.com/wal-g/wal-g/blob/master/internal/multistorage/storage.go#L114:13

```
func (ce *CloseError) Error() string {
	errMsgs := make([]string, len(ce.specificStorageErrs))
	for _, e := range ce.specificStorageErrs {
		errMsgs = append(errMsgs, e.Error())
	}
	return fmt.Sprintf("failed to close storage(s) and release resources: %s", strings.Join(errMsgs, ", "))
}
```

Issue is following:
```
a := make([]int, 5)
> a len=5 cap=5 [0 0 0 0 0]

b := make([]int, 0, 5)
> b len=0 cap=5 []
```

**Comment by ostinru** [comment]
`makezero` is supported by golang-ci, so we can add it our linters.
Also, there is similar linter `prealloc` linter (however authors notes that it is rarely impreove performance).

PS: also I'd like to add `asciicheck` linter.
