### ISSUE TITLE
Unable to build wal-g libsodium donwload issue

### ISSUE THREAD

**Issue by garry-t** [wal-g/wal-g#1738]
### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Issue description
Unable to build wal-g 
### Describe your problem
Cant figure out what is the problem everything worked fine, but today started fails 

### Please provide steps to reproduce
Run `make USE_BROTLI=1 USE_LIBSODIUM=1 deps`

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

```

[ 96%] Linking C static library libbrotlienc-static.a
make[3]: Leaving directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
[ 96%] Built target brotlienc-static
make[3]: Entering directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Leaving directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
[ 98%] Building C object CMakeFiles/brotli.dir/c/tools/brotli.c.o
[100%] Linking C executable brotli
make[3]: Leaving directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
[100%] Built target brotli
make[2]: Leaving directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'
make[1]: Leaving directory '/tmp/wal-g/vendor/github.com/google/brotli/dist'

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [Makefile:296: link_libsodium] Error 2
```

**Comment by garry-t** [comment]
I found the reason. Here `link_libsodium.sh` changed format of link to downloads. 
Old `curl --retry 5 --retry-delay 0 -L https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VERSION/libsodium-$LIBSODIUM_VERSION.tar.gz -o libsodium-$LIBSODIUM_VERSION.tar.gz`

Now 
`curl --retry 5 --retry-delay 0 -L https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VERSION-RELEASE/libsodium-$LIBSODIUM_VERSION.tar.gz -o libsodium-$LIBSODIUM_VERSION.tar.gz`

**Comment by garry-t** [comment]
https://github.com/wal-g/wal-g/pull/1739

**Comment by PKizzle** [comment]
I have opened a discussion over at libsodium why that particular version (1.0.17) has been removed from the releases: https://github.com/jedisct1/libsodium/discussions/1386

**Comment by ostinru** [comment]
PR #1739 merged. Issue should be fixed.

PS: there were #1740, however it was created a moment later.
