### ISSUE TITLE
WAL-G compiled on OEL 7.9 cannot fetch backup was made on Ubuntu 22.04

### ISSUE THREAD

**Issue by opopovich** [wal-g/wal-g#1761]
**### Database name**

Postgres 16

**# Issue description**

WAL-G compiled on OEL 7.9 cannot fetch backup was made on Ubuntu 22.04

**### Describe your problem**

We try to fetch Postgres backup was made by wal-g on Ubuntu 22.04 using wal-g compiled on OEL 7.9. Brotli version is 1 .0.9
wal-g can't open archive tar.br

**### Please provide steps to reproduce**

1.Compile wal-g with lzo and brotli support on OEL 7.9
2. Try to fetch backups which was made on Ubuntu 22.04

**### Please add config and wal-g stdout/stderr logs for debug purpose**

My config:

{
  "WALE_S3_PREFIX": "s3://",
  "AWS_ACCESS_KEY_ID": "my_key_id",
  "AWS_ENDPOINT": "http://192.168.1.10:9000",
  "AWS_S3_FORCE_PATH_STYLE": "true",
  "AWS_SECRET_ACCESS_KEY": "my_key",
  "PGDATA": "/var/lib/pgsql/9.6/data/",
  "PGHOST": "/var/run/postgresql/.s.PGSQL.5432",
  "WALG_UPLOAD_CONCURRENCY": "2",
  "WALG_DOWNLOAD_CONCURRENCY": "2",
  "WALG_UPLOAD_DISK_CONCURRENCY": "2",
  "WALG_DELTA_MAX_STEPS": "7",
  "WALG_COMPRESSION_METHOD": "brotli"
}

**WAL_G output:**

wal-g backup-fetch /test LATEST
INFO: 2024/07/29 19:12:33.612533 Selecting the latest backup...
INFO: 2024/07/29 19:12:33.613348 Backup to fetch will be searched in storages: [default]
INFO: 2024/07/29 19:12:33.627244 LATEST backup is: 'base_0000000200000213000000EA'
INFO: 2024/07/29 19:12:33.963934 Finished extraction of part_002.tar.br
ERROR: 2024/07/29 19:12:33.963958 Extraction error in part_002.tar.br: extractOne: tar extract failed: cbrotli: CL_SPACE
INFO: 2024/07/29 19:12:33.975428 Finished extraction of part_001.tar.br
ERROR: 2024/07/29 19:12:33.975451 Extraction error in part_001.tar.br: extractOne: tar extract failed: cbrotli: CL_SPACE
INFO: 2024/07/29 19:12:34.007944 Finished extraction of part_003.tar.br
ERROR: 2024/07/29 19:12:34.007965 Extraction error in part_003.tar.br: extractOne: tar extract failed: cbrotli: RESERVED
INFO: 2024/07/29 19:12:34.018619 Finished extraction of part_004.tar.br
ERROR: 2024/07/29 19:12:34.018640 Extraction error in part_004.tar.br: extractOne: tar extract failed: cbrotli: PADDING_2
INFO: 2024/07/29 19:12:34.058847 Finished extraction of part_005.tar.br
ERROR: 2024/07/29 19:12:34.058869 Extraction error in part_005.tar.br: extractOne: tar extract failed: cbrotli: CL_SPACE
INFO: 2024/07/29 19:12:34.070949 Finished extraction of part_006.tar.br
ERROR: 2024/07/29 19:12:34.070971 Extraction error in part_006.tar.br: extractOne: tar extract failed: cbrotli: CL_SPACE
INFO: 2024/07/29 19:12:34.114107 Finished extraction of part_007.tar.br
INFO: 2024/07/29 19:12:34.114135 Finished extraction of part_008.tar.br
ERROR: 2024/07/29 19:12:34.114134 Extraction error in part_007.tar.br: extractOne: tar extract failed: cbrotli: PADDING_2
ERROR: 2024/07/29 19:12:34.114176 Extraction error in part_008.tar.br: extractOne: tar extract failed: cbrotli: HUFFMAN_SPACE
INFO: 2024/07/29 19:12:34.169949 Finished extraction of part_009.tar.br

**Comment by x4m** [comment]
Hi! Thanks for the report! Do you observe same problem with lz4 too?

**Comment by opopovich** [comment]
Hello @x4m! Untfortunatelly we can't test lz4 and lzma because we have only read right on S3 and no right on wal-g.
System on which backups are made is closed from us.
Can you suggest maybe we can determine root cause of problem and bypass it? Maybe some test?

**Comment by x4m** [comment]
can you fetch backup to Ubuntu? If it works, the problem is around brotli cross-compatibility

**Comment by opopovich** [comment]
Hello @x4m 
Thanks for answer!
We install Ubuntu 22.04 and download newest 3.0.2 and 3.0.0 version.
Same result 

`
root@walgtest:~# wal-g backup-fetch /test LATEST
INFO: 2024/08/01 05:36:16.403789 Selecting the latest backup...
INFO: 2024/08/01 05:36:16.404612 Backup to fetch will be searched in storages: [default]
INFO: 2024/08/01 05:36:16.420718 LATEST backup is: 'base_0000000200000002000000C9_D_0000000200000002000000C6'
INFO: 2024/08/01 05:36:16.481424 Delta from base_0000000200000002000000C6_D_0000000200000002000000B2 at LSN 2/C6000028
INFO: 2024/08/01 05:36:16.527019 Delta from base_0000000200000002000000B2_D_0000000200000002000000A6 at LSN 2/B2000028
INFO: 2024/08/01 05:36:16.575037 Delta from base_0000000200000002000000A6 at LSN 2/A6000028
INFO: 2024/08/01 05:36:16.650078 Finished extraction of part_003.tar.br
ERROR: 2024/08/01 05:36:16.650101 Extraction error in part_003.tar.br: extractOne: tar extract failed: cbrotli: PADDING_2
INFO: 2024/08/01 05:36:16.668042 Finished extraction of part_001.tar.br
ERROR: 2024/08/01 05:36:16.668059 Extraction error in part_001.tar.br: extractOne: tar extract failed: cbrotli: RESERVED
WARNING: 2024/08/01 05:36:16.668073 2 files failed to download: [part_003.tar.br part_001.tar.br]. Going to sleep and retry downloading them.
WARNING: 2024/08/01 05:36:16.668081 retries left: 14
`
I don't know what to do

**Comment by x4m** [comment]
What kind of storage you use? Are you sure files are not corrupted?
Do you use encryption?

**Comment by x4m** [comment]
Wal-G does not embedd encryption information. Look for libsodium or pgp header…--Отправлено из мобильной Яндекс Почты01.08.2024, 08:45, "opopovich" ***@***.***>:
Hello @x4m
Thanks for answer!
We install Ubuntu 22.04 and download newest 3.0.2 and 3.0.0 version.
Same result
***@***.***:~# wal-g backup-fetch /test LATEST INFO: 2024/08/01 05:36:16.403789 Selecting the latest backup... INFO: 2024/08/01 05:36:16.404612 Backup to fetch will be searched in storages: [default] INFO: 2024/08/01 05:36:16.420718 LATEST backup is: 'base_0000000200000002000000C9_D_0000000200000002000000C6' INFO: 2024/08/01 05:36:16.481424 Delta from base_0000000200000002000000C6_D_0000000200000002000000B2 at LSN 2/C6000028 INFO: 2024/08/01 05:36:16.527019 Delta from base_0000000200000002000000B2_D_0000000200000002000000A6 at LSN 2/B2000028 INFO: 2024/08/01 05:36:16.575037 Delta from base_0000000200000002000000A6 at LSN 2/A6000028 INFO: 2024/08/01 05:36:16.650078 Finished extraction of part_003.tar.br ERROR: 2024/08/01 05:36:16.650101 Extraction error in part_003.tar.br: extractOne: tar extract failed: cbrotli: PADDING_2 INFO: 2024/08/01 05:36:16.668042 Finished extraction of part_001.tar.br ERROR: 2024/08/01 05:36:16.668059 Extraction error in part_001.tar.br: extractOne: tar extract failed: cbrotli: RESERVED WARNING: 2024/08/01 05:36:16.668073 2 files failed to download: [part_003.tar.br part_001.tar.br]. Going to sleep and retry downloading them. WARNING: 2024/08/01 05:36:16.668081 retries left: 14
I don't know what to do

**Comment by opopovich** [comment]
Thanks @x4m i will check this

**Comment by opopovich** [comment]
Archive are encrypted

**Comment by x4m** [comment]
Perhaps, we could embedd some encryption information into backup metadata so that client could debug it easily.
In fact, encryption metadata was poorly designed, admittedly by me in 2017. E.g. each WAL file can be encrypted with different cryptography lib or key. And there is no easy way to understand it.
