### ISSUE TITLE
Problem is always appeared in case of restoring more than 1 delta.

### ISSUE THREAD

**Issue by tam-i13** [wal-g/wal-g#177]
Hi, I have tested wal-g and ran into the problem. When backup-fetch in 2 delta copys, restore is not fine.
Problem was appeared when I restoring backup from two deltas. Errors during recovery are being appeared, if the recovery chain is greater than 1st delta. 
Wal-g 0.2.4
PostgreSQL 9.6.9
For testing restore on special server.

```
I have
base_000000010000004200000085                            2019-01-26T04:26:39Z 000000010000004200000085
base_0000000100000044000000C3_D_000000010000004200000085 2019-01-27T00:00:28Z 0000000100000044000000C3
base_000000010000004B000000E5_D_0000000100000044000000C3 2019-01-28T08:34:02Z 000000010000004B000000E5
```

Test 1 (ERROR), restore base_000000010000004B000000E5_D_0000000100000044000000C3 

```
INFO: 2019/01/28 11:38:38.084845 Delta from base_0000000100000044000000C3_D_000000010000004200000085 at LSN 44c3000060 
INFO: 2019/01/28 11:39:09.204224 Delta from base_000000010000004200000085 at LSN 4285000060 
INFO: 2019/01/28 11:39:50.957167 Finished decompression of part_008.tar.lz4
…

It is time to restore the delta
INFO: 2019/01/28 11:43:08.106007 
Backup extraction complete.
INFO: 2019/01/28 11:43:08.106033 base_000000010000004200000085 fetched. Upgrading from LSN 4285000060 to LSN 44c3000060 
INFO: 2019/01/28 11:43:08.106054 Finished decompression of pg_control.tar.lz4
INFO: 2019/01/28 11:43:18.758035 Finished extraction of part_001.tar.lz4
ERROR: 2019/01/28 11:43:18.758149 Extraction error in part_001.tar.lz4: extractOne: Interpret failed: Interpret: failed to apply increment for '/mnt/RAMDB/data_restore/base/10742633/27485138': incremented file should always exist: open /mnt/RAMDB/data_restore/base/10742633/27485138: no such file or directory
INFO: 2019/01/28 11:43:18.759023 Finished decompression of part_001.tar.lz4
..
```

Test 2 (OK), restore base_0000000100000044000000C3_D_000000010000004200000085 

```
INFO: 2019/01/28 12:06:51.451995 Delta from base_000000010000004200000085 at LSN 4285000060 
INFO: 2019/01/28 12:07:37.297778 Finished extraction of part_008.tar.lz4
INFO: 2019/01/28 12:07:37.297780 Finished decompression of part_008.tar.lz4
INFO: 2019/01/28 12:07:37.371410 Finished decompression of part_009.tar.lz4
INFO: 2019/01/28 12:07:37.371430 Finished extraction of part_009.tar.lz4
…
INFO: 2019/01/28 12:11:01.388172 
Backup extraction complete.
INFO: 2019/01/28 12:11:01.388186 base_000000010000004200000085 fetched. Upgrading from LSN 4285000060 to LSN 44c3000060 
INFO: 2019/01/28 12:11:01.388222 Finished decompression of pg_control.tar.lz4
INFO: 2019/01/28 12:11:20.243592 Finished extraction of part_008.tar.lz4
..
INFO: 2019/01/28 12:11:29.167371 
Backup extraction complete.
```

I've checked several times on different backups, problem is always appeared in case of restoring more than 1 delta. As we see, sometimes we get an error during restoring (from LSN 4285000060 to LSN 44c3000060), but sometimes not.

There are no errors during the process of backuping.
Please clarify the nature of the problem.

**Comment by x4m** [comment]
Thanks for reporting!
I'll look into this. I did not encounter this myself but heard reports about quite similar problem no so long ago.

**Comment by Tinsane** [comment]
Hello!
We tried to reproduce this issue locally but failed to do it. @tam-i13, can you add a setting "WALG_LOG_LEVEL=DEVEL" and send us a full log file of failing backup-fetch?

**Comment by tam-i13** [comment]
Hello. 
I've added "WALG_LOG_LEVEL=DEVEL". You can get log archive here (https://yadi.sk/d/KhTD83bIwu11vg).

**Comment by x4m** [comment]
Please test that issue is fixed in the recent version. If something is still broken plz reopen.
