### ISSUE TITLE
Slow wal-g S3 storage interactions

### ISSUE THREAD

**Issue by Alveel** [wal-g/wal-g#1833]
### Database name
PostgreSQL

# Issue description
`wal-g` commands relating to S3 storage backend take significantly longer than they should.

### Describe your problem
When a backup is run with `wal-g` it takes a _loooong_ time. It can take hours up to days.

Similarly a backup restore can take the same amount of time. When a replica gets re-initialised and uses the WAL archive to catch up to the leader, it can also take literal days.

When we run a `wal-g st ls <directory>` command it executes over 72.000 HTTP requests to list the entirety of a directory that contains just 420 files.

`wal-g st cat <file>` executes over 4.500 HTTP requests.

Lastly it can also fail when it tries to list a path with a trailing slash `foo/bar//`; our S3 provider [MinIO does not support this](https://github.com/minio/minio/issues/5874#issuecomment-524566676). This sometimes happens, and sometimes not, so maybe this is some kind of race condition?

### Please provide steps to reproduce
It is possible this is only reproducible with our specific setup, but here is what we do:

- `kubectl exec` into leader pod
- Run any `wal-g st` command, e.g.
- `wal-g --walg-log-level=DEVEL st check read`

### Please add config and wal-g stdout/stderr logs for debug purpose

We use `wal-g` in [StackGres](https://stackgres.io/doc/1.11/) installed in OpenShift 4.14.

<details><summary>Logs of HTTP requests</summary>
<p>

`wal-g st cat <file>`

```
time wal-g --walg-log-level=DEVEL st cat mets-api-db-new/wal_005/00000012000000AA000000D9.lz4 2>&1 | grep "HTTP response code" | wc -l
4529

real	1m17.012s
user	0m2.271s
sys	0m0.925s
```
</p>
<p>

`mc cat <file>`

```
time mc cat <alias>/<bucket>/<path>/wal_005/00000012000000AA000000D9.lz4 > /dev/null

________________________________________________________
Executed in    1.58 secs      fish           external
   usr time  125.96 millis    0.00 micros  125.96 millis
   sys time  133.13 millis  820.00 micros  132.31 millis
```
</p>
<p>

`wal-g st check read` from cluster in the same datacenter as the S3 endpoint sees 4529 HTTP 200's
[ocp302-mets-api-db-walg-st-check-read.log](https://github.com/user-attachments/files/17718339/ocp302-mets-api-db-walg-st-check-read.log)

`wal-g st check read` from cluster in a different datacenter as the S3 endpoint sees 49055 HTTP 200's?!
[ocp203-mets-api-db-walg-st-check-read.log](https://github.com/user-attachments/files/17718348/ocp203-mets-api-db-walg-st-check-read.log)

```
grep 'HTTP response code: 200' ocp302-mets-api-db-walg-st-check-read.log | wc -l
4529

grep 'HTTP response code: 200' ocp203-mets-api-db-walg-st-check-read.log | wc -l
49055
```
</p>
</details>

<details><summary>Logs of trailing slash error</summary>
<p>

```
wal-g --walg-log-level=DEVEL st ls
DEBUG: 2024/11/12 09:15:00.523759 --- COMPILED ENVIRONMENT VARS ---
...
DEBUG: 2024/11/12 09:34:01.130266 request GET response: 362 request: 0
ERROR: 2024/11/12 09:34:01.130384 list folder: failed to list s3 folder: 'mets-api-db//': XMinioInvalidObjectName: Object name contains unsupported characters.
        status code: 400, request id: 18072ECD51AD30D9, host id: 5d9e84e57df682843bda6c909d1bf5c3be42c2cff0cd6bf9f4d9ab4ebd86f559
```

</p>
</details>

**Comment by x4m** [comment]
We had a bug in pre-released version. I suspect that stackgres is using that pre-release. Switching to release should resolve the issue.

**Comment by x4m** [comment]
Yup. Let me know if something is still wrong. Thanks for doing WAL-G better.

**Comment by Alveel** [comment]
Updated to 3.0.3 and all our problems went away 😄
