### ISSUE TITLE
Reduce unnecessary warnings for Non-Physical Objects during PostgreSQL wal-g backup

### ISSUE THREAD

**Issue by robertmu** [wal-g/wal-g#1850]
### Database version
PostgreSQL 14.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit.

### wal-g Version
wal-g version 	55d0801a	2024.12.02_13:40:49	PostgreSQL

# Issue description

### Describe your problem
When performing a backup with wal-g, I encountered numerous warnings related to `relfilenode` conversion failures. These warnings are generated for Non-Physical Objects that inherently do not have a `relfilenode` (no physical storage), leading to conversion failures. The warnings seem unnecessary and clutter the log output.
![image](https://github.com/user-attachments/assets/5d7f2f4a-cde8-4f66-83c8-f957ac3ea0c7)

### Please provide steps to reproduce
* Execute the following command
``` bash
wal-g backup-push /path/to/database
```

* You will observe warning messages in the logs similar to
```
WARN: Failed to get relfilenode for relation test_view: strconv.ParseUint: parsing "": invalid syntax
```

**Comment by ostinru** [comment]
Hi, @robertmu !

It seems that you have observed the same issue as in https://github.com/wal-g/wal-g/pull/1816#issuecomment-2460746524

You can safely ignore it.

Fix here: https://github.com/wal-g/wal-g/pull/1849

**Comment by ostinru** [comment]
Ah! You sent a PR: https://github.com/wal-g/wal-g/pull/1851
