### ISSUE TITLE
Unified binary names

### ISSUE THREAD

**Issue by stl-victor-sudakov** [wal-g/wal-g#1853]
### Database name
PostgreSQL

# Issue description

The published binaries for AMD64 and ARM64 have different format of filenames. For example, `wal-g-pg-ubuntu20.04-aarch64` has no dash after "ubuntu" while `wal-g-pg-ubuntu-20.04-amd64` does.

### Describe your problem
This difference is a bit inconvenient when I use Ansible to install wal-g binaries to hosts with multiple architectures. My suggestion is that only the arch indicator should change and no other part of the filename, it could be helpful if I could use only `{{ ansible_architecture }}` to select between binaries.

**Comment by stl-victor-sudakov** [comment]
Hmm, "https://github.com/wal-g/wal-g/releases/download/v3.0.3/wal-g-pg-ubuntu-20.04-aarch64" is still a 404. Is this expected? Was no rebuild triggered?

**Comment by chipitsine** [comment]
It will be applied for the next release

**Comment by stl-victor-sudakov** [comment]
> It will be applied for the next release

Ah, OK. Thank you!
