### ISSUE TITLE
pg_wal_restore_test fails with missing archive_status file error

### ISSUE THREAD

**Issue by robertmu** [wal-g/wal-g#1867]
### Description
The `pg_wal_restore_test` integration test is showing flaky behavior - sometimes passing, sometimes failing during the pg_rewind step with the following error: 

```
could not open source file "/var/lib/postgresql/10/main_beta/pg_wal/archive_status/000000020000000000000025.ready": No such file or directory
```

![image](https://github.com/user-attachments/assets/24d8aada-f698-432e-a65d-637e1bc6baf1)

**Comment by chipitsine** [comment]
good catch. likely we have look at other "sleep" invocations in scripts
