### ISSUE TITLE
backup-fetch fails with "Interpret: copy failed" unexpected EOF (wal-g 0.1.15)

### ISSUE THREAD

**Issue by johannesluedke** [wal-g/wal-g#191]
system: CentOS 7 in a docker image, Postgres 9.4
wal-g version: `0.1.15`

`wal-g backup-fetch  <folder> LATEST` fails with 

```
2019/02/28 11:05:52 extractOne: Interpret failed: Interpret: copy failed: unexpected EOF
2019/02/28 11:05:52 unexpected EOF
DecompressLz4: lz4 write failed
github.com/wal-g/wal-g.Lz4Decompressor.Decompress
```

This also happens with `WALG_DOWNLOAD_CONCURRENCY=1` 😱

**Comment by x4m** [comment]
Hi! usually unexpected EOF is the sign of broken tcp connection.
But this error may hide a lot of different root causes. Can you plese give bigger part of log?

Also, may I ask you to try 0.2.6, we have significantly improved retry logic (though it's still far from perfect)

**Comment by johannesluedke** [comment]
> Also, may I ask you to try 0.2.6, we have significantly improved retry logic (though it's still far from perfect)

Is it safe to use 0.2.6 for restore? It's tagged as a pre-release. And it works to make the backup with 0.1.15 but restore with 0.2.6?

**Comment by johannesluedke** [comment]
>  But this error may hide a lot of different root causes. Can you plese give bigger part of log?

I tried to reproduce the log, but this time no errors and it restored like a charm. It also took less then <5mins while last time (failed) restore took over ~1h

**Comment by x4m** [comment]
As for now we only know about one bug present in 0.2.6. It is related to high disk concurrency during backup upload. And the very same bug found in 0.1.15. So, yes, 0.2.6 seems safe for restore.
