### ISSUE TITLE
Add support for backup to remote host via ssh

### ISSUE THREAD

**Issue by thda** [wal-g/wal-g#192]
Hi,

some companies do not want to store data on the cloud and do not have any plans to implement on-premise cloud storage.

For those use cases, it would be great if wal-g allowed pushing to a remote server via ssh.
Could you please let me know if that sounds doable, and if so, can we work on the design ?

Cheers
Thomas

**Comment by x4m** [comment]
Hi! Thanks for this proposal!

With ssh, you have two machines: 1. cluster node host 2. backup host

It seems hard to impractical to run WAL-G on the backup host and acquire data through rep protocol or scp.

Running WAL-G on the DB side seems easy, there's no need to change a lot of things. If there are well-supported scp go adapters - I do not see anything difficult with it, it should be as straightforward as file system storage folder (see fs_folder.go)

**Comment by x4m** [comment]
We already have S3, GCP, SWIFT, Azure, FS. Why not add SSH?
@Tinsane , what do you think?

**Comment by thda** [comment]
Provided you give the go, I can give a shot at it (with a good test suite of course)

**Comment by thda** [comment]
Started working on this, hopefully it will fit in your goals.

**Comment by x4m** [comment]
Yes, sure, this feature looks quite usable! Thanks for working on this.

One thing that may be of interest: in S3 we have parallel uploads, other storages do not have this. If you have some ideas on how to implement parallel uploads for scp - it would be cool too.

**Comment by RajKiranS** [comment]
Yes, this is indeed a quite useful feature for those who do not want to upload to cloud.

I am very much interested in this. When can I expect this feature?

Thanks for your work here!

**Comment by OrangeDog** [comment]
This appears to be done?

**Comment by usernamedt** [comment]
> This appears to be done?

Yes, looks like it is. For anyone interested, there is the [corresponding section](https://github.com/wal-g/wal-g/blob/master/docs/STORAGES.md#ssh) in WAL-G docs.
