### ISSUE TITLE
WAL-E metadata not cleaned up on delete

### ISSUE THREAD

**Issue by cjhubert** [wal-g/wal-g#201]
It appears that the delete command will clean up old WAL-E backups in S3 but leaves behind the `extended_version.txt` metadata file alone.

You can see the file in the WAL-E backup I uploaded in issue 172 (Didn't link it since I wanted to avoid the auto-reference github does), but the file in question has a path similar to `basebackups_005/base_000000010000000000000002_00000040/extended_version.txt`

I think this is the relevant code in WAL-E where it cleans up the file in question
https://github.com/wal-e/wal-e/blob/2bf9df9cd82f1600495f2cbb6621ee4c18d92cc6/wal_e/worker/base.py#L288

**Comment by Tinsane** [comment]
@g0djan, what do you think about this issue, as long as you are refactoring delete handler now?

**Comment by g0djan** [comment]
After refactoring delete command, it will delete all files in this folder if sentinel file of this backup will be recognized as old enough.

**Comment by g0djan** [comment]
I finished refactoring of delete handler where solve your problem too. You may use it if you clone the latest version of repo and build it. But it hasn't been released yet.
