### ISSUE TITLE
DecryptAndDecompressTar: decrypt failed: openpgp: incorrect key

### ISSUE THREAD

**Issue by femaref** [wal-g/wal-g#210]
Sometimes I'm getting the above error using `wal-g backup-fetch`, using a pgp key with passphrase. The passphrase is correct, and the backup works as well. I've added a debug statement to see which file it fails on:

```
INFO: 2019/03/19 11:32:51.865630 LATEST backup is: 'base_000000010000000000000009'
INFO: 2019/03/19 11:32:52.305235 Finished decompression of part_003.tar.lz4
INFO: 2019/03/19 11:32:52.305261 Finished extraction of part_003.tar.lz4
ERROR: 2019/03/19 11:32:52.305284 part_003.tar.lz4 DecryptAndDecompressTar: decrypt failed: openpgp: incorrect key
INFO: 2019/03/19 11:32:53.513288 Finished extraction of part_001.tar.lz4
INFO: 2019/03/19 11:32:53.513338 Finished decompression of part_001.tar.lz4
INFO: 2019/03/19 11:33:54.132282 Finished extraction of part_003.tar.lz4
INFO: 2019/03/19 11:33:54.132316 Finished decompression of part_003.tar.lz4
INFO: 2019/03/19 11:33:54.610425 Finished extraction of pg_control.tar.lz4
INFO: 2019/03/19 11:33:54.610457 Finished decompression of pg_control.tar.lz4
```

On larger backups it fails on multiple archives. I've downloaded the offending file and it decrypts just fine using `gpg`. I've traced the error to https://github.com/wal-g/wal-g/blob/39d192d1141c45ebefa5daada546379db75b4129/internal/open_pgp_crypter.go#L190, however I'm not sure why it happens and why a second decrypt works. I think it would be good to fix as such a line isn't really something you want to read in a backup tool.

For reproduction, I've started with an empty cluster, written some data to it. The pgp key is a fresh key.

**Comment by femaref** [comment]
I've narrowed it down to a race condition on `crypter.SecretKey`.

https://github.com/wal-g/wal-g/blob/39d192d1141c45ebefa5daada546379db75b4129/internal/open_pgp_crypter.go#L147-L188

as the loading/decrypting is concurrent, multiple routines will and write to the `crypter.SecretKey` variable. Two options:

1. keep the behaviour roughly the same, as in, decrypt on the first use, but protect with a RWMutex
2. load/decrypt the key in `ConfigurePGPCrypter`.

I'm experimenting with the first option right now.

**Comment by femaref** [comment]
https://github.com/wal-g/wal-g/pull/213

**Comment by Tinsane** [comment]
Thank you for your contribution!
One more thing: could you add your contacts to CONTRIBUTORS list?
