### ISSUE TITLE
home directory detection

### ISSUE THREAD

**Issue by femaref** [wal-g/wal-g#216]
postgres calls the archive/restore command with a very limited env, notably, `$PATH` and `$HOME` are missing. As such, the home dir detection of `github.com/mitchellh/go-homedir` fails, as it can't find `getent`. 

There is a fix for that (https://github.com/mitchellh/go-homedir/issues/18) but that's on in the v1.1.0 release.

Looking for the code, there are two other places where the homedir is used - `internal/crypto.go` and `internal/config.go`. Both use `os/user.Current`. Is there a reason why `cmd/root.go` uses the other way? Nonetheless, a workaround right now is to 
 use `HOME=/path/to/dir /usr/bin/wal-g`.

**Comment by x4m** [comment]
Hi! Sorry for so long delay...
Yes, this go-home thing certainly  is a problem: usages should be unified. And if we really need go-homedir, it should be in gopkg.toml?

**Comment by x4m** [comment]
@femaref can you please send a PR with behavior that you think is optimal?
I mean to choose  between go-homedir and os/user.Current?

**Comment by x4m** [comment]
Should be fixed now, please reopen if this will reappear in 0.2.10
