### ISSUE TITLE
wal-g gets killed by CentOS OOM Killer during backup-push

### ISSUE THREAD

**Issue by johannesluedke** [wal-g/wal-g#224]
On a server with limited RAM and CentOS, wal-g gets killed by CentOS OOM killer. For the database as such, 512MB of RAM is enough for our operation. I had to increase this now in order to make backups work (backup size on AWS is ~570 MB), but I don't think that this is the way this is supposed to work: Necessary RAM/CPU size of server should be defined from normal operations, not from backup. Maybe one could add an option to say "only use x MB of RAM during backup"?

**Comment by x4m** [comment]
Hi!
RAM is used for buffers between data transformations.
The pipeline is Disk->Tar->Compression->Encryption->Network.

If something on the left works faster than something on the right - you can observe data accumulation in RAM. In my experience, this accumulation never exceeded 370Mb per one disk reader. The easiest thing that you can do with this - 1. reduce disk concurrency if you use multiple readers 2. limit disk read rate limit

**Comment by johannesluedke** [comment]
I did not set `WALG_UPLOAD_DISK_CONCURRENCY`, so this defaults to `1`, right? As for the disk rate, which value would you think could work for `WALG_DISK_RATE_LIMIT`?

When thinking about having to add a WALG_DISK_RATE_LIMIT to my config, I'm thinking it would be nice if the backup tool, wal-g, took care of finding good values by itself (only in the case when they are not configured explicitely by env variables)

**Comment by x4m** [comment]
Yeah, you are 100% right. I'm certainly sure that not every PostgreSQL instance is 4Gb+.

Current logic for handling slow network is very RAM-expensive, we should do something about it.

Also, consider using brotli, it will reduce network usage significantly, thus reducing RAM usage.

**Comment by x4m** [comment]
WALG_DISK_RATE_LIMIT is in bytes per second.
Set it to the expected speed of your network connection.

**Comment by joeblew99** [comment]
@x4m 
I also have this issue. But compression was removed in a recent PR
https://github.com/wal-g/wal-g/commit/a88924d5016a6a40a8746e3d9e92e4940888f59b

Why ?
