### ISSUE TITLE
Unit tests in separate folder?

### ISSUE THREAD

**Issue by pohzipohzi** [wal-g/wal-g#229]
With the exception of a few packages in `internal`, is there a reason why most unit tests currently reside in a folder `test`?

I think it may be more appropriate for tests to be beside the file that they are testing. One important reason is so that we can get package level coverage when we run tests, using Go's `coverprofile` tool. Another reason is to support white box testing - there are many unexported methods in the codebase that have `TODO: unit tests` in them, which will not be possible to test if tests exist in another package.

I can make a PR to move the files to their relevant packages if we are okay with this approach

**Comment by g0djan** [comment]
Someone did it.
