### ISSUE TITLE
Support for postgresql 9.5

### ISSUE THREAD

**Issue by michalgutkowski** [wal-g/wal-g#23]
https://github.com/wal-g/wal-g/blob/a2f3a7038eb547712b1dd83e941d795af0aab5b6/connect.go#L34

Hi, we would like to test wal-g, but it seem, PG 9.6 is only supported as it uses function pg_start_backup  from 9.6 with 3 arguments, where as in 9.5 is only 2:
https://www.postgresql.org/docs/9.5/static/functions-admin.html

**Comment by fdr** [comment]
I wasn't planning adding code paths to support this. Maybe use WAL-E for a few more years.
