### ISSUE TITLE
Support for FS storages.

### ISSUE THREAD

**Issue by patsevanton** [wal-g/wal-g#260]
I read release notes v0.2.9.
`Support for S3, GCS, SWIFT, FS, and Azure storages.`
What is FS storages?
Thanks!

**Comment by x4m** [comment]
Hello! Thanks for your interest in WAL-G
FS stands for ```file system```
This functionality is implemented mostly for tests: there is no sense in making a backup on the same filesystem where the database lives.

**Comment by Tinsane** [comment]
Hello!
Actually, that's not all. One of the common use cases is to mount network storage to file system and backup to it using FS storage.

**Comment by patsevanton** [comment]
Where i can see example use FS for wal-g? Wiki is empty.

**Comment by x4m** [comment]
You can use WALG_FILE_PREFIX to specify a storage location.
BTW, yeah, documentation really is our weak side, any Pull Request enhancing documentation are very welcome. I would be great if we had a comprehensive page about WAL-G storages.

**Comment by x4m** [comment]
I'll close this, if you have some new questions and ideas please feel free to open\reopen.
