### ISSUE TITLE
wal-g backup-push should return backup name in output

### ISSUE THREAD

**Issue by HeikoOnnebrink** [wal-g/wal-g#265]
In order to integrate wal-g into automated / scheduled workflows that allow automated restores the backup-push option should return at the end of the execution an INFO line that contains the name of the written backup set 

INFO: 2019/05/07 08:30:57.445763 Walking ...
INFO: 2019/05/07 08:30:57.446003 Starting part 1 ...
INFO: 2019/05/07 08:30:59.622046 Finished writing part 1.
INFO: 2019/05/07 08:31:00.242104 Starting part 2 ...
INFO: 2019/05/07 08:31:00.242612 /global/pg_control
INFO: 2019/05/07 08:31:00.244206 Finished writing part 2.
INFO: 2019/05/07 08:31:00.392218 Starting part 3 ...
INFO: 2019/05/07 08:31:00.392728 backup_label
INFO: 2019/05/07 08:31:00.392775 tablespace_map
INFO: 2019/05/07 08:31:00.393878 Finished writing part 3.
**INFO: 2019/05/07 08:31:00.393989 Completed backup base_000000010000000000000045**

From here client could cut out from STDOUT of backup execution the backup name after string "Completed backup " (or any other static keyword/string )and save it externally and use it for any later automated restore ..

**Comment by HeikoOnnebrink** [comment]
@x4m 
after my first go lang steps in your repo I have located the place where I need to add the required code

file internal/backup_push_handler.go
func HandleBackupPush
add to the end 

```
// logging backup set name
tracelog.InfoLogger.Println("Wrote backup set with name " + backupName)

```
maybe someone can take it from here .. 
in the meantime I will learn how to create a pull-request ;-)

**Comment by HeikoOnnebrink** [comment]
.. was easier than I thought .. added pull request #272

**Comment by x4m** [comment]
Fixed, thanks!
