### ISSUE TITLE
File `base_*_backup_stop_sentinel.json` is missing information about `global/pg_control`

### ISSUE THREAD

**Issue by carrolcox** [wal-g/wal-g#277]
File `base_*_backup_stop_sentinel.json` is missing information about `global/pg_control`.
Therefore, as I see, `wal-g backup-fetch` does not pick up an archive with this file from S3 bucket.

---

*wal-g*: v0.2.9
*postgresql*: v9.6.13
*S3*: AWS S3 bucket

**Comment by carrolcox** [comment]
There is a part of `base_*_backup_stop_sentinel.json`:

```json

{...}
        "/9.6/main/global/6002": {
            "IsIncremented": false,
            "IsSkipped": false,
            "MTime": "2019-05-06T16:51:51.591616776+03:00"
        },
        "/9.6/main/global/pg_filenode.map": {
            "IsIncremented": false,
            "IsSkipped": false,
            "MTime": "2019-05-06T16:51:51.591616776+03:00"
        },
        "/9.6/main/global/pg_internal.init": {
            "IsIncremented": false,
            "IsSkipped": false,
            "MTime": "2019-05-13T08:58:37.68549997+03:00"
        },
        "/9.6/main/pg_clog/0051": {
            "IsIncremented": false,
            "IsSkipped": false,
            "MTime": "2019-05-06T16:51:51.599616398+03:00"
{...}

```

**Comment by carrolcox** [comment]
I found how this file are unarchived.
My fail — wal backup maked from wrong base path. It should be equal `${PGDATA}`.

Thanks
PS: closing issue now.

**Comment by x4m** [comment]
Sorry for the delay.
That pg_control thing is a feature - control file is restored last from separate tar, so that you do not run partially restored cluster.
