### ISSUE TITLE
Environment Variables for Connection with S3

### ISSUE THREAD

**Issue by azhar1709** [wal-g/wal-g#30]
Hi,

We are using Softlayer S3 storage & which works on Swift API. I have successfully setup WAL-E using S3 storage by defining WALE_S3_PREFIX, SWIFT_AUTH_VERSION, SWIFT_PASSWORD, SWIFT_USER & SWIFT_AUTHURL under /etc/wal.e.d/env.

I have installed the wal-g & moved it to /usr/bin but when I am executing wal-push it is giving an error "FATAL: Did not set the following environment variables:WALE_S3_PREFIX". 
I tried setting up this environment variable which I had setup for WAL-E implementation in bashrc file but after that I am getting below error: 
goroutine 1 [running]:
github.com/wal-g/wal-g.Configure(0x10, 0xc420156620, 0x0, 0x18)
        /home/travis/gopath/src/github.com/wal-g/wal-g/upload.go:77 +0xa6e
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:83 +0x1f6
 
Request you to please let me know if i missed any step or i need to make some changes in my environment variable for WAL-G to connect with S3 storage on Softlayer.

**Comment by azhar1709** [comment]
Hi Team,
Is there any update on above query for setting up environment variable to connect with S3 storage on Softlayer. Any help would be greatly appreciated.

**Comment by x4m** [comment]
Hi @azhar1709 ! SWIFT_* veriables are not supported as for now. But seems like your problem is related to just not configured environment variables for WAL-G. WAL-G does not see WALE_S3_PREFIX.

**Comment by x4m** [comment]
Team at #74 seems to be working on SWIFT too, I think i's fine to close this issue.
Feel free to open questions or report bugs. Thanks for your effort to make WAL-G better.
