### ISSUE TITLE
WALG_UPLOAD_CONCURRENCY > 0: unable to use in scripts due to BG Uploader

### ISSUE THREAD

**Issue by femaref** [wal-g/wal-g#309]
When using the BG Uploader, wal-g automatically renames `.ready` to `.done` in the `archive_status`. While this is fine when using wal-g standalone, you can't use it in scripts. I'm using a script as I need the wal files to feed a hot standby but also want to archive them to s3 via walg.

This behaviour should be prominently displayed in the docs (i.e. if you use wal-g in a script, make sure to set `WALG_UPLOAD_CONCURRENCY` to 0, so wal segments aren't deleted prematurely).

**Comment by x4m** [comment]
This is true. I want to do this in #127 
But still, have not enough resources to do it...

**Comment by x4m** [comment]
@reshke Is this task currently done?

**Comment by reshke** [comment]
@x4m yes its https://github.com/wal-g/wal-g/commit/e6c85a5740af84ee6658004fb5d249eb458ad3fb
