### ISSUE TITLE
Tablespace Support 

### ISSUE THREAD

**Issue by Harrykris** [wal-g/wal-g#31]
Does WAL-G support tablespace backup , It seems WAL-G didn't pick the data from tablespace and while restoration it didn't ask any tablespace details(RESTORE SPEC) like --restore-spec, which WAL-E asks while using backup-fetch command. 

And upon starting the restored cluster throws the error of missing tablespace.

Are we missing anything here ..?

Any pointers in this direction will be appreciated.

**Comment by x4m** [comment]
Try mkdir pg_tblspc (unless you are talking about actual tablespace support).

**Comment by x4m** [comment]
I've addressed this issue in the previous commit. That's not actual tablespace support. But that's the issue referenced here, so I'll close this. If the problem will occur in future versions, plz report it.
