### ISSUE TITLE
wal-g wal-push always overwrites WAL with the same name

### ISSUE THREAD

**Issue by ilicmilan** [wal-g/wal-g#354]
**Version**
```
wal-g version v0.2.9
```
**Expected Behavior**
`wal-push` command should return non-zero exit code, as stated in the Documentation for `WALG_PREVENT_WAL_OVERWRITE`
```
If the different file is already archived under the same name,
WAL-G will return the non-zero exit code to prevent PostgreSQL from removing WAL.
```
**Actual Behavior**
`wal-push` always overwrites existing WAL file returning zero exit code.
Even if both files have the same content (Modified time will be changed).

**Steps to Reproduce**
```
[root@walg-test-01 ~]# export WALG_GS_PREFIX=gs://test-walg
[root@walg-test-01 ~]# export PGHOST=/var/run/postgresql
[root@walg-test-01 ~]# export PGUSER=postgres
[root@walg-test-01 ~]# export WALG_PREVENT_WAL_OVERWRITE=true  # whatever I've set here doesn't work
```

```
[root@walg-test-01 ~]# wal-g wal-push /var/lib/pgsql/9.5/data/pg_xlog/000000010000000000000043
INFO: 2019/07/26 11:49:37.260601 FILE PATH: 000000010000000000000043.lz4

[root@walg-test-01 ~]# echo 1 >> /var/lib/pgsql/9.5/data/pg_xlog/000000010000000000000043

[root@walg-test-01 ~]# wal-g wal-push /var/lib/pgsql/9.5/data/pg_xlog/000000010000000000000043
INFO: 2019/07/26 11:49:50.260601 FILE PATH: 000000010000000000000043.lz4

[root@walg-test-01 ~]# echo $?
0
```

**Comment by x4m** [comment]
Hi! Thanks for the report!
Yes, this is a bug, we need to fix it.
Also there's #278

**Comment by benjaminjb** [comment]
I see there was a merge on Oct 16 (https://github.com/wal-g/wal-g/pull/410) that was supposed to take care of this wal-g overwrite issue, but I'm still experiencing this with wal-g v0.2.13. Is this still an issue for others or is my setup wrong? (That "or" could be an "and", but I'd like to rule out certain errors.)

**Comment by x4m** [comment]
ISTM 0.2.13 was shipped on October 15. I think it's time to have another pre-release...

**Comment by benjaminjb** [comment]
With 0.2.14, I am now getting the expected error when trying to push the same file name. So is this issue close-able?

**Comment by x4m** [comment]
Thanks @benjaminjb !
