### ISSUE TITLE
My ceph does not enable server encryption, and WALG_S3_SSE prevents me from backing up

### ISSUE THREAD

**Issue by wopincm** [wal-g/wal-g#356]
ERROR: 2019/07/29 07:51:00.486673 failed to upload 'spilo/pg-1/wal/basebackups_005/base_00000004000000000000000A/tar_partitions/part_001.tar.lz4' to bucket 'db-backup': InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
	status code: 400, request id: tx0000000000000000040f0-005d3ea508-f042e-default, host id: 
ERROR: 2019/07/29 07:51:00.486744 upload: could not upload 'base_00000004000000000000000A/tar_partitions/part_001.tar.lz4'
ERROR: 2019/07/29 07:51:00.486770 failed to upload 'spilo/pg-1/wal/basebackups_005/base_00000004000000000000000A/tar_partitions/part_001.tar.lz4' to bucket 'db-backup': InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
	status code: 400, request id: tx0000000000000000040f0-005d3ea508-f042e-default, host id: 
ERROR: 2019/07/29 07:51:00.486790 Unable to complete uploads

**Comment by x4m** [comment]
Hi! Thanks for the report!
Can you please tell me more about your problem? Was it working and not something happened? Or are you trying to introduce WAL-G and encounter this problem?

Also, I know one KMS specialist. @bn0ir is this kind of problem you fixed?

**Comment by wopincm** [comment]
@x4m I am experiencing this problem while using WAL-G, it makes me unable to backup my postgresql
My ceph does not enable server-side encryption. WALG_S3_SSE requires my ceph server to be encrypted to be able to back up my postgresql. I can't close the WALG_S3_SSE function.

**Comment by x4m** [comment]
Which version of WAL-G are you using?

**Comment by bn0ir** [comment]
Hello,
@wopincm if you don't want to enable SSE you can simply unset env variable WALG_S3_SSE (or don't set it in first place)

**Comment by wopincm** [comment]
Thank you for your help. I have solved the problem @x4m @bn0ir
