### ISSUE TITLE
wal-g delete (before|retain)* hangs indefinitely

### ISSUE THREAD

**Issue by benjamin-thomas** [wal-g/wal-g#358]
OS=Ubuntu 18.04
    wal-g version v0.2.9    5bf0fcf 2019.04.22_06:20:09
    backend=openstack swift

The following commands keep hanging for me (+30 minutes)
```
envdir ~/.envdir/wal-g/ wal-g delete before base_000000010000007900000084 --confirm
envdir ~/.envdir/wal-g/ wal-g delete retain FIND_FULL 1 --confirm
envdir ~/.envdir/wal-g/ wal-g delete retain FULL 1 --confirm
```

These commands returns immediatly
```
envdir ~/.envdir/wal-g/ wal-g backup-list
name                          last_modified        wal_segment_backup_start
base_0000000100000012000000CB 2019-07-11T14:51:40Z 0000000100000012000000CB
base_000000010000001800000037 2019-07-12T13:58:19Z 000000010000001800000037
base_0000000100000019000000E8 2019-07-12T21:10:44Z 0000000100000019000000E8
base_000000010000001F00000085 2019-07-13T21:10:54Z 000000010000001F00000085
base_000000010000002500000025 2019-07-14T21:10:42Z 000000010000002500000025
base_000000010000002A000000BA 2019-07-15T21:10:40Z 000000010000002A000000BA
base_00000001000000300000005A 2019-07-16T21:11:02Z 00000001000000300000005A
base_0000000100000035000000FA 2019-07-17T21:10:56Z 0000000100000035000000FA
base_000000010000003B0000009F 2019-07-18T21:10:52Z 000000010000003B0000009F
base_000000010000004100000040 2019-07-19T21:11:08Z 000000010000004100000040
base_0000000100000046000000E2 2019-07-20T21:12:09Z 0000000100000046000000E2
base_000000010000004C00000084 2019-07-21T21:11:11Z 000000010000004C00000084
base_000000010000005200000026 2019-07-22T21:11:02Z 000000010000005200000026
base_0000000100000057000000C7 2019-07-23T21:12:57Z 0000000100000057000000C7
base_000000010000005D00000065 2019-07-24T21:11:59Z 000000010000005D00000065
base_000000010000006300000007 2019-07-25T21:11:42Z 000000010000006300000007
base_0000000100000068000000A5 2019-07-26T21:14:22Z 0000000100000068000000A5
base_000000010000006E00000043 2019-07-27T21:11:29Z 000000010000006E00000043
base_0000000100000073000000E5 2019-07-28T21:11:44Z 0000000100000073000000E5
base_000000010000007900000084 2019-07-29T21:11:33Z 000000010000007900000084
```

Those commands (without --confirm) run fine too :

```
envdir ~/.envdir/wal-g/ wal-g delete before base_000000010000007900000084
envdir ~/.envdir/wal-g/ wal-g delete retain FIND_FULL 1 
envdir ~/.envdir/wal-g/ wal-g delete retain FULL 1 
```

Is there anyway to enable some kind of debug output, to see what's going on ? Any ideas ?

I'm barely getting familiar with archiving and wal-g.

Thanks

**Comment by x4m** [comment]
Hi! Please, repeat tour command with WALG_LOG_LEVEL=DEVEL

**Comment by benjamin-thomas** [comment]
I could not reproduce this "bug" today.

Meanwhile, I manually emptied the underlying "openstack container" (equivalent of an s3 bucket).

Whereas yesterday I had 20 or so basebackups, I recreated 15 today for testing purposes and my 12 of those got deleted in 7 minutes.

    time WALG_LOG_LEVEL=DEVEL envdir ~/.envdir/wal-g/ wal-g delete retain FULL 3 --confirm &>>/tmp/delete_log

Tbh I suspect some kind of latency issue from my provider/backend.

However, the default logging does not seem to be very chatty. Below is 2 consecutive log lines, demonstrating 2 minutes without any feedback under "normal" circumstances, seems to be long

    INFO: 2019/07/31 16:03:07.212661 base_000000010000007F00000023 will be deleted
    INFO: 2019/07/31 16:04:56.514145 000000010000007F00000023.00000028.backup.lz4

---

I would suggest returning that log line as INFO, to make it similar in behavior with `backup-push`

    postgres@pg:~$ cat /tmp/delete_log | grep Delete.*base | tail -1
    DEBUG: 2019/07/31 16:10:09.098431 Delete object basebackups_005/base_000000010000007F00000023

**Comment by benjamin-thomas** [comment]
Could be related? Inspecting my cronjob's log for a `backup-push` operation I see **1 hour** between 2 consecutive log lines, and some kind of HTTP timeout.

```
INFO: 2019/07/30 23:00:03.018060 Starting part 1 ...
INFO: 2019/07/30 23:00:44.881797 Finished writing part 1.
INFO: 2019/07/30 23:00:44.882120 Starting part 2 ...
2019/07/30 23:00:55 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCach
e-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour 
browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
INFO: 2019/07/31 00:11:30.660861 Finished writing part 2.
```

I'm not familiar with the details of the openstack/swift protocol, and can only guess it sits on top of HTTP. 

That timeout does not seem to be systematically problematic:

```
INFO: 2019/07/29 23:08:08.683452 Finished writing part 12.
INFO: 2019/07/29 23:08:08.683743 Starting part 13 ...
2019/07/29 23:08:19 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCach
e-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour 
browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
INFO: 2019/07/29 23:08:56.485350 Finished writing part 13.
INFO: 2019/07/29 23:08:56.485442 Starting part 14 ...
```

Do you feel something could be wrong on `wal-g`'s side? If that's the case, I could enable more verbose logging for `backup-push` and report back if I see this abnormality again.

**Comment by benjamin-thomas** [comment]
```
INFO: 2019/08/01 16:23:13.077138 Starting part 20 ...
INFO: 2019/08/01 16:23:13.077219 /global/pg_control
INFO: 2019/08/01 16:23:13.164231 Finished writing part 20.

^C      

real    1106m51.391s
```

I encountered this "bug" again, I controlled-c out of a manual `backup-push` process, after being "stuck" for 18 hours:

    time envdir ~/.envdir/wal-g/ wal-g backup-push /var/lib/postgresql/10/main/

I'll reporting with verbose logging next time.

**Comment by x4m** [comment]
it seems like you were doing backup-push? probably it is wating for archival
look into pg logs

**Comment by benjamin-thomas** [comment]
Damn, I'm so sorry. I initially thought I hit a similar bug with `backup-push`, and thought it could be some kind of network handling issue, but was in fact totally unrelated.

I was playing with some (wrong) parameters just before the end of that manual backup-push and got confused, so please disregard my latest comment. (my latest error did affect WAL archiving on pg's side)

I'm still puzzled by that `Unsolicited response` error message though. The mention of `err=<nil>` in the log message seems to hint that something is happening on golang's side, but it's pretty blurry to me.

I'll report with verbose logging if I hit that slowness/hanging again with the `delete` command.

**Comment by x4m** [comment]
Thanks! Waiting for details

**Comment by benjamin-thomas** [comment]
Hello again,

I think I've been bitten by that same bug again, although this time it affected my pg server : a wal file write operation got "stuck" via wal-g and that "stuck" state lasted over the week-end.

Unfortunatly (for me :p), as a result, the pg server queued up the wal files waiting for a write (via wal-g) on the hard drive, which got filled up pretty quickly, causing then my db to shut down.

I've kept the logs in case you need more data, and what follows is a recap of the lines I think are relevant.

I actived the WALG_LOG_LEVEL=DEVEL globally, so I think I've got as much logging info as I can.

---

pg server side:

grep_cmd=`cat postgresql-10-main.log.failed | grep -F 'INFO: 2019/08/07 12:30:30.170459 ' -B10 -A999 | egrep -v 'app1stuff|app2stuff' | head -20`
archive_command=`'envdir /var/lib/postgresql/.envdir/wal-g/ /usr/local/bin/wal-g wal-push %p'`


	INFO: 2019/08/07 12:25:31.051897 FILE PATH: 00000001000000A9000000DA.lz4
	DEBUG: 2019/08/07 12:26:29.810202 Put 00000001000000A9000000DB.lz4 into wal_005/
	INFO: 2019/08/07 12:26:30.391233 FILE PATH: 00000001000000A9000000DB.lz4
	DEBUG: 2019/08/07 12:27:29.399335 Put 00000001000000A9000000DC.lz4 into wal_005/
	INFO: 2019/08/07 12:27:30.002654 FILE PATH: 00000001000000A9000000DC.lz4
	DEBUG: 2019/08/07 12:28:29.838137 Put 00000001000000A9000000DD.lz4 into wal_005/
	INFO: 2019/08/07 12:28:30.366408 FILE PATH: 00000001000000A9000000DD.lz4
	DEBUG: 2019/08/07 12:29:29.637705 Put 00000001000000A9000000DE.lz4 into wal_005/
	INFO: 2019/08/07 12:29:30.018936 FILE PATH: 00000001000000A9000000DE.lz4
	DEBUG: 2019/08/07 12:30:29.665110 Put 00000001000000A9000000DF.lz4 into wal_005/
	INFO: 2019/08/07 12:30:30.170459 FILE PATH: 00000001000000A9000000DF.lz4
	2019-08-07 23:01:56.842 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
	2019-08-07 23:01:56.842 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-07 23:02:56.912 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (120 seconds elapsed)
	2019-08-07 23:02:56.912 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-07 23:04:57.036 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (240 seconds elapsed)
	2019-08-07 23:04:57.036 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-07 23:08:57.292 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (480 seconds elapsed)
	2019-08-07 23:08:57.292 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-07 23:16:57.814 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (960 seconds elapsed)



`FILE PATH` appears on each wal push operation. Under my load, I usually have at least 1 archive operation every 2 minutes. It appears that "something" happened at 12:30 where logging of wal archiving stops.

I use a time tracker, so I know I wasn't working on database stuff within that time frame. Then I have scheduled daily `wal-g backup-push` every day at 23:00, which failed due to that pending write operation.

grep_cmd2=`cat postgresql-10-main.log.failed | grep -F 'INFO: 2019/08/07 12:30:30.170459 ' -B10 -A999 | egrep -v 'app1stuff|app2stuff' | head -35 | tail -5`

	2019-08-08 07:33:29.464 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-08 16:06:01.441 CEST [12672] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (61440 seconds elapsed)
	2019-08-08 16:06:01.441 CEST [12672] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
	2019-08-08 23:02:08.330 CEST [19901] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
	2019-08-08 23:02:08.330 CEST [19901] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.

I can see there is some kind of easing back from `pg_stop_backup` logging, until 16:06, then the next backup cycle triggers the same errors.

---

Cronjob's side

cronjob=`0 23 * * * /usr/bin/envdir ~/.envdir/wal-g/ /usr/local/bin/wal-g backup-push /var/lib/postgresql/10/main/ >>/tmp/walg_backup_push.log 2>>/tmp/walg_backup_push.log`

grep_cmd3=`cat walg_backup_push.log | grep -F '2019/08/06 23:00' -B10 -A99999 | egrep -v 'Skipp?ed|\/base\/|\/global|\/pg_.*' | head -70`

	INFO: 2019/08/05 23:00:47.203974 Starting part 2 ...
	INFO: 2019/08/05 23:00:47.291690 Finished writing part 2.
	INFO: 2019/08/05 23:00:49.430723 Starting part 3 ...
	DEBUG: 2019/08/05 23:00:49.431347 Put base_00000001000000A100000019_D_000000010000009F00000074/tar_partitions/part_003.tar.lz4 into basebackups_005/
	INFO: 2019/08/05 23:00:49.534410 backup_label
	INFO: 2019/08/05 23:00:49.534982 tablespace_map
	INFO: 2019/08/05 23:00:49.535573 Finished writing part 3.
	DEBUG: 2019/08/05 23:00:49.680048 Put base_00000001000000A100000019_D_000000010000009F00000074_backup_stop_sentinel.json into basebackups_005/
	INFO: 2019/08/06 23:00:03.191788 Delta backup from base_00000001000000A100000019_D_000000010000009F00000074 with LSN a119000028. 
	INFO: 2019/08/06 23:00:03.418151 Walking ...
	DEBUG: 2019/08/06 23:00:03.418657 
	INFO: 2019/08/06 23:00:03.418713 Starting part 1 ...
	DEBUG: 2019/08/06 23:00:03.418847 Put base_00000001000000A6000000B4_D_00000001000000A100000019/tar_partitions/part_001.tar.lz4 into basebackups_005/
	DEBUG: 2019/08/06 23:00:03.486287 /PG_VERSION
	DEBUG: 2019/08/06 23:00:03.486805 /base
	DEBUG: 2019/08/06 23:00:47.900244 /postgresql.auto.conf
	INFO: 2019/08/06 23:00:47.904418 Finished writing part 1.
	INFO: 2019/08/06 23:00:48.751949 Starting part 2 ...
	INFO: 2019/08/06 23:00:48.877133 Finished writing part 2.
	INFO: 2019/08/06 23:00:50.985187 Starting part 3 ...
	DEBUG: 2019/08/06 23:00:50.985346 Put base_00000001000000A6000000B4_D_00000001000000A100000019/tar_partitions/part_003.tar.lz4 into basebackups_005/
	INFO: 2019/08/06 23:00:51.042645 backup_label
	INFO: 2019/08/06 23:00:51.043536 tablespace_map
	INFO: 2019/08/06 23:00:51.045032 Finished writing part 3.
	DEBUG: 2019/08/06 23:00:51.193665 Put base_00000001000000A6000000B4_D_00000001000000A100000019_backup_stop_sentinel.json into basebackups_005/
	INFO: 2019/08/07 23:00:09.785044 Delta backup from base_00000001000000A6000000B4_D_00000001000000A100000019 with LSN a6b4000028. 
	INFO: 2019/08/07 23:00:10.122039 Walking ...
	DEBUG: 2019/08/07 23:00:10.122635 
	INFO: 2019/08/07 23:00:10.122691 Starting part 1 ...
	DEBUG: 2019/08/07 23:00:10.122848 Put base_00000001000000AC0000001B_D_00000001000000A6000000B4/tar_partitions/part_001.tar.lz4 into basebackups_005/
	DEBUG: 2019/08/07 23:00:10.215435 /PG_VERSION
	DEBUG: 2019/08/07 23:00:10.215968 /base
	DEBUG: 2019/08/07 23:00:55.295620 /postgresql.auto.conf
	INFO: 2019/08/07 23:00:55.300028 Finished writing part 1.
	INFO: 2019/08/07 23:00:55.766676 Starting part 2 ...
	INFO: 2019/08/07 23:00:57.310413 Finished writing part 2.
	INFO: 2019/08/08 23:00:07.174077 Delta backup from base_00000001000000A6000000B4_D_00000001000000A100000019 with LSN a6b4000028. 
	INFO: 2019/08/08 23:00:07.590598 Walking ...
	DEBUG: 2019/08/08 23:00:07.591162 
	INFO: 2019/08/08 23:00:07.591222 Starting part 1 ...
	DEBUG: 2019/08/08 23:00:07.591382 Put base_00000001000000B10000003B_D_00000001000000A6000000B4/tar_partitions/part_001.tar.lz4 into basebackups_005/
	DEBUG: 2019/08/08 23:00:07.858526 /PG_VERSION
	DEBUG: 2019/08/08 23:00:07.861481 /base
	DEBUG: 2019/08/08 23:01:07.127011 /postgresql.auto.conf
	INFO: 2019/08/08 23:01:07.131685 Finished writing part 1.
	INFO: 2019/08/08 23:01:07.820461 Starting part 2 ...
	INFO: 2019/08/08 23:01:08.000675 Finished writing part 2.
	INFO: 2019/08/09 23:00:06.264486 Delta backup from base_00000001000000A6000000B4_D_00000001000000A100000019 with LSN a6b4000028. 
	INFO: 2019/08/09 23:00:06.692984 Walking ...
	DEBUG: 2019/08/09 23:00:06.693462 
	INFO: 2019/08/09 23:00:06.693511 Starting part 1 ...
	DEBUG: 2019/08/09 23:00:06.693641 Put base_00000001000000B6000000DD_D_00000001000000A6000000B4/tar_partitions/part_001.tar.lz4 into basebackups_005/
	DEBUG: 2019/08/09 23:00:06.771769 /PG_VERSION
	DEBUG: 2019/08/09 23:00:06.774302 /base
	DEBUG: 2019/08/09 23:01:28.125702 /postgresql.auto.conf
	INFO: 2019/08/09 23:01:28.144208 Finished writing part 1.
	INFO: 2019/08/09 23:01:28.559894 Starting part 2 ...
	INFO: 2019/08/09 23:01:28.724023 Finished writing part 2.
	ERROR: 2019/08/10 06:07:04.073613 EOF
	QueryRunner StopBackup: stop backup failed
	github.com/wal-g/wal-g/internal.(*PgQueryRunner).StopBackup
		/home/travis/gopath/src/github.com/wal-g/wal-g/internal/queryRunner.go:141
	github.com/wal-g/wal-g/internal.(*Bundle).UploadLabelFiles
		/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:406
	github.com/wal-g/wal-g/internal.HandleBackupPush
		/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:147
	github.com/wal-g/wal-g/cmd.glob..func3
		/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/backup_push.go:22
	github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute
		/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766

To my understanding, the `pg_stop_backup` could not complete due to that "pending/stuck" wal file archiving.

---

Lastly, as a solution, I simply restarted my postgresql service, which resumed (or restarted) that hanging wal backup, as if nothing happened. Postgres then deleted the unneeded wal files, my hard drive space came back to normal, and my apps/db stuff resumed to normal.

**Comment by x4m** [comment]
Uh.. To restart archive command you can just pkill wal-g, restarting DB is a serious business. I think your problem is related to #266 
The most important thing, in this case, is wal-push stack traces

**Comment by x4m** [comment]
Are you using 0.2.10 ?

**Comment by benjamin-thomas** [comment]
I'm running:

    wal-g version v0.2.9    5bf0fcf 2019.04.22_06:20:09

Yes killing wal-g sounds smarter, thanks for insisting on it. Although I don't think it was running at the time since the db got shutdown, and was the parent process.

#266 is very helpful, I'll go with the timeout command approach.

I'm not convinced something is wrong with wal-g "per se", as I did encounter some other timeout issue with another program on the same backend.

If some cloud backends do indeed hang "by design", then until some reasonable global timeout is available or configurable, maybe that coreutils timeout trick this should be documented?

**Comment by benjamin-thomas** [comment]
Old
