### ISSUE TITLE
Warn user if backup-push is invoked for non-compatible PostgreSQL

### ISSUE THREAD

**Issue by nicodimi** [wal-g/wal-g#364]
Hi,

after upgrade to the new pre-release version v.0.2.10a because of the issue with deleting old backups #319, I got the following issue while executing our postgres_backup script in order to delete the old backupy after X days and to create a new base backup.

`2019-08-05 05:02:29.436 - /postgres_backup.sh - producing a new backup
INFO: 2019/08/05 05:02:29.454910 Doing full backup.
INFO: 2019/08/05 05:02:29.474682 Calling pg_start_backup()
INFO: 2019/08/05 05:02:29.607743 Walking ...
WARNING: 2019/08/05 05:02:29.607829 15  deleted during filepath walk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124a74b]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc0001cafd0, 0x15c70a1, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:367 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000d5900, 0x7ffd2e8c9ef3, 0x2, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:146 +0x672
github.com/wal-g/wal-g/cmd/pg.glob..func3(0x2192060, 0xc00016db70, 0x1, 0x1)
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:26 +0x66
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x2192060, 0xc00016db40, 0x1, 0x1, 0x2192060, 0xc00016db40)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x21929e0, 0x1, 0x2191ba0, 0xc0002ddf78)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x21929e0, 0x8f37a0, 0xc0000440b8)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20`

**Comment by x4m** [comment]
Yeah, we should check that what you backup is PostgreSQL before doing work...

**Comment by x4m** [comment]
WAL-G should:
1. Refuse to do backup-push of the folder without base/pg_contol file
2. Refuse to do backup-push without PGVERSION
3. Warn user, if PGVERSION contain something except 9.5,9.6,10,11 or *devel (do not warn devs - they are free to shout at their feet)

The test should try backup-push of the empty folder and fail.

@munakoiso can you please look into this if you will have some spare time?

**Comment by nicodimi** [comment]
Hi,
I've closed the issue. This was a mistake from our side regarding the configuration.
WAL-G is working correctly for deleting old backups.
