### ISSUE TITLE
recipe for target 'deps' failed message when building for Postgres

### ISSUE THREAD

**Issue by thijslemmens** [wal-g/wal-g#371]
I'm following the instructions to build the wal-g binary on this page:
https://github.com/wal-g/wal-g/blob/master/PostgreSQL.md#installing

However when I get to the `make deps` part, I get:

```
thijs@havana ~/go/src/github.com/wal-g/wal-g (master) $ make deps
git submodule update --init
dep ensure
make: dep: Command not found
Makefile:117: recipe for target 'deps' failed
make: *** [deps] Error 127
```

I'm new to building GO projects, so I'm probably missing some implicit information.

**Comment by g0djan** [comment]
Yeah, you should install dep firstly :) Did you execute first steps of Install section of readme?
If it doesn't help you should check where you install binary of dep and it is possible to find this binary in the PATH variable.

**Comment by thijslemmens** [comment]
@g0djan Thanks, that got me past that step.
