### ISSUE TITLE
backup-list switches are missing + bad version returned on v0.2.11

### ISSUE THREAD

**Issue by benjamin-thomas** [wal-g/wal-g#381]
Version=`wal-g version v0.2.9    5bf0fcf 2019.04.22_06:20:09`, and `v0.2.11` release

---

`wal-g backup-list --json`

Returns `unknown flag: --json`

Am I missing something obvious??

---

Also something is wrong with the `v0.2.11` release.

`/wal-g --version` returns:

    wal-g version devel     devel   devel   PostgreSQL

**Comment by munakoiso** [comment]
Hi!
--version now is fixed. 
You can check out v0.2.13

**Comment by Denchick** [comment]
Hi, @benjamin-thomas! I tried to reproduce your problem with `backup-list --json` but for me, all works fine.
I ran wal-g with `--json` option and without, with few backups and none. Please, could you give me additional information about your problem? Is it indeed still actual?

**Comment by benjamin-thomas** [comment]
@Denchick, the `--json` switch works fine with `v0.2.13` so I'm closing this issue.

It seems something was wrong with that badly versioned release.
