### ISSUE TITLE
Surprising UX followed by panic

### ISSUE THREAD

**Issue by ocharles** [wal-g/wal-g#39]
I have just added wal-g to one of my machines, but I don't entirely understand how to use it. Here is a transcript from a first time user:

```
[root@hydra:~]# wal-g
Please choose a command:
  backup-fetch  fetch a backup from S3
  backup-push   starts and uploads a finished backup to S3
  wal-fetch     fetch a WAL file from S3
  wal-push      upload a WAL file to S3

[root@hydra:~]# wal-g backup-push
Please choose a command:
  backup-fetch  fetch a backup from S3
  backup-push   starts and uploads a finished backup to S3
  wal-fetch     fetch a WAL file from S3
  wal-push      upload a WAL file to S3

[root@hydra:~]# wal-g backup-push --help
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/wal-g/wal-g.Configure(0x10, 0xc42016e540, 0x0, 0x18)
        /tmp/nix-build-wal-g-0.1.2.drv-0/go/src/github.com/wal-g/wal-g/upload.go:77 +0xa6e
main.main()
        /tmp/nix-build-wal-g-0.1.2.drv-0/go/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:83 +0x1f6
```

I didn't expect the second command (`wal-g backup-push`) to work, but I did expect it to inform me about the path. It didn't, so I called with `--help` which caused some kind of panic and crash.

**Comment by x4m** [comment]
Hi Oliver! Embedded docs and code for arg parsing - these places need improvement. I do not want to accumulate too much of tech debt here.
I'm planning to work on them, but help would be welcome. If you have some spare time, I can explain what exactly, but ISTM that you observe this problem.

**Comment by x4m** [comment]
And about how to use.
First, you need to setup WAL archiving commands. Backups are useless without archived WALs during the time of backup.
Then you can backup-push, the second arg is PGDATA directory. But there must be env vars which are important too: they describe how to connect to PostgreSQL and where to place backups.

When you have backups and WAL archive - it's time to have a disaster, cause WAL-G is disaster recovery tool.

You do backup-fetch, then setup restore command to pull WALs, start Postgres and it will recover itself from disaster.

This all is a bit simplified description.

**Comment by ocharles** [comment]
Right, that's the same process as WAL-E I think - I already have that working fine. I'm a little surprised about the panic above though - I also get that if I try and use wal-g to back up my `/var/db/postgresql/ directory.

**Comment by x4m** [comment]
@ocharles , could you please provide call stack or other details of failure when you call wal-g with PGDATA as argument after backup-push and proper pg env vars setted?

**Comment by ocharles** [comment]
Do I have to do anything beyond running wal-g to generate a call stack?

**Comment by x4m** [comment]
console output should be enough

**Comment by ocharles** [comment]
I'm no longer trying to use wal-g, so I'll close this.
