### ISSUE TITLE
backup delete removes max only 1000 WALs on Ceph

### ISSUE THREAD

**Issue by chobostar** [wal-g/wal-g#392]
known affected Ceph versions - 12, 13.

WAL-G uses `ListObjectsV2Pages`:
https://github.com/wal-g/wal-g/blob/v0.2.11/internal/storages/s3/folder.go#L158

but Ceph doesn't support it:
https://tracker.ceph.com/issues/37801

by default it's limited to 1000:
```
rgw list buckets max chunk

Description: | The maximum number of buckets to retrieve in a single operation when listing user buckets.
-- | --
Integer
1000
```
https://docs.ceph.com/docs/luminous/radosgw/config-ref/

is where any suppose to support old listobjects in WAL-G?

**Comment by x4m** [comment]
Hi! Thanks for reporting!

Options:
0. Fix Ceph. It's opensource, right?
1. Use V1 - will it help? We can create alternative storage calling ListObjects() or setting that uses ListObject
2. Retry ```wal-g delete``` several times. It's ugly...

**Comment by chobostar** [comment]
0. Right, they doing the best: https://github.com/ceph/ceph/pull/29849

1. With this diff it's look like working
```
diff --git a/internal/storages/s3/folder.go b/internal/storages/s3/folder.go
index a14c49c..5dfacce 100644
--- a/internal/storages/s3/folder.go
+++ b/internal/storages/s3/folder.go
@@ -149,13 +149,13 @@ func (folder *Folder) GetPath() string {
 }
 
 func (folder *Folder) ListFolder() (objects []storage.Object, subFolders []storage.Folder, err error) {
-       s3Objects := &s3.ListObjectsV2Input{
+       s3Objects := &s3.ListObjectsInput{
                Bucket:    folder.Bucket,
                Prefix:    aws.String(folder.Path),
                Delimiter: aws.String("/"),
        }
 
-       err = folder.S3API.ListObjectsV2Pages(s3Objects, func(files *s3.ListObjectsV2Output, lastPage bool) bool {
+       err = folder.S3API.ListObjectsPages(s3Objects, func(files *s3.ListObjectsOutput, lastPage bool) bool {
                for _, prefix := range files.CommonPrefixes {
                        subFolders = append(subFolders, NewFolder(folder.uploader, folder.S3API, *folder.Bucket, *prefix.Prefix))
                }
```
but i'm not sure about correct binary build

2. Yes it's possible, retry `wal-g delete` until it's no effect, but not for all cases.

Thanks for response.
