### ISSUE TITLE
WAL prefetch

### ISSUE THREAD

**Issue by x4m** [wal-g/wal-g#40]
@fdr , I'll create an issue here to keep the discussion on implementation details open.

# Brief description
I'm working now on WAL-prefetch feature. Postgres asks WAL-fetch command only when it has nothing else to do. This is not very performant design, we can download WALs that probably will be needed when Postgres is busy with a replay of what's in hand already.

# Details
In the email conversation, @fdr stated that we should prefetch 8 files ahead of what was asked by Postgres.

I have few more questions:
1. Should we trigger prefetch after fetch, or start prefetch along with fetch? I propose triggering prefetch just before returning.
2. Current `wal-fetch` command before the start is doing the following:
  a. Check if there is .lzo from WAL-E
  b. Check if there is .lz4 from WAL-G
  c. Start downloading whatever is there
 I propose changing this behavior towards more optimistic path:
  a. Start downloading .lz4
  b. If failed - start downloading .lzo
  c. If failed - return failure

**Comment by fdr** [comment]
Some thoughts on fallback:

I suggest making a `.wal-g` directory that should be excluded from back-up. In it, you can store the last successful archival fetch-type, whether lzo or lz4. Try that one first.

The number of "misses" will be minimal.

As seen in WAL-E's `.wal-e` directory, careful management of that directory to ensure it does not blow up in size due to bugs is the main care required here. Other than that, it provides a lot of design flexibility in making features adaptive and not complex to configure.

**Comment by x4m** [comment]
How do you think, should we delete prefetched files from old runs?
Normally they should not occur, but I see scenario when they can appear:
Network is gone for 50ms, wal-fetch does not see any progress and ignores prefetch. 

If Postgres asks for WAL X, we can safely drop prefetches like X-1?

**Comment by fdr** [comment]
On Wed, Nov 22, 2017 at 9:46 AM Andrey Borodin <notifications@github.com>
wrote:

> How do you think, should we delete prefetched files from old runs?
> Normally they should not occur, but I see scenario when they can appear:
> Network is gone for 50ms, wal-fetch does not see any progress and ignores
> prefetch.
>
> If Postgres asks for WAL X, we can safely drop prefetches like X-1?
>

That's what WAL-E does. If memory serves, it also has some logic to empty
the directory on a timeline mis-prediction.

**Comment by x4m** [comment]
I've committed this feature. wal-fetch optimization is not done yet.
I'll be back to this later, currently I need to do more complex tests and rollout WAL-G on some servers.
