### ISSUE TITLE
basebackup_005 and wal_005

### ISSUE THREAD

**Issue by jnicholls** [wal-g/wal-g#42]
What is the reason for these folders being named as such?  Is there intention to have these folders actually be dynamically named based on part of the WAL prefix, in order to better organize the objects rather than dumping them all into the same logical location?  If yes, then I will rephrase this issue's title to suggest implementing this behavior.

**Comment by x4m** [comment]
005 does not stand there for timeline id (first 8 digits of WAL filename). In WAL-E this was the version of the backup format, AFAIK. In WAL-G currently, these digits are in string literals (but not for long, I hope).

**Comment by jnicholls** [comment]
Roger that, thanks.  I'll close this issue.  I thought for a moment it was a timeline id to add some organization to archive placement.  I have no experience with WAL-E so forgive my ignorance.

**Comment by x4m** [comment]
I believe every couple of eyes is important, your question is valuable. Thanks for asking, Jarred.
