### ISSUE TITLE
Prevent overwrite of .history file

### ISSUE THREAD

**Issue by x4m** [wal-g/wal-g#420]
By default, WAL-G does not turn on WAL overwrite prevention, since this check consumes resources and does not provide much stronger guarantees.

But this is incorrect for .history files: PostgreSQL algorithm to pick timeline relies on unoverwritable archive.
this can affect a PostgreSQL cluster with concurrent promote.

**Comment by serprex** [comment]
Do you have any reference to docs about this requirement?

Otherwise it seems like the fix would be straight forward:

```diff
diff --git a/internal/databases/postgres/wal_push_handler.go b/internal/databases/postgres/wal_push_handler.go
index f89da23c..b2cfd7b6 100644
--- a/internal/databases/postgres/wal_push_handler.go
+++ b/internal/databases/postgres/wal_push_handler.go
@@ -6,6 +6,7 @@ import (
        "io/ioutil"
        "os"
        "path/filepath"
+       "strings"

        "github.com/wal-g/wal-g/internal"

@@ -48,7 +49,7 @@ func HandleWALPush(uploader *WalUploader, walFilePath string) {
        tracelog.ErrorLogger.FatalOnError(err)

        totalBgUploadedLimit := viper.GetInt32(internal.TotalBgUploadedLimit)
-       preventWalOverwrite := viper.GetBool(internal.PreventWalOverwriteSetting)
+       preventWalOverwrite := viper.GetBool(internal.PreventWalOverwriteSetting) || strings.HasSuffix(walFilePath, ".history")
        readyRename := viper.GetBool(internal.PgReadyRename)

        bgUploader := NewBgUploader(walFilePath, int32(concurrency-1), totalBgUploadedLimit-1, uploader, preventWalOverwrite, readyRename)
```

**Comment by x4m** [comment]
@serprex looks correct. A comment, and probably a link to this Issue would be good. Can you plz send a Pull request with it?
It would be great to have a test also. https://github.com/wal-g/wal-g/blob/196c92016f2ffb11b261f2e152f35ab066cdd6fb/docker/pg_tests/scripts/tests/test_functions/test_full_backup.sh#L40

Many thanks!
