### ISSUE TITLE
S3 Object Listing Does Not Paginate

### ISSUE THREAD

**Issue by jnicholls** [wal-g/wal-g#44]
Calls such as `GetBackups` and `GetWals` do not paginate across S3's maximum object return list size of 1000.  These parts of the code base—especially the `GetWals` call—should be refactored to call `ListObjectsV2Pages` rather than `ListObjectsV2`.  The consequence of this today is that deleting old backups may only clear up to the oldest 1000 WAL segments, but none further.

**Comment by x4m** [comment]
Thanks! I've addressed this issue in commit c812f4a.
If you have some spare time, can I ask you to verify that fixes work for you?

**Comment by jnicholls** [comment]
Good to go!  Nice work.
