### ISSUE TITLE
Problems deleting (a lot of) backups

### ISSUE THREAD

**Issue by benzimmer** [wal-g/wal-g#440]
I realized yesterday I forgot to setup the delete cronjob for a server of ours which led to around 350 base backups being created in the meantime (amounting to around 17TB of data). I've been trying to remove them using

```
envdir /etc/wal-g.d/env /usr/local/bin/wal-g delete retain FULL 5 --confirm
```

The problem is that this seems to do nothing really to decrease the number of base backups. I've been running the command in a loop for a day now and it barely made a dent into the amount of data on S3.

The log output suggests that a bunch of archives are deleted, but somehow this seems very inefficient and not working as intended I guess. I would post the log, but it's 85MB, so not sure it will be of any help. Let me know.

Am I doing something wrong or is this how it's supposed to work?

Using v0.2.9 with AWS S3 as storage.

**Comment by x4m** [comment]
Hi! Thanks for the report!
To diagnose the problem we need logs with WALG_LOG_LEVEL=DEVEL
Plz send a log to x4mmm at yandex-team.ru or post it somewhere

**Comment by benzimmer** [comment]
Hi!

I have put a shortened version of the log here: https://gist.github.com/benzimmer/7b396e5f525f23e827a4472d5ae3b489

If you actually need the full log you can find it here: https://drive.google.com/file/d/1fYtEZeZt6JP0u1k8KbUTLMZC_tNkZXaj/view?usp=sharing

**Comment by x4m** [comment]
What storage do you use? S3?

**Comment by benzimmer** [comment]
Yes, S3.

**Comment by x4m** [comment]
From the log that you had posted - ISTM that everything should work just fine..
Can you please make a log with WALG_LOG_LEVEL=DEVEL? It seems like your log is done with regular log settings, while in devel log level there will be more debug information...

**Comment by benzimmer** [comment]
Here you go: https://drive.google.com/file/d/14YBdUCPxy-L7Fzwemoj1pBDunFfEjkKy/view?usp=sharing

Created with `WALG_LOG_LEVEL=DEVEL envdir /etc/wal-g.d/env /usr/local/bin/wal-g delete retain FULL 5 --confirm &>> delete.log`

**Comment by x4m** [comment]
Sorry for the delay...
Yes, I've checked the log, but cannot understand what is the problem.
There are two problems:
1. WAL-G is issuing delete commands, I do not understand why S3 objects survive
2. There is still regular log level, not verbose (devel)... maybe try to add WALG_LOG_LEVEL file to 
/etc/wal-g.d/env ?

**Comment by benzimmer** [comment]
It does not produce any (noticable) debug output no matter how I define WALG_LOG_LEVEL unfortunately.

However, I think I found the problem between chair and keyboard. The user policy for the S3 user did not include the permission to delete objects... Question is why wal-g did not complain when trying to delete. Here is the policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::db-backups"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Resource": "arn:aws:s3:::db-backups/*"
        }
    ]
}
```

Adding `"s3:DeleteObject"` to the second statement seems to have done the trick.

**Comment by x4m** [comment]
Looks like it's error handling bug, but I've checked code and do not see problem there...seems like we need a better investigation on our side...
