### ISSUE TITLE
Backup folder is not properly deleted during a delete operation

### ISSUE THREAD

**Issue by jnicholls** [wal-g/wal-g#45]
When deleting a backup, the backup's folder is specified as the object key name, which is not an actual object and therefore will not match nor delete any objects.

https://github.com/wal-g/wal-g/blob/master/commands.go#L175

This implementation must be refactored to first query the objects located under that backup folder, and then pass those object identifiers to the delete function.

**Comment by x4m** [comment]
Hi! Thank you for reporting this. I've pushed fix. Testing will be highly appreciated.

**Comment by jnicholls** [comment]
Heck yeah!  Good to go.  Thanks.
