### ISSUE TITLE
/bin/ld: cannot find -llzo2 on make pg_build

### ISSUE THREAD

**Issue by p-arse** [wal-g/wal-g#453]
Hello!
Trying to build on Centos7.5 and
I get this output on step **make pg_build**:
```
(cd main/pg && go build -tags "brotli lzo" -o wal-g -ldflags "-s -w -X github.com/wal-g/wal-g/cmd/pg.BuildDate=`date -u +%Y.%m.%d_%H:%M:%S` -X github.com/wal-g/wal-g/cmd/pg.GitRevision=`git rev-parse --short HEAD` -X github.com/wal-g/wal-g/cmd/pg.WalgVersion=`git tag -l --points-at HEAD`")
# github.com/wal-g/wal-g/vendor/github.com/cyberdelia/lzo
/bin/ld: cannot find -llzo2
collect2: error: ld returned 1 exit status
make: *** [pg_build] Error 2
```

I have lzo-devel v. 2.06 installed, checked /usr/lib64 for library files:
``` 
# ls -l /usr/lib64 | grep lzo
liblzo2.so
liblzo2.so.2
liblzo2.so.2.0.0
libminilzo.so
libminilzo.so.0 
```
Tried to add config file to /etc/ld.so.conf.d/ and export LD_LIBRARY_PATH=/usr/lib64 with no effect

How do I make **go build** see lzo2 library?

**Comment by x4m** [comment]
Thanks for the report @p-arse !
Currently, I do not know how to help.. maybe just remove lzo compressor everywhere in your code?

I'm considering the following approach:
compression is extra bytes in wal-g, let's hide all compressors behind gotags for those who build from sources and only install them to those who download the binary from github?

**Comment by p-arse** [comment]
@x4m Thanks for your answer! I removed tag "lzo" from pg_build command in Makefile and got build without errors. 
I will check usability of this build in few days.

**Comment by x4m** [comment]
keep in mind that without lzo your build is not wal-e compatible

**Comment by p-arse** [comment]
Since I don't need wal-e compatibility, build without lzo tag worked fine for me. Thanks!

**Comment by munakoiso** [comment]
@p-arse Now can you try to build wall-g with lzo tag?

**Comment by g0djan** [comment]
Fixed with https://github.com/wal-g/wal-g/commit/d0b3f0b569996518c8632bee03c6a7b03df1edc2
