### ISSUE TITLE
WAL-G doesn't see WAL-E archives in GCS

### ISSUE THREAD

**Issue by NikolayS** [wal-g/wal-g#469]
In GCS, WAL-E adds an additional slash (see https://github.com/wal-e/wal-e/issues/411), for example:
```
gs://mybucket//pitr-wale-v1
             ^^_____________________ should be a single slash?
```

WAL-G's `backup-list` doesn't see this backup when such string is provided in `WALG_GS_PREFIX`, reporting just a simple message: `No backups found.`, even when working with `WALG_LOG_LEVEL=DEVEL`.

I assume that this may be related to:
- WAL-E behavior (additional slash),
- WAL-G's `TrimPrefix` in multiple places.

**As a result, on GCS we cannot use WAL-G to work with WAL-E archives.**

Additionally, it would be great if WAL-G reported more information here, at least in `WALG_LOG_LEVEL=DEVEL` mode. It would be good to have more diagnostics such was:
- which buckets/folders where scanned,
- are we dealing with just empty folders, or the folder (or the bucket specified in `WALG_GS_PREFIX`) does not exist at all – in this case it should be something more sound, maybe an error.

**Comment by NikolayS** [comment]
See also: https://github.com/wal-g/wal-g/issues/454.  There @Andrey-Salnikov describes issues of using `wal-g wal-fetch` against an archive created by WAL-E on S3 (in this issue, I described problems of using `backup-list` and `backup-fetch` on GCS).

It also mentioned there, that the older versions of WAL-G worked well with WAL-E archives. Unfortunately, I cannot check it for GCS since its support didn't exist in version 0.1.10.

**Comment by x4m** [comment]
Hi! I think everything here is fixed, right?

**Comment by NikolayS** [comment]
Yes @x4m, works like a charm! Thank you.
