### ISSUE TITLE
Deletion Failures

### ISSUE THREAD

**Issue by jnicholls** [wal-g/wal-g#47]
Seeing errors such as this when deleting a large backlog of WALs (this is the first time I've tested multi-page WAL deletion, i.e. more than 1000 objects):

```
2017/12/05 22:32:45 Unable to delete WALS before base_000000010000006A00000073MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
	status code: 400, request id: E783694080458AC0, host id: p7AI/ZTMbb9aeRdsouupEC0ziU4w6Gy2H3AK6EWdJbpwo8tFnabJr81OGfbaf1frDUbvdgYYqog=
```

**Comment by x4m** [comment]
Now works for me. Thanks for reporting! 
Generating WAL was a bit tedious
`for i in $(seq 1 1001); do psql -c "update x set i = i+1;select pg_switch_xlog();"; done`

**Comment by x4m** [comment]
I do not observe these problems now. Thus I'ss close the issue. Feel free to open issue on any sight of problems with WAL-G.
