### ISSUE TITLE
Problem with restoring to ISCSI device

### ISSUE THREAD

**Issue by Mynom** [wal-g/wal-g#477]
Hi,
I am experiencing the following problem. When restoring to a filesystem located on an ISCSI device. I get the following errors. The same backup can be restored without problems on a local disk or NFS storage.

```
INFO: 2019/11/22 09:53:24.626197 Finished decompression of part_002.tar.lz4
ERROR: 2019/11/22 09:53:24.626266 part_002.tar.lz4 DecryptAndDecompressTar: lz4 decompress failed. Is archive encrypted?: DecompressLz4: lz4 write failed: read tcp 172.21.131.24:53006->172.19.46.100:443:
read: connection reset by peer
INFO: 2019/11/22 09:53:24.626572 Finished extraction of part_002.tar.lz4
ERROR: 2019/11/22 09:53:24.626609 Extraction error in part_002.tar.lz4: extractOne: Interpret failed: Interpret: copy failed: unexpected EOF
```

Everything else works without a problem on the ISCSI device. The Database is running on it, I can do backups. Only some archives cannot be restored. 

Environment:

Centos 7.7
Kernel Versions tested: 3.10 up to 5.3.1
WAL-G versions for restore tested: 0.1.17 up to 0.2.13.

Storage Interface is 10Gbit.
Process has enough ram and cpu (tried with 16 GiG and 4 CPUs).

I tried using WALG_DOWNLOAD_CONCURRENCY="1", WALG_DISK_RATE_LIMIT="1000000", LZMA, LZ4 and brotli.

Does anyone have an idea on how to debug this further?

**Comment by x4m** [comment]
Hi! Looks like a network problem?
```read tcp 172.21.131.24:53006->172.19.46.100:443:```

**Comment by Mynom** [comment]
You are right. There is some kind of strange interaction with ISCSI and S3.
