### ISSUE TITLE
Fails when deleting basebackup

### ISSUE THREAD

**Issue by OlleLarsson** [wal-g/wal-g#480]
Hi, I am encountering a problem when i try to remove a basebackup using wal-g.

When I execute `envdir etc/wal-g/env/ wal-g delete before FIND_FULL base_000000010000000000000003 --confirm`

I get the following error message 

```
INFO: 2019/11/28 13:54:04.532622 Start delete
INFO: 2019/11/28 13:54:04.532657 retrieving permanent objects
INFO: 2019/11/28 13:54:04.580127 Objects in folder:
INFO: 2019/11/28 13:54:04.580210        skipped: basebackups_005/base_000000010000000000000003_backup_stop_sentinel.json
INFO: 2019/11/28 13:54:04.580232        will be deleted: wal_005/000000010000000000000001.lz4
INFO: 2019/11/28 13:54:04.580250        will be deleted: wal_005/000000010000000000000002.lz4
INFO: 2019/11/28 13:54:04.580270        skipped: wal_005/000000010000000000000003.00000028.backup.lz4
INFO: 2019/11/28 13:54:04.580283        skipped: wal_005/000000010000000000000003.lz4
INFO: 2019/11/28 13:54:04.580302        skipped: basebackups_005/base_000000010000000000000003/metadata.json
INFO: 2019/11/28 13:54:04.580322        skipped: basebackups_005/base_000000010000000000000003/tar_partitions/part_001.tar.lz4
INFO: 2019/11/28 13:54:04.580343        skipped: basebackups_005/base_000000010000000000000003/tar_partitions/part_003.tar.lz4
INFO: 2019/11/28 13:54:04.580366        skipped: basebackups_005/base_000000010000000000000003/tar_partitions/pg_control.tar.lz4
ERROR: 2019/11/28 13:54:04.582212 failed to delete s3 object: '[wal_005/000000010000000000000001.lz4 wal_005/000000010000000000000002.lz4]': NotImplemented:
        status code: 501, request id: tx000000000000000219e5a-005ddfd17c-12de1d43-default, host id:
```

It appears as if the S3 service does not implement a operation that wal-g uses (correct me if I'm wrong). 

I am using version `v0.2.13` of wal-g. 
Any help at all is much appreciated :)

**Edit:** I tried using wal-g against another S3 service and it worked. Still interested to know what functionality is missing that causes wal-g not being able to remove objects from S3. Gonna revert back to using wal-e as that seems to work against any S3 service that I have tried so far.

**Comment by x4m** [comment]
@OlleLarsson sorry I missed this issue.
In S3 we call DeleteObjects method. I'm not sure how can we delete objects without calling it. Are there any replacements in S3 API?

**Comment by x4m** [comment]
Oh, I see....we issue DeleteObject**s**, but we can issue ListObjectsV2 and many DeleteObject...

**Comment by x4m** [comment]
If you have some spare time you can handle it here
https://github.com/wal-g/storages/blob/master/s3/folder.go#L195
test error for not implemented and try deleting object one by one.
