### ISSUE TITLE
INFO and WARNING and DEBUG logs are being written in os.Stderr

### ISSUE THREAD

**Issue by Sarankrishna** [wal-g/wal-g#483]
I see now https://github.com/Tinsane library is used for logging. After version v0.1.17 we are getting INFO,WARNNING, DEBUG logs also as error because of the below code in logging liberary logging.go file

var InfoLogger = NewErrorLogger(os.Stderr, "INFO: ")
var WarningLogger = NewErrorLogger(os.Stderr, "WARNING: ")
var ErrorLogger = NewErrorLogger(os.Stderr, "ERROR: ")
var DebugLogger = NewErrorLogger(ioutil.Discard, "DEBUG: ")

Notice that every logger in attached to os.Stderr , But we need to only attach the Errorlogger os.Stderror and others to os.Stdout.

Since i am calling wal-g backup-fatch from python code ,even though backup-fetch is successful  and stderror buffer is having result INFO AND warnning logs, my main code is failed with error. 

Can you get this issue fixed in https://github.com/Tinsane ?

**Comment by x4m** [comment]
Your proposal seems to make sense. We can ask @Tinsane what does he think on this.

But I also have a few questions. Why do you call WAL-G from Python? Maybe we should implement your program inside WAL-G so that it would not need an external runner?

Also, it's not Python in control, it is your program. Certainly, you can tell Python when to fail and when to ignore stderr.

**Comment by Sarankrishna** [comment]
Hi @x4m 

We build point in recovery tool in python using wal-g.  Our point in recovery tool is a orchestrator which create recovery job and schedule it in  for recovery and do automatic test of whether wal-g  PITR recovery is successfull or not using the content of the database table.

As you said i have a control in ,my code but WAL-G tool is returning INFO, DEBUG,WARINGS logs as error. It was working fine in v 0.1.17 as tracelogger was not used in those version i guess.

below is my sample code here i call wal-g in python code


    command = ['/usr/bin/wal-g backup-fetch LASTEST' ]

    proc = subprocess.Popen(command, shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = proc.communicate()

    if stderr:
        raise RestoreException(stderr)
`
`

**Comment by g0djan** [comment]
Fixed
