### ISSUE TITLE
Delete command does not work with flag --after

### ISSUE THREAD

**Issue by CritPower** [wal-g/wal-g#514]
I used example from documentation.

Command: wal-g delete retain 5 --after 2019-12-12T12:12:12H

Output: Error: unknown flag: --after

wal-g version v0.2.14   d372cbd 2019.12.04_06:14:06     PostgreSQL

**Comment by x4m** [comment]
Hi! Well, this feature is implemented in master, but still did not make its way into prerelease.
But it will work as expected in the next release cycle.
