### ISSUE TITLE
stuck process

### ISSUE THREAD

**Issue by AdmiralUA** [wal-g/wal-g#515]
Hi wal-g community!

Today we got the `pg_stop_backup` process that stuck, which was called by `wal-g`.
```
SELECT labelfile, spcmapfile, lsn FROM pg_stop_backup(false)
```

In wal-g logs we got:
```
INFO: 2019/12/25 01:00:01.357461 Doing full backup.
INFO: 2019/12/25 01:00:01.409599 Calling pg_start_backup()
INFO: 2019/12/25 01:00:01.850813 Walking ...
INFO: 2019/12/25 01:00:01.851080 Starting part 1 ...
INFO: 2019/12/25 01:00:10.747870 Finished writing part 1.
INFO: 2019/12/25 01:00:10.747904 Starting part 2 ...
INFO: 2019/12/25 01:00:19.568321 Finished writing part 2.
INFO: 2019/12/25 01:00:19.568385 Starting part 3 ...
....
INFO: 2019/12/25 01:53:38.717927 Finished writing part 397.
INFO: 2019/12/25 01:53:38.717976 Starting part 398 ...
INFO: 2019/12/25 01:53:43.096007 Finished writing part 398.
INFO: 2019/12/25 01:53:44.118330 Starting part 399 ...
INFO: 2019/12/25 01:53:44.118397 /global/pg_control
INFO: 2019/12/25 01:53:44.123919 Finished writing part 399.
INFO: 2019/12/25 01:53:44.125230 Calling pg_stop_backup()
```
`wal-g backup-list` didn't show this backup

We used `strace` to check what this process did and got:
```
stat("pg_xlog/archive_status/0000000200006885000000DC.done", 0x7ffe44e1d430) = -1 ENOENT (No such file or directory)
stat("pg_xlog/archive_status/0000000200006885000000DC.ready", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
stat("pg_xlog/archive_status/0000000200006885000000DC.done", 0x7ffe44e1d430) = -1 ENOENT (No such file or directory)
stat("pg_xlog/archive_status/0000000200006885000000DC.ready", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
```
`strace` spams this message every second.

There is only `0000000200006885000000DC.ready` in our archive_status directory, but not `0000000200006885000000DC.done`. Why didn't wal-g create it? How can we prevent similar cases in the future?

When we canceled postgres backend process, we got:
```
ERROR: 2019/12/25 17:11:40.019406 UploadLabelFiles: failed to stop backup: QueryRunner StopBackup: stop backup failed: ERROR: canceling statement due to user request (SQLSTATE 57014)
```

-------
wal-g version v0.2.14   d372cbd 2019.12.04_06:14:06     PostgreSQL
psql (PostgreSQL) 9.6.3
Ubuntu 16.04.2 LTS

**Comment by x4m** [comment]
Hi! Thanks for the report!
Please inspect pg_log for more information. I suspect that you are doing backup from standby with no WAL activity and backup simply waits for WAL segment completition. BTW @HeikoOnnebrink was raising this topic recently. #511

**Comment by AdmiralUA** [comment]
Hi x4m!
Thanks for fast response!

We already used wal-g for a long time before this problem, and everything worked fine.
Yesterday we tried to make a backup from the master with great activity. In the logs, we see updates after backup hangs. Today it repeated again: wal-g did not create the .done file and pg_stop_backup was stuck at the end of the backup process.

**Comment by x4m** [comment]
But WAL-G does not create .done files at all, it only polls its existence. These files are created by postgresql

**Comment by AdmiralUA** [comment]
I'm closing issue. It was a "wal-push" process hanging during archiving_command. That caused pg_stop_backup to wait until archiving_command finishing it's work.
