### ISSUE TITLE
Check archive_mode = off

### ISSUE THREAD

**Issue by patsevanton** [wal-g/wal-g#544]
If archive_mode = off, wal-g don`t show error and don`t push full backup.
May be wal-g check archive_mode = off ?

**Comment by x4m** [comment]
Hi! Thanks for reporting!

There is a code for this, I belive WAL-G must emmit warning
https://github.com/wal-g/wal-g/blob/82ef12e15977f95179c375f3a7d9463328e50169/internal/connect.go#L45-L58

**Comment by patsevanton** [comment]
Ok
