### ISSUE TITLE
Don't know how to configure AES256 SSE-C

### ISSUE THREAD

**Issue by koehn** [wal-g/wal-g#546]
First of all, thanks for making such a useful utility! Now, on to my issue. 

I'm trying to configure SSE-C to backup postgresql to Minio, and I'm having trouble getting the configuration to work. If I set `WALG_S3_SSE=AES256`, I get the error:
```
InvalidArgument: Server side encryption specified but KMS is not configured
```

I know I need to configure the AES key, but how do I do that? The docs reference `WALG_S3_SSE_KMS_ID`, but AFAIK that won't work with minio, which uses customer-provided keys (SSE-C). There's no reference I can find to setting the AES key, and I can't find anything in the source, either. 

Barring that, can I set up CSE with WAL-G and Minio? I think that might be even better. Also, I can see some stuff in the source about PGP, but there's no mention in the documentation about it.

**Comment by x4m** [comment]
Hi! Thanks for the questions.
AFAIR, @bn0ir is a well-known expert on KMS. Alexander, can you please help with this?

**Comment by bn0ir** [comment]
Hello!

WAL-G does not support SSE-C for now.
There are two options to encrypt files:

- Configure Minio KMS with Hashicorp Vault instance or set static master key via env var `MINIO_KMS_MASTER_KEY` — [Minio docs](https://docs.min.io/docs/minio-kms-quickstart-guide.html)

- Use WAL-G client side PGP based encryption (env var `WALG_PGP_KEY`) — [WAL-G docs](https://github.com/wal-g/wal-g/blob/master/PostgreSQL.md)

**Comment by koehn** [comment]
OK, that's really good to know. Thanks so much!

**Comment by x4m** [comment]
I'll close this for now. Feel free to reopen or create new issue if you have more questions.
