### ISSUE TITLE
Q: is "wal-g backup-list --json" order deterministic?

### ISSUE THREAD

**Issue by kmoppel** [wal-g/wal-g#553]
It looks like it...but a bit weird is that the default text output shows oldest backups first and the json format array has newest first. Thanks!

**Comment by x4m** [comment]
Hi! As far as I see there is sorting in code 
https://github.com/wal-g/wal-g/blob/e10b2bbd56ef20533c588b1164f340cc31aa6a3e/internal/delete_handler.go#L78
backups are sorted by time. If time obtained from storage system is deterministic - backup-list is deterministic.

**Comment by x4m** [comment]
BTW, I totally forgot to answer part of a question.
Text output is designed to be maximally compatible with WAL-E
JSON functions take list from the source that is responsible for resolving LATEST backup.
