### ISSUE TITLE
On which machine we should install wal-g?

### ISSUE THREAD

**Issue by Tekchanddagar** [wal-g/wal-g#580]
Hello Team,

We are using postgresql version 12.1. Currently we have high availability and automatic failover using patroni and its working fine.

Now we are planning for Disaster recovery and we are planning to use WAL-G for this.

We read some article to know that on which machine we should install WAL-G master,slave or both? But couldn't get clear idea.

Can you please help us to know which machine should use for WAL-G?

Any help will be appriciated.

Thanks.

**Comment by Penagwin** [comment]
I'd like to know as well, currently we're trying it on both

**Comment by Tekchanddagar** [comment]
Hello Team,

Can you please help me on above question?

Thanks.

**Comment by x4m** [comment]
Hi!
In minimal installation WAL-G can be installed only on primary.
You have to setup 2 things:
1. WAL archiving. define archive_command in PostgreSQL settings. This is preffered to run on primary.
2. Backup push. Define crond job which creates new backups and deletes old. Preffered to run on standby to reduce load, but you have to monitor that there is not big lag.

**Comment by Tekchanddagar** [comment]
@x4m, Thank you for your response. We completed our setup and set in similar way.

But you response will give more confidence now.

Thanks a lot for your helping hands.

**Comment by Tekchanddagar** [comment]
@Penagwin, hope so you also got the answer of your question.
Thanks.
