### ISSUE TITLE
Use pure Go implementation of zstd compress

### ISSUE THREAD

**Issue by tamalsaha** [wal-g/wal-g#586]
Currently wal-g uses a cgo based implementation. It might be better to use a pure Go implementation found here: https://github.com/klauspost/compress/tree/master/zstd

**Comment by patsevanton** [comment]
wal-g have brotli compression.
zstd compression comparable with brotli compression

**Comment by LeGEC** [comment]
Hello

I would be interested in opening a pull request for this feature.

Do you have a pro/cons arguments for this feature ?

The big pro I see is : portability and no Cgo dependency for that feature
