### ISSUE TITLE
AUR package added.

### ISSUE THREAD

**Issue by mijoharas** [wal-g/wal-g#590]
Hi, I added an AUR (arch user repository) package for wal-g (https://aur.archlinux.org/packages/wal-g/).

It's incredibly simple, it just downloads the release installs it, but allows everything to be tracked by my package manager for arch linux.

This is mainly an fyi, if you want to take ownership of the package or anything at any point, just let me know I'd be happy to transfer it.

Small request, can you add a checksum alongside the tarball for future releases? (It's required for packaging, I just downloaded the tarball and summed it myself to add to the package but it'd be better if people didn't have to trust me as well as you.)

**Comment by x4m** [comment]
Thanks @mijoharas !
Let's add checksum to releases here https://github.com/wal-g/wal-g/blob/master/.travis.yml#L135-L142 ?
Can you please send a PR with proper commands which you used to compute checksum?

**Comment by mijoharas** [comment]
Done! I don't know how to test this given it's on travisci and probably just run while making releases.

Thanks for your prompt response!

**Comment by x4m** [comment]
Cool, waiting for Travis here https://github.com/wal-g/wal-g/releases/tag/untagged-6aad31462be560501a68

Thanks!!

**Comment by x4m** [comment]
actually here https://github.com/wal-g/wal-g/releases/tag/v0.2.14a

**Comment by mijoharas** [comment]
Brilliant, thanks!
```
$ sha256sum --check wal-g.linux-amd64.tar.gz.sha256
wal-g.linux-amd64.tar.gz: OK
```
