### ISSUE TITLE
AWS_REGION should be optional

### ISSUE THREAD

**Issue by willglynn** [wal-g/wal-g#6]
Right now, the user has to specify `WALE_S3_PREFIX` and `AWS_REGION`. However, `WALE_S3_PREFIX` indicates an S3 bucket, S3 buckets have globally unique names, and the [`s3:GetBucketLocation` API](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetBucketLocation) can take a S3 bucket name and return its region. `AWS_REGION` should therefore be optional, with `wal-g` able to determine the bucket's region automatically.

**Comment by fdr** [comment]
Unfortunately, it's not optional in every region, and new regions will make it less and less optional, on account of SigV4. GetBucketLocation is not always granted via IAM and I'm not too keen to expend extra API round-trips for this.

**Comment by willglynn** [comment]
I didn't say `wal-g` should disregard `AWS_REGION`, I suggested it should fall back to calling `s3:GetBucketLocation` if `AWS_REGION` were unspecified. Paired with #5, this would allow `wal-g` to run knowing only `WALE_S3_PREFIX`, with implicit defaults functioning for all the other parameters.

Would you accept a PR to this effect?
