### ISSUE TITLE
prefetch failed

### ISSUE THREAD

**Issue by lesovsky** [wal-g/wal-g#60]
Hi,
I've restored a backup and during recovery, WAL segments are copied as usual but I also see messages `WAL-prefetch failed:  no such file or directory`. What is the cause?

recovery.conf 
```
standby_mode = 'on'
restore_command = '. /etc/wal-g/env && wal-g wal-fetch "%f" "%p"'
recovery_target = 'immediate'
```

**Comment by x4m** [comment]
Hi, Alexey! Thanks for reporting this!
Seems like WAL-G couldn't fork himself for WAL-prefetch.
By "fork" I mean just exec itself here
https://github.com/wal-g/wal-g/blob/master/prefetch.go#L82

This issue will not incur any problems with the restored cluster. But without prefetch restoration will be a bit slower. I'm looking into it.

**Comment by x4m** [comment]
Chances are you are exporting PATH in /etc/wal-g/env to cope with #59 and this PATH do not lead to WAL-G anymore?

**Comment by lesovsky** [comment]
I've set absolute path to wal-g in `restore_command` and it's become ok. Huh, I had to do that before write here )))

**Comment by x4m** [comment]
I still think it is a bug. I'm not inclined to address it ASAP, since there are a workaround and no easy fix. But eventually, this must be fixed.

**Comment by akindemirci** [comment]
We also ran into this issue. With these values, we cannot benefit from prefetch function:

```
archive_command = 'wal-g wal-push %p'
restore_command = 'wal-g wal-fetch %f %p'
```

We have to enter the absolute path for prefetch function to work, like this:
```
archive_command = 'wal-g wal-push %p'
restore_command = '/usr/local/bin/wal-g wal-fetch %f %p'
```

Thanks very much!
