### ISSUE TITLE
backup-push runtime error

### ISSUE THREAD

**Issue by benubois** [wal-g/wal-g#61]
Hi,

I'm getting the following error when attempting a backup-push. Any ideas on what might be wrong? Please let me know if I can provide any more information.

Thanks!

```
/usr/bin/envdir /etc/wal-g.d/writer /usr/local/bin/wal-g backup-push /var/lib/postgresql/9.2/main
BUCKET: database
SERVER: wal-g/db3-00:25:90:f5:33:aa
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/wal-g/wal-g.ParseLsn(0x0, 0x0, 0x3, 0x3, 0xc38620)
        /home/travis/gopath/src/github.com/wal-g/wal-g/timeline.go:29 +0x223
github.com/wal-g/wal-g.(*Bundle).StartBackup(0xc4201519e0, 0xc420012700, 0xc4201d6ed0, 0x26, 0x26, 0x433b2e, 0xc4200001a0, 0x200000003, 0xc4200001a0, 0xc420020000)
        /home/travis/gopath/src/github.com/wal-g/wal-g/connect.go:76 +0x361
github.com/wal-g/wal-g.HandleBackupPush(0xc42017c900, 0x1c, 0xc420116e70, 0xc42017c6c0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:549 +0x318
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:107 +0x6db
```

**Comment by x4m** [comment]
Hi, Ben! Thanks for the report!
Unfortunately, WAL-G does not support 9.2 as for now. This functionality is expected in #38. Partially, that's the reason why we have such inconsistent error message. Probably, I should fix that.
I have no ETA on #38, but if you wish, you can contribute to its development, seems like that not so much of additional functionality left there unimplemented.

**Comment by benubois** [comment]
Ah ok! That makes sense. I’m planning on upgrading to 10.1 soon and I’ll try again after that. 

Thanks!
