### ISSUE TITLE
Missing WAL

### ISSUE THREAD

**Issue by benubois** [wal-g/wal-g#62]
Hi,

I'm running into an issue with a missing WAL file. Currently I have postgres archiving with both `wal-e` and `wal-g`

```
archive_command = '/usr/bin/envdir /etc/wal-e.d/writer /usr/local/bin/wal-e wal-push %p && /usr/bin/envdir /etc/wal-g.d/writer /usr/local/bin/wal-g wal-push %p'
```

However when restoring from `wal-g`, postgres reports an error:

```
2018/02/05 22:18:06 WAL-prefetch file:  000000010000B6A90000008E
2018/02/05 22:18:06 Archive '000000010000B6A90000008E' does not exist.
2018-02-05 22:18:06.792 UTC [15164] LOG:  restored log file "000000010000B6A90000008D" from archive
2018-02-05 22:18:07.580 UTC [15164] FATAL:  WAL ends before end of online backup
2018-02-05 22:18:07.580 UTC [15164] HINT:  All WAL generated while online backup was taken must be available at recovery.
```

In the `wal-g` log it does in fact seem to skip right over `000000010000B6A90000008E`

```
BUCKET: database
SERVER: wal-g/db3
WAL PATH: wal-g/db3/wal_005/000000010000B6A90000008D.lz4

BUCKET: database
SERVER: wal-g/db3
WAL PATH: wal-g/db3/wal_005/000000010000B6A90000008F.lz4
```

The `wal-e` log does show this segment:

```
Feb  5 04:12:41 db3 wal_e.worker.upload INFO     
MSG: begin archiving a file#012        
DETAIL: Uploading "pg_wal/000000010000B6A90000008D" to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008D.lzo".#012        
STRUCTURED: time=2018-02-05T10:12:41.865887-00 pid=15524 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008D.lzo prefix=wal-e/db3/ seg=000000010000B6A90000008D state=begin

Feb  5 04:12:41 db3 wal_e.worker.upload INFO     
MSG: begin archiving a file#012        
DETAIL: Uploading "pg_wal/000000010000B6A90000008E" to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008E.lzo".#012        
STRUCTURED: time=2018-02-05T10:12:41.869823-00 pid=15524 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008E.lzo prefix=wal-e/db3/ seg=000000010000B6A90000008E state=begin

Feb  5 04:12:42 db3 wal_e.worker.upload INFO     
MSG: completed archiving to a file#012        
DETAIL: Archiving to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008D.lzo" complete at 14886.7KiB/s.#012        
STRUCTURED: time=2018-02-05T10:12:42.557404-00 pid=15524 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008D.lzo prefix=wal-e/db3/ rate=14886.7 seg=000000010000B6A90000008D state=complete

Feb  5 04:12:42 db3 wal_e.worker.upload INFO     
MSG: completed archiving to a file#012        
DETAIL: Archiving to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008E.lzo" complete at 11440.3KiB/s.#012        
STRUCTURED: time=2018-02-05T10:12:42.792245-00 pid=15524 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008E.lzo prefix=wal-e/db3/ rate=11440.3 seg=000000010000B6A90000008E state=complete

Feb  5 04:12:44 db3 wal_e.worker.upload INFO     
MSG: begin archiving a file#012        
DETAIL: Uploading "pg_wal/000000010000B6A90000008F" to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008F.lzo".#012        
STRUCTURED: time=2018-02-05T10:12:44.996389-00 pid=15545 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008F.lzo prefix=wal-e/db3/ seg=000000010000B6A90000008F state=begin

Feb  5 04:12:46 db3 wal_e.worker.upload INFO     
MSG: completed archiving to a file#012        
DETAIL: Archiving to "s3://database/wal-e/db3/wal_005/000000010000B6A90000008F.lzo" complete at 5754.38KiB/s.#012        
STRUCTURED: time=2018-02-05T10:12:46.528526-00 pid=15545 action=push-wal key=s3://database/wal-e/db3/wal_005/000000010000B6A90000008F.lzo prefix=wal-e/db3/ rate=5754.38 seg=000000010000B6A90000008F state=complete
```

I do not see any errors reported in the log.

Is there anything I can provide that would help figure out why the segment is missing?

Thanks!

**Comment by x4m** [comment]
Hi, Ben!
I think that you encountered #58. WAL-E uploaded a file from archive_status and Postgres does not call WAL-G for this file anymore.

Just by coincidence right now one of my QA databases experienced the necessity of this feature (bulk upload from archive_status, which, in your case was done by WAL-E). And just yesterday Zalando guy at PgConf.Russia asked to implement it.
So, I think it's about a time for me to do that... 
Thanks!

**Comment by x4m** [comment]
BTW after implementing this thing with archive_status WAL-G will steal files from WAL-E too (WAL-E already is doing this)

**Comment by benubois** [comment]
Interesting! Does that mean if I were just archiving with wal-g that this would not happen?

**Comment by x4m** [comment]
> Does that mean if I were just archiving with wal-g that this would not happen?
Yes. I think so.

I've done the implementation of archive_status scan. Right now QA tests are running. Tomorrow morning (UTC+3) I'm planning to make the new release.

**Comment by benubois** [comment]
Thanks! I switched to using wal-g only and have successfully backed up and recovered with it several times.

Also, I noticed 0.1.5 went up with support for scanning archive_status.

Not sure if this is at all related but I occasionally see "checkpoints are occurring too frequently" in my postgres logs. Will this release help with that or is that just mean I need to adjust my checkpoint settings?

**Comment by x4m** [comment]
@benubois about "checkpoints are occurring too frequently": there must be also hint in logs that you can increase max_wal_size in logs. I think it is reasonable.

What is going on is settings of your database are not suitable for your workload, your database accumulates WAL too quickly and has to do checkpoint often.
The frequent checkpoint is good for fast recovery but affects performance. Checkpoint is synchronisation of shared buffers content with disk. I'd recommend reading docs on WAL https://www.postgresql.org/docs/current/static/wal-configuration.html : this is the critical thing for the performance of your DB.
