### ISSUE TITLE
archive file has wrong size

### ISSUE THREAD

**Issue by bartdag** [wal-g/wal-g#63]
Hi, we are currently testing wal-g with a small database that writes an entry every minute. When we try to restore the DB, we sometimes get this error:

```
2018-02-10 05:48:59.478 EST [25962] FATAL:  archive file "000000010000000000000028" has wrong size: 8388608 instead of 16777216
```

If we start over (rm -rf the data dir, backup-fetch, then recovery), we sometimes manage to fully restore the db, sometimes we get another similar error:

```
2018-02-10 06:01:29.671 EST [27419] FATAL:  archive file "000000010000000000000027" has wrong size: 8388608 instead of 16777216
```

The relevant part of the postgresql.conf:

```
wal_level = logical
archive_mode = on
archive_command = 'envdir /etc/wal-g.d/env /usr/local/bin/wal-g wal-push %p'
archive_timeout = 60
```

The recovery.conf file when we try to restore the db on a secondary cluster:

```
restore_command = 'envdir /etc/wal-g.d/env /usr/local/bin/wal-g wal-fetch "%f" "%p"'
```

We are not using GPG and we only declare basic environment variables:

```
ls -l /etc/wal-g.d/env/
total 12
-rwxr-x--- 1 root postgres 13 Feb  9 04:32 AWS_REGION
-rwxr-x--- 1 root postgres 16 Feb  9 04:53 PGHOST
-rwxr-x--- 1 root postgres 39 Feb  9 04:32 WALE_S3_PREFIX
```

**Comment by x4m** [comment]
Hello, Barthelemy! Your case seems both strange and important.
I want to ask for some additional info.
What is WAL-G version?
What S3 implementation do you use?
What is the size of WALs 000000010000000000000028 and 000000010000000000000027 in S3?
Do you have any signs of the file system and network malfunction?
Is restore point beyond 000000010000000000000028?
Can you include json sentinel file, or, at least result of backup-list command?

**Comment by bartdag** [comment]
wal-g version:
I downloaded: https://github.com/wal-g/wal-g/releases/download/v0.1.5/wal-g.linux-amd64.tar.gz

I use AWS S3 (in ca-central-1), standard storage class.

S3 reports these sizes:
- walg/testvm/wal_005/000000010000000000000027.lz4 94.4 KB
- walg/testvm/wal_005/000000010000000000000028.lz4 96.9 KB

The restore point was beyond 000000010000000000000028 (LATEST, which included hundreds of wal segments).


Result of backup-list:
```
postgres@testvm:~$ envdir /etc/wal-g.d/env wal-g backup-list
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
name    last_modified   wal_segment_backup_start
base_00000001000000000000000E   2018-02-09T11:16:24Z    00000001000000000000000E
base_000000010000000000000007   2018-02-09T11:16:24Z    000000010000000000000007
base_0000000100000005000000DC   2018-02-10T10:41:12Z    0000000100000005000000DC
```

PostgreSQL version:
Version: 10.2-1.pgdg16.04+1 (from postgresql apt)

OS (ubuntu xenial):
```
postgres@testvm:~$ uname -a
Linux testvm 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not sure what you mean by the json sentinel file?

This is a test environment (t2.small using a small EBS drive) so I can give you access to the files and if it comes to this, the whole VM. If I try to reproduce this, what would be the best way to provide you with meaningful trace/log (except saying that it happens sometimes)? 

Thanks!

**Comment by x4m** [comment]
Do you observe traces of OOMs of WAL-PREFETCH in syslog?
Does the bug reproduce on previous pre-release (0.1.4)?

Access to S3 would be great, but I think I can setup similar test site myself. Latest tests were acquired on big VMs. Anyway, seems like I'll be able to look closely only on Monday morning...

**Comment by bartdag** [comment]
I executed the recovery 5 more times (3 without a recovery_target_time and 2 with one). One of the runs with a recovery_target_time set a few hours after the base backup encountered this problem with a wal segment (`[29887] FATAL:  archive file "000000010000000000000031" has wrong size: 12582912 instead of 16777216`). Memory usage was minimal at the time ~200 MB out of 2 GB RAM, there were no OOM or error messages in syslog. The weird thing is that when I executed the exact same run a few minutes later, it completed without any issue.

I will try with earlier releases of wal-g and report my findings here. Thanks!

**Comment by bartdag** [comment]
Some more tests:

1. I executed a recovery with wal-g 0.1.4 five times and everything went fine.

2. I tried the exact same recovery with wal-g 0.1.5 five times and 3 recoveries failed.

The errors were different than the ones I reported previously. I actually encountered the same error while testing 0.1.5 but did not report it because I thought I had done something wrong :-)

```2018-02-10 18:52:34.286 EST [10221] LOG:  restored log file "000000010000000000000039" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-10 18:52:34.434 EST [10221] LOG:  restored log file "00000001000000000000003A" from archive
2018-02-10 18:52:34.437 EST [10221] LOG:  invalid magic number 0000 in log segment 00000001000000000000003A, offset 0
2018-02-10 18:52:34.437 EST [10221] LOG:  redo done at 0/39000120
2018-02-10 18:52:34.437 EST [10221] LOG:  last completed transaction was at log time 2018-02-09 05:36:01.521652-05```

Second error:
```2018-02-10 19:01:16.884 EST [19474] LOG:  restored log file "0000000100000000000000E3" from archive
2018-02-10 19:01:16.889 EST [19474] LOG:  invalid magic number 0000 in log segment 0000000100000000000000E3, offset 0
2018-02-10 19:01:16.889 EST [19474] LOG:  redo done at 0/E2000120
2018-02-10 19:01:16.889 EST [19474] LOG:  last completed transaction was at log time 2018-02-09 08:26:01.845417-05```

Third error:
```BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-10 19:03:19.890 EST [21600] LOG:  restored log file "000000010000000000000032" from archive
2018-02-10 19:03:19.906 EST [21600] LOG:  invalid magic number 0000 in log segment 000000010000000000000032, offset 0
2018-02-10 19:03:19.906 EST [21600] LOG:  redo done at 0/310001C8
2018-02-10 19:03:19.906 EST [21600] LOG:  last completed transaction was at log time 2018-02-09 05:28:01.133364-05```

Just to clarify: the backups and wal segments were pushed using 0.1.5, but I tried the restore with 0.1.4 and 0.1.5.

**Comment by x4m** [comment]
Thank you for testing!
I cannot reproduce the problem in my environment (I use Porto containers and mdadm over SSD).
Per your report, I'll mark 0.1.5 release as pre-release.
Tomorrow, I'll try to reproduce on Amazon EBS

**Comment by x4m** [comment]
Looks like something similar [happened before](https://groups.google.com/forum/#!topic/wal-e/8wwiDkrNLXQ)

@bartdag can I ask you for one more experiment? v0.1.5 + WALG_MAX_DOWNLOAD_CONCURRENCY set to 0 (do not leave it this way, just for tests)
if this will not fail we will be sure it is the problem in prefetch.

**Comment by x4m** [comment]
I've misspelled correct setting, it should be WALG_DOWNLOAD_CONCURRENCY

**Comment by bartdag** [comment]
Hi,

I first executed 5 runs with wal-g and I encountered the problem three times again so at least I knew I could reproduce the error.

I then set WALG_DOWNLOAD_CONCURRENCY to 0, but only for the wal-fetch in recovery (backup-fetch seemed to get stuck and do nothing after printing BUCKET...SERVER...).

I ran the recovery 5 times and encountered no error so this seems to be the problem.

I removed the WALG_DOWNOAD_CONCURRENCY variable and executed the recovery again, but it took 10 attempts to encounter the error :-( I'm running out of time, but I will try later to test the standby_mode = on mentioned in the Google Groups post to see if it makes a difference.

**Comment by x4m** [comment]
Thanks, this proves that prefetch is buggy, I'll look into it. Probably, will fire my pwn t2 cluster.

**Comment by x4m** [comment]
@bartdag I still cannot reproduce the problem, but I have added fixes for some possible bugs to v0.1.6. Can I ask you to test this release?
Your help is invaluable, thanks.

**Comment by bartdag** [comment]
Hi,

I reproduced the problem with 0.1.5, but it took me another 10 attempts again. It seemed less frequent than before.

I tried to reproduce the problem with 0.1.6 by running it 10 times (both backup-fetch and wal-fetch used 0.1.6) and I did not see the problem.

If you are fine with these results, I will stop my spot instance :-)

**Comment by x4m** [comment]
If the bug was there, it would manifest itself with probability 65%.
Technically, I'd be fine with 95%, which would be achieved with 18 more runs.

But I think that it's time for me to go to AWS and do that 18 runs myself.
Thank you for your work!

**Comment by bartdag** [comment]
I'll run the test for the next hour and report the results. I used to be able to reproduce the bug more easily, which is why I was not totally confident about my last runs.

**Comment by bartdag** [comment]
So I encountered this bug with 0.1.6. Notice how it is different than the bug I originally reported, but it matches another error that I reported later in this [comment](https://github.com/wal-g/wal-g/issues/63#issuecomment-364706989): 

```
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-13 04:58:08.936 EST [19007] LOG:  restored log file "000000010000000000000034" from archive
2018-02-13 04:58:08.967 EST [19007] LOG:  invalid magic number 0000 in log segment 000000010000000000000034, offset 0
2018-02-13 04:58:08.967 EST [19007] LOG:  redo done at 0/33000120
2018-02-13 04:58:08.967 EST [19007] LOG:  last completed transaction was at log time 2018-02-09 05:30:01.230061-05
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-13 04:58:10.401 EST [19007] LOG:  restored log file "000000010000000000000033" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/13 04:58:10 Archive '00000002.history' does not exist.
2018-02-13 04:58:10.823 EST [19007] LOG:  selected new timeline ID: 2
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/13 04:58:11 Archive '00000001.history' does not exist.
2018-02-13 04:58:11.330 EST [19007] LOG:  archive recovery complete
2018-02-13 04:58:11.639 EST [19006] LOG:  database system is ready to accept connections
```

This is problematic because 000000010000000000000033 is not the last segment, but postgresql stop reading logs after that.

**Comment by x4m** [comment]
Ok, the bug is still there.
Seems like instead of 16MB of WAL you get 16MB of zeroes (v0.1.6 would not let WAL-G give PostgreSQL anything besides 16Mb file).
When you have standby_mode=off PostgreSQL stops recovery and thinks that it is here already. This is, obviously, wrong.
I'll do more debugging...

**Comment by bartdag** [comment]
Maybe one thing that would help is a logging statement that tells the exact size of the downloaded compressed segment (maybe with a sha sum on it) and then a sha sum on the uncompressed segment. When an error occurs, it would then be obvious if the problem is with the uncompression process vs the network download. 

These wal segments are almost empty because there is very little activity on the database.

Also if it helps, there is another cluster running at the same time (on another port) sending wal archives (with 0.1.5) to S3 every 30 seconds.

The VM and S3 are connected through a VPC endpoint (faster and free bandwidth).

Another question: does wal-g shares a cache with all postgresql clusters on a machine or is it per cluster?

**Comment by x4m** [comment]
WAL-G keeps it's prefetch cache in location where it is asked to restore file. I.e. if you have a cluster of 9.6 at /tmp/data/ it will have cache at /tmp/data/pg_xlog/.wal-g/prefetched

**Comment by bartdag** [comment]
The clusters are (obviously) in different directories so that is not the problem. Thanks!

**Comment by x4m** [comment]
Essentially, there are two things to consider:
1. Fsync prefetched files
2. Check XLOG_PAGE_MAGIC of prefetched files to check their integrity

Comments in WAL-E are repeating many times that fsync is omitted to increase performance.
Anyway, I have to build my reliable stage reproduction to fix this permanently.

**Comment by x4m** [comment]
@bartdag you do not use tmpfs for pg_xlog directory, right?

I cannot reproduce the problem in Amazon...
I've gone through WAL-E code and only difference I've found is that it does link when moving from running to prefetched, while WAL-G is doing rename.

**Comment by bartdag** [comment]
I do not use tmpfs. It's straight on the root ebs drive (gp-2, ebs encrypted, ext4). I've kept the VM up if you want me to run additional tests. 

I'm not surprised you were not able to reproduce the bug, it seems to be a very elusive one. At some point I was seeing the error every other run and now I often have to make 10-15 runs to see something. I can try tonight to spin another VM with the same s3 bucket and see if I can reproduce the problem.

I have also rebooted in case there was something transient causing the bug, but I've encountered the problem after a reboot.

**Comment by x4m** [comment]
Can I ask you to try current master version?
Here's compiled version which I scp'ed from my Amazon VM https://yadi.sk/d/BmMl6C263SPJUN
The difference is that Link instead of Rename

**Comment by x4m** [comment]
My t2 instances are not encrypted.. may be, it's somehow related

**Comment by bartdag** [comment]
1. Tried 0.1.5 and encountered the invalid magic number 0000 in log segment 2 times out of 5 (yay?).

2. Tried the wal-g binary you sent me. The first time I got an error and a logging statement I never saw before:

Logging statement:
```
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:39.786 EST [9689] LOG:  restored log file "000000010000000000000046" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:39.918 EST [9689] LOG:  restored log file "000000010000000000000047" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/14 09:26:40 WAL-G: Prefetch error: wrong file size of prefetched file
2018-02-14 09:26:42.013 EST [9689] LOG:  restored log file "000000010000000000000048" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:42.175 EST [9689] LOG:  restored log file "000000010000000000000049" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:42.248 EST [9689] LOG:  restored log file "00000001000000000000004A" from archive
```

Error:

```
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:57.720 EST [9689] LOG:  restored log file "00000001000000000000006F" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:58.091 EST [9689] LOG:  restored log file "000000010000000000000070" from archive
2018-02-14 09:26:58.110 EST [9689] LOG:  invalid magic number 0000 in log segment 000000010000000000000070, offset 0
2018-02-14 09:26:58.110 EST [9689] LOG:  redo done at 0/6F0001E0
2018-02-14 09:26:58.110 EST [9689] LOG:  last completed transaction was at log time 2018-02-09 06:31:01.058569-05
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 09:26:59.919 EST [9689] LOG:  restored log file "00000001000000000000006F" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/14 09:27:00 Archive '00000002.history' does not exist.
2018-02-14 09:27:00.671 EST [9689] LOG:  selected new timeline ID: 2
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/14 09:27:01 Archive '00000001.history' does not exist.
2018-02-14 09:27:01.443 EST [9689] LOG:  archive recovery complete
2018-02-14 09:27:01.771 EST [9688] LOG:  database system is ready to accept connections
```

I will try tonight to spin a new VM and see if I can reproduce the problem.

**Comment by bartdag** [comment]
I tried with another vm but with the same bucket: t2-small, 8 gb gp-2 encrypted, ext-4, ubuntu 16.04, postgresql 10.

One thing I should have mentioned since the beginning is that the wal level is set to logical.

I got the following error 3 times out of 3 with the zipped version you posted (on three different wal segments).

```
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 20:41:09.207 EST [23480] LOG:  restored log file "00000001000000000000004E" from archive
2018-02-14 20:41:09.211 EST [23480] LOG:  invalid magic number 0000 in log segment 00000001000000000000004E, offset 0
2018-02-14 20:41:09.211 EST [23480] LOG:  redo done at 0/4D000120
2018-02-14 20:41:09.211 EST [23480] LOG:  last completed transaction was at log time 2018-02-09 05:56:01.47834-05
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018-02-14 20:41:10.868 EST [23480] LOG:  restored log file "00000001000000000000004D" from archive
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/14 20:41:11 Archive '00000002.history' does not exist.
2018-02-14 20:41:11.438 EST [23480] LOG:  selected new timeline ID: 2
BUCKET: test-resulto-pgbackup
SERVER: walg/testvm
2018/02/14 20:41:11 Archive '00000001.history' does not exist.
2018-02-14 20:41:11.942 EST [23480] LOG:  archive recovery complete
2018-02-14 20:41:12.061 EST [23479] LOG:  database system is ready to accept connections
```

Interestingly, I never encountered an error with 0.1.4 in 10 runs.

**Comment by x4m** [comment]
@bartdag can you give me S3 keys for the bucket with archive? I'm running through thousands of WAL and you somehow get 3/3 bingo :)

Also, how do you create encrypted volume? I cannot start VM encrypted
https://yadi.sk/i/N2vE8csl3SR5Wo
But I can attach encrypted volume

**Comment by bartdag** [comment]
For the encrypted boot volume, you need to create an encrypted AMI first (ref: https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/). I'll create a user for you and send you the credentials. It might be easier to clone the content at some point if you want to perform more tests.

**Comment by bartdag** [comment]
Email sent.

**Comment by x4m** [comment]
Thanks, I can reproduce from your WALs!
So far it's not neither encryption, nor fsync. But it is related to prefetch multithreading. I go on hunting.

**Comment by bartdag** [comment]
Yes! Good luck! I also noticed that the bucket is encrypted at rest, but this should be transparent to any aws library used to interact with S3.

**Comment by bartdag** [comment]
Hi @x4m , just to confirm, can I delete my temporary vm since you are able to reproduce the problem (I'll keep the bucket up)?

**Comment by x4m** [comment]
Yes, but plz keep S3 files. Many thanks, Barthelemy!

**Comment by x4m** [comment]
I've added checks of XLOG_PAGE_MAGIC and WAL file size, replaced hardlinks with file renames, added several error checks and now I'm observing stable restoration of your 0x1800+ WAL files from the archive.
I'll leave the machine go on testing for the weekend (have accumulated lots of CPU credits between hacking) and if everything goes OK will cut stable release on Monday.

**Comment by x4m** [comment]
By the way, WAL-E recommends using standby_mode = on. In this case, if cluster fetches malformed WAL it just retries. I think in WAL-G we have to add the same recommendation. Anyway, it is good that we managed to ensure no malformed WALs will go through.

**Comment by bartdag** [comment]
Hi Andrey, since this issue is closed, I assume I can keep a backup of the S3 files but close the bucket (and revoke your user)?

Thanks!
