### ISSUE TITLE
Can't make wal-g to write logs when started by cron

### ISSUE THREAD

**Issue by luza** [wal-g/wal-g#649]
When executed from the terminal wal-g writes logs to stdout and stderr.

When it scheduled to start by cron, it writes nothing.

Tried in this way:
```
0 * * * * /usr/local/bin/wal-g backup-push /var/lib/postgresql/9.6/main &>> /var/log/postgresql/wal-g.log
```

And tried to debug it in this way:
```
* * * * * /tmp/backup-push.sh
```
```
> cat /tmp/backup-push.sh
#!/bin/sh

echo "--- START ---" >> /tmp/cron-debug.txt
wal-g backup-list &>> /tmp/cron-debug.txt
echo "--- END ---" >> /tmp/cron-debug.txt
```

The output is:
```
> cat /tmp/cron-debug.txt
--- START ---
--- END ---
--- START ---
--- END ---
```

Any thoughts why this happens?

OS is `Ubuntu 18.04.3 LTS` if that matters.

**Comment by defntvdm** [comment]
As I know wal-g writes logs to stderr.
Try this
`0 * * * * /usr/local/bin/wal-g backup-push /var/lib/postgresql/9.6/main 2>> /var/log/postgresql/wal-g.log &`

**Comment by luza** [comment]
Worked perfectly, thank you.
