### ISSUE TITLE
Crash with disappearing base backup segment

### ISSUE THREAD

**Issue by benubois** [wal-g/wal-g#65]
Hi,

I ran into a crash recently during a `backup-push`. The server happened to be running [pg_repack](https://github.com/reorg/pg_repack) at the same time, and I'm guessing that's the cause of this since it creates and drops lot of temporary tables. 

I'm not sure if this is something wal-g could/should handle, but I thought I'd report it to see if it could recover from this particular error.

Thanks!

```
/base/16400/94197891.8
2018/02/11 03:17:12 lstat /var/lib/postgresql/10/main/base/16400/94197891.9: no such file or directory
TarWalker: walk failed
github.com/wal-g/wal-g.(*Bundle).TarWalker
	/home/travis/gopath/src/github.com/wal-g/wal-g/walk.go:33
github.com/wal-g/wal-g.(*Bundle).TarWalker-fm
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:570
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:372
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:376
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:376
path/filepath.Walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:398
github.com/wal-g/wal-g.HandleBackupPush
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:570
main.main
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:107
runtime.main
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/runtime/proc.go:185
runtime.goexit
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/runtime/asm_amd64.s:2197
```

**Comment by benubois** [comment]
I forgot to mention that is is wal-g version 0.1.4.

**Comment by x4m** [comment]
Thanks for reporting. This was fixed at https://github.com/wal-g/wal-g/commit/258a0897e12d33766e7c3b60852d79eea48e428f and in 0.1.5
But 0.1.5 possibly contain bug in prefetch, I cannot reproduce it, but will have another stable release soon.

**Comment by x4m** [comment]
Check out release 0.1.7, the problem must be solved there.

**Comment by benubois** [comment]
Thank you! Appreciate all your work on wal-g.
