### ISSUE TITLE
I would like to have a feature that uses streaming replication for receiving wals.

### ISSUE THREAD

**Issue by sebasmannem** [wal-g/wal-g#692]
If we would add a function wal-receive, which would connect to Postgres and star a streaming replication connection to receive WAL segments, create wal files and pushes to S3, we could run wal-g without archive command and through a remote connection.
Looking at [this commit on pglogrepl](https://github.com/jackc/pglogrepl/commit/30f74807492eae37efc3725f09a342f6f5075e30), pglogrepl seems to have support for Physical Replication usage. Let's do a spike investigation for adding this option.

**Comment by tpetry** [comment]
You‘re describing a completely different backup mechanism. Have a look at barman which should be what you are looking for.

**Comment by sebasmannem** [comment]
@tpetry I don't really understand what you mean, but this ticket is now merged as PR 737.
If you talk about streaming backups with the Postgres protocol, that is being worked on.
On barman, barman uses native tools like pg_receivewal, and pg_basebackup, where with wal-g we rely on the golang implementations of the streaming protocol.
I will close this as being done.
