### ISSUE TITLE
Wrong metadata, uncompressed_size reflects size of single part of the backup.

### ISSUE THREAD

**Issue by yanchenko-igor** [wal-g/wal-g#701]
In case if tar file is bigger than WALG_TAR_SIZE_THRESHOLD, uncompressed_size stores only size of the last tar file and doesn't include previous parts of tar file.

**Comment by x4m** [comment]
It looks like a quite possible bug. And files inside one tar must be bigger than threshold quite often.
Can you please send a PR with fix?

**Comment by yanchenko-igor** [comment]
> Thanks for reporting this!
> It looks like a quite possible bug. And files inside one tar must be bigger than threshold quite often.
> Can you please send a PR with fix?

i tried to fix this, but it doesn't look very easy and requires some refactoring, I will give it another try.
