### ISSUE TITLE
backup fetch for Redis?

### ISSUE THREAD

**Issue by moredure** [wal-g/wal-g#712]

**Comment by x4m** [comment]
I think we have incomplete Redis support and should remove it from README until someone actually volunteer to make it great again. @g0djan what do you think?

**Comment by g0djan** [comment]
That'a right idea.

**Comment by x4m** [comment]
@moredure we would be happy to review Redis ```backup-fetch``` if you implement it.

**Comment by moredure** [comment]
Currently I am using another tool for it, but I will publish it soon
