### ISSUE TITLE
The storage sizes of backup data and raw are too different!!!???

### ISSUE THREAD

**Issue by zhangxu3486432** [wal-g/wal-g#716]
the `du` show that the storage size in pg path is 18G,

<img width="543" alt="screenshot" src="https://user-images.githubusercontent.com/30019034/88956935-b3375580-d2d0-11ea-92a3-a5269544f64d.png">

but the minio show that only 5 G.

<img width="321" alt="screenshot" src="https://user-images.githubusercontent.com/30019034/88956974-c2b69e80-d2d0-11ea-868d-dee2c18aec90.png">

What's backed up?

and

What's not backed up?

**Comment by x4m** [comment]
Every useful thing is backed up. And compressed.
We skip things like temp files, WAL (must be archived via wal-push) etc. if you use table spaces they must be setuped separately.

Also, by default you use lz4 - pretty modest compression codec. If you switch to brotli you will get x2 smaller backup.

**Comment by zhangxu3486432** [comment]
> Every useful thing is backed up. And compressed.
> We skip things like temp files, WAL (must be archived via wal-push) etc. if you use table spaces they must be setuped separately.
> 
> Also, by default you use lz4 - pretty modest compression codec. If you switch to brotli you will get x2 smaller backup.

Wow, great job, cool!!!
