### ISSUE TITLE
after run `select pg_switch_wal();` `wal-g wal-push` not executed

### ISSUE THREAD

**Issue by zhangxu3486432** [wal-g/wal-g#726]
`wal-g` is working fine, can push backup file to S3.

but when I run `select pg_switch_wal();` manually,  `wal-g wal-push` not executed, nothing happen.

postgresql: v12.2
wal-g: v0.2.15

**Comment by zhangxu3486432** [comment]
Can't use https, when I use http, all problems will be solved.

If I use https, `wal-g backup-push` work, but `wal-g wal-push` not work:

```
caused by: Put https://cos.ap-beijing.myqcloud.com/pgsqlbkp-1254116918/wal_005/000000010000000900000045.lz4: x509: certificate signed by unknown authority
```

May I ask what this is about?

**Comment by zhangxu3486432** [comment]
The cloud service(tencent cos) I'm using is compatible with the S3 protocol.

**Comment by zhangxu3486432** [comment]
postgresql run in docker.

**Comment by defntvdm** [comment]
Hi, try to update ca-certificates package on machine where you start `wal-g wal-push`.

**Comment by zhangxu3486432** [comment]
> Hi, try to update ca-certificates package on machine (docker container) where you execute `wal-g wal-push`.

thanks! I'll try it.
