### ISSUE TITLE
WAL-G failed to make base backup

### ISSUE THREAD

**Issue by konstantin-schura** [wal-g/wal-g#742]
**WAL-G version**:  v0.2.15

**PostgreSQL version**: 9.6

**Operating system/version**: Ubuntu 18.04

Hello,

I use wal-g to upload base backup to aws s3 daily by cron.
Sometimes base backup didn't upload completely.
Stderr wal-g
`INFO: 2020/08/26 04:06:43.462499 Starting part 19 ...
INFO: 2020/08/26 04:06:54.511771 Finished writing part 19.
INFO: 2020/08/26 04:07:36.284634 Starting part 20 ...
INFO: 2020/08/26 04:07:48.028766 Finished writing part 20.
INFO: 2020/08/26 04:08:26.378329 Starting part 21 ...
ERROR: 2020/08/26 04:08:30.574519 failed to upload 'pg96-master-wls/basebackups_005/base_0000000100000029000000E4/tar_partitions/part_019.tar.lz4' to bucket 'pg-wal': MultipartUpload: upload multipart failed
        upload id: JJrTsQrV1OW.7TbeHd9LNrLEHy2yL9Nry0ltA5KPk3HpiK0Fz8XTr7LYt66j9mO9mwjGTleqwvzenyBAzPBGvVGxKX3rNa3WTaR5XKv6EsbM9MkYwrskkgiyrZALCFZ1
caused by: SerializationError: failed to unmarshal error message
        status code: 400, request id: 0SFP8J2K6REX3HAG, host id: RxInGkFvAuaKn1LYeT/gdomRaUgagF+dv0j6qgha00xnBMO0uBzOn9hyq2ui2MUKtam+6IRk8ZI=
caused by: UnmarshalError: failed to unmarshal error message
caused by: unexpected EOF
ERROR: 2020/08/26 04:08:30.574538 upload: could not upload 'base_0000000100000029000000E4/tar_partitions/part_019.tar.lz4'
ERROR: 2020/08/26 04:08:30.574548 failed to upload 'pg96-master-wls/basebackups_005/base_0000000100000029000000E4/tar_partitions/part_019.tar.lz4' to bucket 'pg-wal': MultipartUpload: upload multipart failed
        upload id: JJrTsQrV1OW.7TbeHd9LNrLEHy2yL9Nry0ltA5KPk3HpiK0Fz8XTr7LYt66j9mO9mwjGTleqwvzenyBAzPBGvVGxKX3rNa3WTaR5XKv6EsbM9MkYwrskkgiyrZALCFZ1
caused by: SerializationError: failed to unmarshal error message
        status code: 400, request id: 0SFP8J2K6REX3HAG, host id: RxInGkFvAuaKn1LYeT/gdomRaUgagF+dv0j6qgha00xnBMO0uBzOn9hyq2ui2MUKtam+6IRk8ZI=
caused by: UnmarshalError: failed to unmarshal error message
caused by: unexpected EOF
INFO: 2020/08/26 04:08:42.552066 Finished writing part 21.
ERROR: 2020/08/26 04:08:42.552096 Unable to complete uploads
`
Syslog postgresql message:
`WARNING:  aborting backup due to backend exiting before pg_stop_backup wa
s called`

Configuration is minimal. Credentials and s3 prefix.
Params WALG_DOWNLOAD_CONCURRENCY, WALG_UPLOAD_CONCURRENCY, WALG_UPLOAD_DISK_CONCURRENCY have default values.

Maybe I do something wrong?

**Comment by x4m** [comment]
Hi!
Looks like a network problem, but we fixed something similar at https://github.com/wal-g/wal-g/pull/727
maybe @bunsenmcdubbs could comment is it that problem or something else?
thanks!

**Comment by konstantin-schura** [comment]
I have the same postgresql instanse, but with wal-e. It doesn't have this issue.

**Comment by x4m** [comment]
Try latest prerelease. We fixed few S3 issues there. Wal-e does not suffer from bugs in AWS Go SDK

**Comment by bunsenmcdubbs** [comment]
Hard to say. The fix referenced above handles S3 error handling bugs for certain networking errors related to "using closed network connection". That said we've seen this manifest in a number of ways so it could be related. Worth giving the prerelease a shot!

**Comment by konstantin-schura** [comment]
Thank you!
