### ISSUE TITLE
Base backup: warning: pg_internal.init deleted during filepath walk

### ISSUE THREAD

**Issue by konstantin-schura** [wal-g/wal-g#749]
**WAL-G version: v0.2.15
PostgreSQL version: 9.6
Operating system/version: Ubuntu 18.04**

Hello,
Cron starts base backup daily.
/usr/bin/envdir /etc/wal-g/env  /usr/local/bin/wal-g backup-push /var/lib/postgresql/9.6/main

Backup is finished ok, but I get warning.

INFO: Starting part 128 ...
INFO: Finished writing part 128.
INFO:  Starting part 129 ...
WARNING:  /var/lib/postgresql/9.6/main/base/139766/pg_internal.init  deleted during filepath walk
INFO:  Finished writing part 129.
INFO:  Starting part 130 ...
INFO:  /global/pg_control
INFO:  Finished writing part 130.
INFO:  Calling pg_stop_backup()
INFO:  Starting part 131 ...
INFO:  backup_label
INFO:  tablespace_map
INFO:  Finished writing part 131.
INFO:  Wrote backup with name base_0000000100000045000000AA

What does it mean? Should I be worried about my bakup?)

**Comment by x4m** [comment]
Don't worry, it's normal that PG deletes files.

**Comment by konstantin-schura** [comment]
Thank you!
