### ISSUE TITLE
[UI BUG] Command 'delete' is not supported

### ISSUE THREAD

**Issue by Scukerman** [wal-g/wal-g#77]
```
~ # wal-g
Please choose a command:
  backup-fetch	fetch a backup from S3
  backup-push	starts and uploads a finished backup to S3
  backup-list	prints available backups
  wal-fetch	fetch a WAL file from S3
  wal-push	upload a WAL file to S3
  delete	clear old backups and WALs
~ # wal-g delete
Command 'delete' is unsupported by WAL-G.

~ # 
```

Looks like there's no case for usage of the delete command:
https://github.com/wal-g/wal-g/blob/master/cmd/wal-g/main.go#L69

**Comment by x4m** [comment]
Hi! It's UI bug that WAL-G does not print you delete help message.
Which is
```delete requires at least 2 parameters
		retain 5                      keep 5 backups
		retain FULL 5                 keep 5 full backups and all deltas of them
		retail FIND_FULL 5            find necessary full for 5th and keep everything after it
		before base_0123              keep everything after base_0123 including itself
		before FIND_FULL base_0123    keep everything after base of base_0123```

Hope to fix it soon.
Thanks for reporting.

**Comment by Scukerman** [comment]
yeah, I've just figured it out. Thx for the quick response.
BTW, is there any gitter\slack\chat so user could reach developers without posting issues?

**Comment by x4m** [comment]
Well, we have no chat right now, but I think it is a good idea to have some medium for those who start using WAL-G. I'm not aware of available options besides IRC and Slack. What would you recommend? Can you point out how other project are doing this?

**Comment by Scukerman** [comment]
Like I said, they usually use gitter or slack for questions like this. And they accept issues only on feature requests or bugs. But I don't have any wide experience as well.

**Comment by x4m** [comment]
@Scukerman , I'll be ping here when I'll be ready to set up the chat. I think that it is very important to hear from users on any sight of a problem.

**Comment by Scukerman** [comment]
Thx. But until this, I'll keep posting questions :)

Getting back to the issue:
Well, I would strongly suggest to start using [cobra](https://github.com/spf13/cobra) cuz spent some time until I got how it works through looking at the code.
https://github.com/wal-g/wal-g/blob/f2cc408096a936ecb11d52373381ab3c3b62de9a/commands.go#L131-L135

The order of flags and commands looks very unusual.

**Comment by dev1ant** [comment]
> I'm not aware of available options besides IRC and Slack. What would you recommend? Can you point out how other projects are doing this?

I would prefer github issues or public mailing list rather than some sort of a chat. For two reasons:
1. It will keep the history and reduce (I hope) the number on same questions.
2. It will be indexed by search engines and give the ability to find answers with google without need to go to chat.

**Comment by Scukerman** [comment]
In this case, you'll have to read all the off topic messages like this. If you are ready for this, then it's okay.

**Comment by x4m** [comment]
This message is not a problem at all. But the reason for IRC channel (or similar) is quite contrary - it's about receiving more of these messages.
Mailing lists are the barrier for newcomers, actually. Github issues are less repulsive, but still, you have to extract subject and put your thoughts in single writing.

Currently, we do not need the reduction in the number of questions. We need to build the community. With "stupid" questions and repeated feature request, it's OK. I fear that some user will encounter a critical bug and will tempt to report it because he or she could miss something "stupid" in WAL-G setup.

**Comment by x4m** [comment]
@Scukerman I've created the channel on PostgreSQL Slack
https://postgresteam.slack.com/messages/CA25P48P2/
