### ISSUE TITLE
backup-push ignores set WALG_S3_STORAGE_CLASS

### ISSUE THREAD

**Issue by Scukerman** [wal-g/wal-g#78]
`backup-push` ignores set `WALG_S3_STORAGE_CLASS` and keeps uploading files as `STANDARD`.
`wal-push` works as expected.

**Comment by x4m** [comment]
Yep, that is a bug.
JSON sentinel was uploaded without storage class specification.
Thanks for reporting!
Can I ask you to check if now the problem is solved?

**Comment by Scukerman** [comment]
yeah, it has been fixed.
