### ISSUE TITLE
backup-push to size-limited bucket

### ISSUE THREAD

**Issue by x4m** [wal-g/wal-g#79]
@istarling recently have reported the interesting problem. When there is not enough space in bucket WAL-G retries every file many times.
I think that best solution should be to remove existing retry infrastructure in favor of AWS SDK built-in retries.
This may interfere with #74. @tamalsaha , how do you think, if I'll do that in a week or two I won't make a problem for your implementations of #74?

**Comment by g0djan** [comment]
@munakoiso tried to reproduce it, but it wasn't successful. If you can share with us the version of wal-g that you use and steps how you did it.
