### ISSUE TITLE
Deleting backups leaves sentinel file

### ISSUE THREAD

**Issue by daviesian** [wal-g/wal-g#81]
Apologies if this is me misunderstanding what is actually correct behaviour, but when I run this:

```
$ wal-g delete retain FULL 1 --confirm
2018/03/25 11:45:20 base_000000010000000000000008 skipped         
2018/03/25 11:45:20 base_000000010000000000000004 will be deleted 
```

The backup `base_000000010000000000000004` correctly disappears from my S3 bucket. However the sentinel file `base_000000010000000000000004_backup_stop_sentinel.json` remains, meaning that the deleted backup shows up in `wal-g backup-list` even though it no longer exists:

```
$ wal-g backup-list    
name    last_modified   wal_segment_backup_start                                                       
base_000000010000000000000004   2018-03-25T11:44:39Z    000000010000000000000004                       
base_000000010000000000000008   2018-03-25T11:45:02Z    000000010000000000000008                       
```

Manually deleting the sentinel file stops the actually-deleted backup from showing up.

Is this intended behaviour? I found it a bit misleading, so thought it was worth checking. Thanks!

**Comment by x4m** [comment]
If it is reproducible it is certainly a bug. I'll hunt for it tomorrow. Which version do you use?

**Comment by daviesian** [comment]
Ok, if this is not intended behaviour then I will try to build a proper reproducible case for you. I'm using the 0.1.7 release.

**Comment by x4m** [comment]
Many thanks @daviesian ! That's probably the coolest way to report bugs :)
This bug shows up when you place backup at the root of the bucket. We had several similar bugs before (e.g. #17), but this somehow slipped away. I will fix this in next release.

**Comment by daviesian** [comment]
Ah yes, Docker has done wonders for reproducibility!

At least this one is trivial to work around - thanks very much for working it out so quickly.
