### ISSUE TITLE
Different timeout/retry logic for wal-push (GCS)

### ISSUE THREAD

**Issue by NikolayS** [wal-g/wal-g#817]
(via @hphilipps https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/12034)

We need to have a different logic (retries, timeouts) for `wal-push` process compared to the `backup-push`. Why:

1. Postgres has its own retry logic, it is better to let to rely on it and fail fast
1. WALs are smaller than data files (16 MiB by default, might be bigger though), so use of composite objects is not needed

cc @agneum

**Comment by x4m** [comment]
This makes sense. How can we generalize this for all storages? Using different configs? Using config extensions for commands?

**Comment by NikolayS** [comment]
@x4m I think for `wal-push` we should just avoid any timeout and retry logic at all and rely on the driver (for timeouts and internal retries) + on the main Postgres logic (for retries). In this case, no additional config would be needed.

Thoughts?

cc @agneum

**Comment by x4m** [comment]
So we need to expose the interface to disable retries of storage?

**Comment by agneum** [comment]
We could disable retries of storage by default and enable them only if a certain parameter is passed.

**Comment by hphilipps** [comment]
The wal-g/storage drivers don't have any knowledge if they are uploading a small WAL segment or a big backup part. So it would be good to have an ability to tune for both use cases. We either could make it very general and provide CLI flags:

* `--chunksize` (e.g. for gcs wal-push 16MiB would be perfect, for gcs backup-push maybe 50MiB)
* `--retries` (e.g. for wal-push `1` and for backup-push `16`)

or provide config settings as ENV vars

* WAL_UPLOAD_CHUNKSIZE
* BACKUP_UPLOAD_CHUNKSIZE
* WAL_UPLOAD_RETRIES
* BACKUP_UPLOAD_RETRIES

For the specific case of gcs uploads we also should consider not to retry unrecoverable error types, e.g. when we get `object doesn't exist` errors for composite objects.

A very simple workaround for the problem without code-changes also could be to set the env var `GCS_CONTEXT_TIMEOUT ` to a very low value for wal-push. But that only would work for gcs.
