### ISSUE TITLE
Issues with parallel backup-push

### ISSUE THREAD

**Issue by Aevin1387** [wal-g/wal-g#82]
I've been testing out the parallel backup-push that is currently in master, and have run into a few breaking scenarios. 

First, and foremost, if the backup doesn't crash it never finishes. It gets through the last files, and seems to freeze while waiting for the last few to upload. Example:
```
...
/pg_xlog
/recovery.done
/server.crt
/server.key
Finished writing part 78.
```

Secondly, I've run into a couple of crashes, details of which can be found in [this gist](https://gist.github.com/Aevin1387/d6d30cb23c9a934aa38eed87a0800d8d). I've hit the "Wait Group" exception the vast majority of the time, and the "concurrent map iteration and map write" a handful of times. 

I've not yet been able to track down the cause of any of these issues, but I haven't spent a lot of time looking.

**Comment by x4m** [comment]
@Aevin1387 thanks for your report. Seems like I have to remove parallel backup from master and make pull request out of it to do more testing.

**Comment by x4m** [comment]
This seems to be fixed as for now
