### ISSUE TITLE
rating-composer and connections to database as superuser

### ISSUE THREAD

**Issue by banlex73** [wal-g/wal-g#836]
rating-composer is really a great feature but there's might be security concern, it requires access to all databases as supperuser, I see that it is only selecting data from pg_stat_all_tables but..
Can we add an improvement and setup a user with limited access to database on cluster? something like wal-g user and grant select on pg_stat_all_tables to wal-g

Thank you in advance.

**Comment by usernamedt** [comment]
> Can we add an improvement and setup a user with limited access to database on cluster?

You can set up the restricted user as you described and then adjust the `PGUSER`, `PGPASSWORD` in the WAL-G config file/environment variables.

**Comment by banlex73** [comment]
great idea, didn't know that!
Thanks a lot

**Comment by usernamedt** [comment]
> great idea, didn't know that!
> Thanks a lot

You're welcome :)
