### ISSUE TITLE
~postgres/env ~postgres/wal-g backup-push "$DATADIR" --rating-composer fails with panic: startReadingFile: failed to open file

### ISSUE THREAD

**Issue by banlex73** [wal-g/wal-g#837]
Unfortunately, it fails
INFO: 2020/12/17 19:59:32.918513 Starting part 80 ...
panic: startReadingFile: failed to open file '/pgsql/cluster/data/base/2516071/t267_11123082'
: open /pgsql/cluster/data/base/2516071/t267_11123082: no such file or directory

goroutine 439965 [running]:
github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs.func1(0xc0163a9220, 0xc0002e6270, 0x1fe8820, 0xc014f18190)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:186 +0x101
created by github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:182 +0x40f
Error running handler: exit status 2

**Comment by usernamedt** [comment]
Hi!

Thanks for reporting the issue. Did you manage to reproduce the error or it occurred only once?

**Comment by banlex73** [comment]
Hi, 
issue is constantly reproducible (last 4 days in a row)
`INFO: 2020/12/18 04:00:32.409950 Starting part 1 ...
panic: startReadingFile: failed to open file '/pgsql/cluster/data/base/1016799/t698_11145705'
: open /pgsql/cluster/data/base/1016799/t698_11145705: no such file or directory

goroutine 163 [running]:
github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs.func1(0xc01394d640, 0xc0022be750, 0x1fe8820, 0xc0002a25a0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:186 +0x101
created by github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:182 +0x40f
Error running handler: exit status 2```
INFO: 2020/12/19 04:00:24.103370 Querying pg_stat_all_tables
INFO: 2020/12/19 04:00:24.122519 Walking ...
WARNING: 2020/12/19 04:00:32.217690 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.15058.tmp  deleted during filepath walk
WARNING: 2020/12/19 04:00:32.217747 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.15373.tmp  deleted during filepath walk
WARNING: 2020/12/19 04:00:32.217902 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.1941.tmp  deleted during filepath walk
INFO: 2020/12/19 04:00:32.303715 Starting part 1 ...
panic: startReadingFile: failed to open file '/pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.4466.tmp'
: open /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.4466.tmp: no such file or directory

goroutine 131 [running]:
github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs.func1(0xc01519fd00, 0xc002278750, 0x1fe8820, 0xc0005a8aa0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:186 +0x101
created by github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:182 +0x40f
Error running handler: exit status 2

`INFO: 2020/12/19 04:00:24.122519 Walking ...
WARNING: 2020/12/19 04:00:32.217690 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.15058.tmp  deleted during filepath walk
WARNING: 2020/12/19 04:00:32.217747 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.15373.tmp  deleted during filepath walk
WARNING: 2020/12/19 04:00:32.217902 /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.1941.tmp  deleted during filepath walk
INFO: 2020/12/19 04:00:32.303715 Starting part 1 ...
panic: startReadingFile: failed to open file '/pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.4466.tmp'
: open /pgsql/cluster/data/pg_logical/snapshots/307-2CA26800.snap.4466.tmp: no such file or directory

goroutine 131 [running]:
github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs.func1(0xc01519fd00, 0xc002278750, 0x1fe8820, 0xc0005a8aa0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:186 +0x101
created by github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).PackTarballs
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/rating_tar_ball_composer.go:182 +0x40f
Error running handler: exit status 2`

**Comment by banlex73** [comment]
by the way, without --rating-composer it works fine. I use differencial backup if it does make any difference.

**Comment by usernamedt** [comment]
Should be fixed by #839
