### ISSUE TITLE
wal-show: "value out of range"

### ISSUE THREAD

**Issue by ball-hayden** [wal-g/wal-g#840]
Good day.
I'm receiving the following error when running `wal-show`:

```
$ wal-g wal-show
ERROR: 2020/12/19 16:16:24.009456 Error while loading .history file strconv.ParseUint: parsing "16": value out of range
```

WAL-G Version: `v0.2.19`
Postgres: `postgres (PostgreSQL) 12.5 (Debian 12.5-1.pgdg100+1)`
Storage: GCS

Is there a debug flag I can pass to give more information?

**Comment by usernamedt** [comment]
> Good day.
> 
> I'm receiving the following error when running `wal-show`:
> 
> 
> 
> ```
> 
> $ wal-g wal-show
> 
> ERROR: 2020/12/19 16:16:24.009456 Error while loading .history file strconv.ParseUint: parsing "16": value out of range
> 
> ```
> 
> 
> 
> WAL-G Version: `v0.2.19`
> 
> Postgres: `postgres (PostgreSQL) 12.5 (Debian 12.5-1.pgdg100+1)`
> 
> Storage: GCS
> 
> 
> 
> Is there a debug flag I can pass to give more information?

Hi!

Thanks for reporting the issue.

Contents of the current timeline .history file might be useful.

**Comment by ball-hayden** [comment]
Apologies for my ignorance - where would I find the current timeline `.history` file?

**Comment by usernamedt** [comment]
> Apologies for my ignorance - where would I find the current timeline `.history` file?

It should be in "wal_005" storage folder. Look for the 0000000x.history file with the highest number

**Comment by ball-hayden** [comment]
I have `000000EE.history.lz4`, attached as a zip to appease GitHub.

[000000EE.history.lz4.zip](https://github.com/wal-g/wal-g/files/5719891/000000EE.history.lz4.zip)

**Comment by usernamedt** [comment]
> I have `000000EE.history.lz4`, attached as a zip to appease GitHub.
> 
> [000000EE.history.lz4.zip](https://github.com/wal-g/wal-g/files/5719891/000000EE.history.lz4.zip)

Thanks! I've fixed the issue in https://github.com/wal-g/wal-g/pull/841

**Comment by ball-hayden** [comment]
Thank you 🙂
