### ISSUE TITLE
Pull backup and perform online restore

### ISSUE THREAD

**Issue by absolutejam** [wal-g/wal-g#851]
Howdy!

Hopefully I'm not out of line creating an issue for this request, but I thought it might be worth having it on record.

I'm wondering if there's a way to leverage `wal-g` to do an online restore, like is possible with `pg_restore`.

I'm looking at running a persistent Postgres instance for staging environment(s) that will contain a persistent 'production-copy' database, which can be leveraged to make a copy on-demand (Within the same instance). 

I started by outlining the following procedure:
  * Spin up an ephemeral Postgres instance
  * `wal-g backup-fetch` 
  * Start an ephemeral Postgres instance with config to restore from this 
  * `pg_dump` to disk 
  * `pg_restore` on the persistent host

Is there any way I can do this in a more streamlined fashion, ideally without requiring a running Postgres instance?

Thanks for providing this awesome tool!

**Comment by x4m** [comment]
Hi! You can do pg_dump | pg_restore without touching disk.
If we could provide partial restore it would be so cool, but this is WAL mess...

**Comment by x4m** [comment]
Deforming tuples right out from data files could be straignforward feature. But it's hard to know if the tuple was visible at certain point...

**Comment by absolutejam** [comment]
@x4m Thanks for the `pg_dump | pg_restore` suggestion! I was originally doing this in separate Kubernetes pods but have since taken a sidecar approach so I'll be able to do this now 👍
