### ISSUE TITLE
How to increase GCS Context Timeout

### ISSUE THREAD

**Issue by jlmanaloto** [wal-g/wal-g#852]
Hello!

As seen from the documentation, `GCS_CONTEXT_TIMEOUT` defaults to 1 hour. So if I want to increase the timeout to 2 hours do I set the value as `GCS_CONTEXT_TIMEOUT=2` ?

**Comment by x4m** [comment]
Hmm, probably, it's in seconds. We should improve the docs here.
Moreover, probably you do not need GCS_CONTEXT_TIMEOUT timeout anymore. in 0.2.19 GCS storage retries improved radically.

**Comment by jlmanaloto** [comment]
Okay, got it! Thanks!
