### ISSUE TITLE
How to setup swift V3

### ISSUE THREAD

**Issue by Oleksandr-Silin** [wal-g/wal-g#859]
Hello,
i'm new to this and trying to understand what exactly i need to provide to setup swift V3 backup. 
This info is probably is good enough for people who works with it.
> To store backups in Swift object storage, WAL-G requires that this variable be set:
> 
> WALG_SWIFT_PREFIX to specify where to store backups in Swift object storage (e.g. swift://test-container/walg-folder)
> WAL-G determines Swift object storage credentials using openStack default credentials. You can use any of V1, V2, V3 of the SwiftStack Auth middleware to provide Swift object storage credentials.

My provider "infomaniak" gave me next info:
```
Server	https://swiss-backup02.infomaniak.com
Path	/identity/v3
Project	sb_project_SBI
Domain	default
Project:Domain:Username	sb_project_SBI:<domain>:<user-name>
```
So based on that info I have created next .walg.json:
```
{
 "WALG_SWIFT_PREFIX":"/db-backups",
 "OS_AUTH_URL":"https://swiss-backup02.infomaniak.com/identity/v3",
 "OS_USERNAME":"my user name",
 "OS_PASSWORD":"my password"
}
```
If i run wal-g I receive next error:  Swift error : Unable to authenticate connection: Bad Request

Maybe i don't have proper info and for sure i don't know what i need to have to configure wal-g to make it work.  
What do i miss and how should i configure wal-g??

Thanks for the help!

**Comment by Tri0L** [comment]
Try to add `swift://` to prefix.
Like this:
```
"WALG_SWIFT_PREFIX":"swift://your_bucket/directory"
```

**Comment by Oleksandr-Silin** [comment]
Finally found solution (For whom who has Infomaniak, maybe others, I have used this instruction to configure postgresql backup https://edwardsamuel.wordpress.com/2016/05/24/set-up-scheduled-postgresql-backup-to-aws-s3-using-wal-e/). And i have next json:
```
{
 "WALG_SWIFT_PREFIX":"swift://bucket_name/my_any_directory_name",
 "OS_AUTH_URL":"https://swiss-backup02.infomaniak.com/identity/v3/",
 "OS_USERNAME":"infomaniak_user_name",
 "OS_PASSWORD":infomaniak_user_password",
 "OS_PROJECT_NAME":"infomaniak_project_name",
 "OS_USER_DOMAIN_NAME": "infomaniak_user_domain"
}
```

PS: my bucket I got using command in the terminal ``swift list``
