### ISSUE TITLE
Fail to restore MySQL backup: out of memory

### ISSUE THREAD

**Issue by tnt-dev** [wal-g/wal-g#862]
Hello!
I try to restore MySQL backup from Swift storage to my virtual machine and get 
`fatal error: runtime: out of memory`
Full traceback and debug WAL-G logs [here](https://pastebin.com/aLPWDch2)

Database size is about 250 GB, brotli archive (stream.br) is about 26 GB.
VM size: 4 vcpus / 16 GB RAM.
OS: Ubuntu Bionic / 4.15.0-118-generic
WAL-G versions: v0.2.18 / v0.2.19 / devel (b3f2765f0abc94d518a7fa8ffb24f2880904a83c)

**Comment by x4m** [comment]
Hi!
Pase to don show log
``` Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it. ```
Did WAL-G OOMed or xtrabackup?

**Comment by tnt-dev** [comment]
I put full log here:

`DEBUG: 2021/02/03 09:58:44.681510 --- COMPILED ENVIRONMENT VARS ---
DEBUG: 2021/02/03 09:58:44.681535 LC_ALL=C.UTF-8
DEBUG: 2021/02/03 09:58:44.681542 LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
DEBUG: 2021/02/03 09:58:44.681561 LESSCLOSE=/usr/bin/lesspipe %s %s
DEBUG: 2021/02/03 09:58:44.681564 LANG=en_US.UTF-8
DEBUG: 2021/02/03 09:58:44.681569 USER=root
DEBUG: 2021/02/03 09:58:44.681574 WALG_LOG_LEVEL=DEVEL
DEBUG: 2021/02/03 09:58:44.681582 PWD=/root
DEBUG: 2021/02/03 09:58:44.681584 HOME=/root
DEBUG: 2021/02/03 09:58:44.681591 LC_CTYPE=UTF-8
DEBUG: 2021/02/03 09:58:44.681613 SSH_TTY=/dev/pts/0
DEBUG: 2021/02/03 09:58:44.681616 MAIL=/var/mail/root
DEBUG: 2021/02/03 09:58:44.681618 TERM=xterm-256color
DEBUG: 2021/02/03 09:58:44.681622 SHELL=/bin/bash
DEBUG: 2021/02/03 09:58:44.681624 SHLVL=1
DEBUG: 2021/02/03 09:58:44.681627 LOGNAME=root
DEBUG: 2021/02/03 09:58:44.681632 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DEBUG: 2021/02/03 09:58:44.681635 LESSOPEN=| /usr/bin/lesspipe %s
DEBUG: 2021/02/03 09:58:44.681651 WALG_MYSQL_DATASOURCE_NAME=***
DEBUG: 2021/02/03 09:58:44.681654 WALG_STREAM_RESTORE_COMMAND=xbstream -x -C /var/lib/mysql
DEBUG: 2021/02/03 09:58:44.681657 WALG_MYSQL_BACKUP_PREPARE_COMMAND=xtrabackup --prepare --target-dir=/var/lib/mysql
DEBUG: 2021/02/03 09:58:44.681664 WALG_SWIFT_PREFIX=swift://db-1/
DEBUG: 2021/02/03 09:58:44.681677 WALG_STREAM_CREATE_COMMAND=xtrabackup --backup --user=*** --password=*** --stream=xbstream --datadir=/var/lib/mysql --galera-info
DEBUG: 2021/02/03 09:58:44.681681 WALG_COMPRESSION_METHOD=brotli
DEBUG: 2021/02/03 09:58:44.681683 OPLOG_PUSH_WAIT_FOR_BECOME_PRIMARY=false
DEBUG: 2021/02/03 09:58:44.681686 PGDATA=
DEBUG: 2021/02/03 09:58:44.681688 OPLOG_ARCHIVE_AFTER_SIZE=16777216
DEBUG: 2021/02/03 09:58:44.681691 WALG_AZ_PREFIX=
DEBUG: 2021/02/03 09:58:44.681694 WALG_SENTINEL_USER_DATA=
DEBUG: 2021/02/03 09:58:44.681696 SQLSERVER_BLOB_HOSTNAME=
DEBUG: 2021/02/03 09:58:44.681698 AWS_DEFAULT_REGION=
DEBUG: 2021/02/03 09:58:44.681701 SSH_PRIVATE_KEY_PATH=
DEBUG: 2021/02/03 09:58:44.681703 PGPASSFILE=
DEBUG: 2021/02/03 09:58:44.681706 AZURE_STORAGE_SAS_TOKEN=
DEBUG: 2021/02/03 09:58:44.681708 WALE_GPG_KEY_ID=
DEBUG: 2021/02/03 09:58:44.681710 OPLOG_PUSH_STATS_UPDATE_INTERVAL=30s
DEBUG: 2021/02/03 09:58:44.681719 WALG_TAR_SIZE_THRESHOLD=1073741823
DEBUG: 2021/02/03 09:58:44.681725 WALG_UPLOAD_QUEUE=2
DEBUG: 2021/02/03 09:58:44.681731 AWS_SECRET_ACCESS_KEY=
DEBUG: 2021/02/03 09:58:44.681735 WALG_USE_RATING_COMPOSER=false
DEBUG: 2021/02/03 09:58:44.681738 WALG_S3_PREFIX=
DEBUG: 2021/02/03 09:58:44.681740 WALG_USE_WAL_DELTA=false
DEBUG: 2021/02/03 09:58:44.681742 AWS_ROLE_SESSION_NAME=
DEBUG: 2021/02/03 09:58:44.681745 SSH_USERNAME=
DEBUG: 2021/02/03 09:58:44.681748 PGUSER=
DEBUG: 2021/02/03 09:58:44.681751 WALG_INTEGRITY_MAX_DELAYED_WALS=0
DEBUG: 2021/02/03 09:58:44.681753 YC_CSE_KMS_KEY_ID=
DEBUG: 2021/02/03 09:58:44.681756 AZURE_STORAGE_KEY=
DEBUG: 2021/02/03 09:58:44.681758 OPLOG_PITR_DISCOVERY_INTERVAL=
DEBUG: 2021/02/03 09:58:44.681761 AWS_DEFAULT_OUTPUT=
DEBUG: 2021/02/03 09:58:44.681764 HTTP_EXPOSE_PPROF=
DEBUG: 2021/02/03 09:58:44.681766 WALG_SSH_PREFIX=
DEBUG: 2021/02/03 09:58:44.681769 OPLOG_PUSH_STATS_EXPOSE_HTTP=
DEBUG: 2021/02/03 09:58:44.681771 AZURE_STORAGE_ACCOUNT=
DEBUG: 2021/02/03 09:58:44.681775 AWS_CA_BUNDLE=
DEBUG: 2021/02/03 09:58:44.681777 YC_SERVICE_ACCOUNT_KEY_FILE=
DEBUG: 2021/02/03 09:58:44.681780 WALG_PREVENT_WAL_OVERWRITE=false
DEBUG: 2021/02/03 09:58:44.681782 S3_ENDPOINT_PORT=
DEBUG: 2021/02/03 09:58:44.681785 SSH_PORT=
DEBUG: 2021/02/03 09:58:44.681788 WALG_MYSQL_BINLOG_REPLAY_COMMAND=
DEBUG: 2021/02/03 09:58:44.681791 WALG_MYSQL_BINLOG_DST=
DEBUG: 2021/02/03 09:58:44.681793 SQLSERVER_BLOB_KEY_FILE=
DEBUG: 2021/02/03 09:58:44.681796 AWS_CONFIG_FILE=
DEBUG: 2021/02/03 09:58:44.681798 WALG_GPG_KEY_ID=
DEBUG: 2021/02/03 09:58:44.681802 WALG_DELTA_MAX_STEPS=0
DEBUG: 2021/02/03 09:58:44.681804 WALG_S3_STORAGE_CLASS=
DEBUG: 2021/02/03 09:58:44.681807 OPLOG_ARCHIVE_TIMEOUT_INTERVAL=60s
DEBUG: 2021/02/03 09:58:44.681809 WALG_PG_WAL_SIZE=16
DEBUG: 2021/02/03 09:58:44.681811 WALG_MYSQL_SSL_CA=
DEBUG: 2021/02/03 09:58:44.681815 AWS_S3_FORCE_PATH_STYLE=
DEBUG: 2021/02/03 09:58:44.681817 WALE_S3_PREFIX=
DEBUG: 2021/02/03 09:58:44.681820 WALG_DOWNLOAD_CONCURRENCY=10
DEBUG: 2021/02/03 09:58:44.681822 WALG_GS_PREFIX=
DEBUG: 2021/02/03 09:58:44.681825 WALG_STORE_ALL_CORRUPT_BLOCKS=false
DEBUG: 2021/02/03 09:58:44.681829 MONGODB_URI=
DEBUG: 2021/02/03 09:58:44.681831 AWS_ACCESS_KEY_ID=
DEBUG: 2021/02/03 09:58:44.681836 HTTP_LISTEN=
DEBUG: 2021/02/03 09:58:44.681839 WALG_S3_SSE=
DEBUG: 2021/02/03 09:58:44.681842 AWS_SHARED_CREDENTIALS_FILE=
DEBUG: 2021/02/03 09:58:44.681845 WALG_PGP_KEY_PASSPHRASE=
DEBUG: 2021/02/03 09:58:44.681847 OPLOG_PUSH_PRIMARY_CHECK_INTERVAL=30s
DEBUG: 2021/02/03 09:58:44.681850 MONGODB_LAST_WRITE_UPDATE_INTERVAL=3s
DEBUG: 2021/02/03 09:58:44.681852 WALG_FILE_PREFIX=
DEBUG: 2021/02/03 09:58:44.681856 WALG_PGP_KEY=
DEBUG: 2021/02/03 09:58:44.681859 PGPASSWORD=
DEBUG: 2021/02/03 09:58:44.681861 AWS_REGION=
DEBUG: 2021/02/03 09:58:44.681864 WALG_VERIFY_PAGE_CHECKSUMS=false
DEBUG: 2021/02/03 09:58:44.681866 WALG_CSE_KMS_ID=
DEBUG: 2021/02/03 09:58:44.681870 WALG_USE_REVERSE_UNPACK=false
DEBUG: 2021/02/03 09:58:44.681873 PGPORT=
DEBUG: 2021/02/03 09:58:44.681875 HTTP_EXPOSE_EXPVAR=
DEBUG: 2021/02/03 09:58:44.681878 WALG_AZURE_BUFFER_SIZE=
DEBUG: 2021/02/03 09:58:44.681880 SQLSERVER_BLOB_CERT_FILE=
DEBUG: 2021/02/03 09:58:44.681884 PGDATABASE=
DEBUG: 2021/02/03 09:58:44.681887 WALG_UPLOAD_CONCURRENCY=16
DEBUG: 2021/02/03 09:58:44.681889 OPLOG_PUSH_STATS_LOGGING_INTERVAL=30s
DEBUG: 2021/02/03 09:58:44.681892 WALG_S3_CA_CERT_FILE=
DEBUG: 2021/02/03 09:58:44.681894 WALG_SLOTNAME=
DEBUG: 2021/02/03 09:58:44.681897 SSH_PASSWORD=
DEBUG: 2021/02/03 09:58:44.681900 PGHOST=
DEBUG: 2021/02/03 09:58:44.681902 WALG_MYSQL_TAKE_BINLOGS_FROM_MASTER=
DEBUG: 2021/02/03 09:58:44.681905 WALG_CSE_KMS_REGION=
DEBUG: 2021/02/03 09:58:44.681907 WALG_UPLOAD_DISK_CONCURRENCY=1
DEBUG: 2021/02/03 09:58:44.681911 AWS_SESSION_TOKEN=
DEBUG: 2021/02/03 09:58:44.681914 SQLSERVER_CONNECTION_STRING=
DEBUG: 2021/02/03 09:58:44.681916 AWS_ENDPOINT=
DEBUG: 2021/02/03 09:58:44.681919 WALG_SKIP_REDUNDANT_TARS=false
DEBUG: 2021/02/03 09:58:44.681921 GOOGLE_APPLICATION_CREDENTIALS=
DEBUG: 2021/02/03 09:58:44.681925 PGSSLMODE=
DEBUG: 2021/02/03 09:58:44.681927 WALG_DISK_RATE_LIMIT=
DEBUG: 2021/02/03 09:58:44.681930 TOTAL_BG_UPLOADED_LIMIT=32
DEBUG: 2021/02/03 09:58:44.681932 OPLOG_PUSH_STATS_ENABLED=
DEBUG: 2021/02/03 09:58:44.681935 WALG_AZURE_MAX_BUFFERS=
DEBUG: 2021/02/03 09:58:44.681941 WALG_PGP_KEY_PATH=
DEBUG: 2021/02/03 09:58:44.681944 WALG_S3_SSE_KMS_ID=
DEBUG: 2021/02/03 09:58:44.681947 WALG_S3_MAX_PART_SIZE=
DEBUG: 2021/02/03 09:58:44.681953 GOMAXPROCS=
DEBUG: 2021/02/03 09:58:44.681960 AWS_PROFILE=
DEBUG: 2021/02/03 09:58:44.681966 WALG_NETWORK_RATE_LIMIT=
DEBUG: 2021/02/03 09:58:44.681973 S3_ENDPOINT_SOURCE=
DEBUG: 2021/02/03 09:58:44.681979 WALG_DELTA_ORIGIN=
DEBUG: 2021/02/03 09:58:44.758574 HandleBackupFetch(stream_20210202T121417Z, folder,)
fatal error: runtime: out of memory
 
runtime stack:
runtime.throw(0x25f7d90, 0x16)
	/snap/go/6745/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc204000000, 0x200000000, 0x390f978)
	/snap/go/6745/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x38f2360, 0x200000000, 0xf4f197, 0x38f2368)
	/snap/go/6745/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x38f2360, 0x100000, 0x0)
	/snap/go/6745/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x38f2360, 0x100000, 0x7f4b74df0100, 0x390f988, 0x18aa7af74c1d6)
	/snap/go/6745/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
	/snap/go/6745/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x38f2360, 0x100000, 0xc001150101, 0xc00115e000)
	/snap/go/6745/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x1fffffe00, 0xc000000101, 0x0)
	/snap/go/6745/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
	/snap/go/6745/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
	/snap/go/6745/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/snap/go/6745/src/runtime/proc.go:1116
 
goroutine 1 [running]:
runtime.systemstack_switch()
	/snap/go/6745/src/runtime/asm_amd64.s:330 fp=0xc000c3f5a0 sp=0xc000c3f598 pc=0xf909e0
runtime.mallocgc(0x1fffffe00, 0x2224940, 0x58b01, 0x58b00)
	/snap/go/6745/src/runtime/malloc.go:1070 +0x938 fp=0xc000c3f640 sp=0xc000c3f5a0 pc=0xf31038
runtime.makeslice(0x2224940, 0x1fffffe00, 0x1fffffe00, 0x0)
	/snap/go/6745/src/runtime/slice.go:98 +0x6c fp=0xc000c3f670 sp=0xc000c3f640 pc=0xf71c4c
bytes.makeSlice(0x1fffffe00, 0x0, 0x0, 0x0)
	/snap/go/6745/src/bytes/buffer.go:229 +0x73 fp=0xc000c3f6b0 sp=0xc000c3f670 pc=0x1022dd3
bytes.(*Buffer).grow(0xc0005b78c0, 0x200, 0x58b08)
	/snap/go/6745/src/bytes/buffer.go:142 +0x156 fp=0xc000c3f700 sp=0xc000c3f6b0 pc=0x10226f6
bytes.(*Buffer).ReadFrom(0xc0005b78c0, 0x2821ea0, 0xc000655b00, 0x7f4b7405d478, 0xc0005b78c0, 0xc000918d01)
	/snap/go/6745/src/bytes/buffer.go:202 +0x48 fp=0xc000c3f770 sp=0xc000c3f700 pc=0x1022ba8
io.copyBuffer(0x28208e0, 0xc0005b78c0, 0x2821ea0, 0xc000655b00, 0x0, 0x0, 0x0, 0x0, 0xc000655b00, 0xc000bf46f0)
	/snap/go/6745/src/io/io.go:395 +0x2ff fp=0xc000c3f7e8 sp=0xc000c3f770 pc=0xfd8f7f
io.Copy(...)
	/snap/go/6745/src/io/io.go:368
github.com/ncw/swift.(*Connection).ObjectGet(0xc0002ffa40, 0xc00005e42a, 0x2a, 0xc000918d00, 0x31, 0x28208e0, 0xc0005b78c0, 0x1, 0x0, 0xc000bf46f0, ...)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/ncw/swift/swift.go:1798 +0x173 fp=0xc000c3f880 sp=0xc000c3f7e8 pc=0x1fbc6f3
github.com/ncw/swift.(*Connection).ObjectGetBytes(0xc0002ffa40, 0xc00005e42a, 0x2a, 0xc000918d00, 0x31, 0xc0005d45d0, 0x21, 0x21, 0xc000b9f9d0, 0xf75bfe)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/ncw/swift/swift.go:1807 +0x9c fp=0xc000c3f8f8 sp=0xc000c3f880 pc=0x1fbc81c
github.com/wal-g/storages/swift.(*Folder).ReadObject(0xc00007d700, 0xc0005d45d0, 0x21, 0x25de3f8, 0x2, 0xc0005d45d0, 0x21)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/swift/folder.go:123 +0xef fp=0xc000c3fa20 sp=0xc000c3f8f8 pc=0x1fc62ef
github.com/wal-g/wal-g/internal.TryDownloadFile(0x2863d80, 0xc00007d700, 0xc0005d45d0, 0x21, 0xc0005d45d0, 0x21, 0xc000394100, 0x0, 0x0)
	/root/go/src/github.com/wal-g/wal-g/internal/wal_fetch_handler.go:126 +0x4c fp=0xc000c3fa88 sp=0xc000c3fa20 pc=0x1fd45ec
github.com/wal-g/wal-g/internal.downloadAndDecompressStream(0xc000c3fbf0, 0x283f020, 0xc0005b71a0, 0x0, 0x0)
	/root/go/src/github.com/wal-g/wal-g/internal/stream_fetch_helper.go:43 +0x12f fp=0xc000c3fb50 sp=0xc000c3fa88 pc=0x1fd278f
github.com/wal-g/wal-g/internal.GetCommandStreamFetcher.func1(0x2863d80, 0xc00007d6c0, 0x2863d80, 0xc00007d700, 0x7ffd2b5db448, 0x17, 0x0)
	/root/go/src/github.com/wal-g/wal-g/internal/backup_fetch_handler.go:92 +0x199 fp=0xc000c3fbe0 sp=0xc000c3fb50 pc=0x1fd5ad9
github.com/wal-g/wal-g/internal.HandleBackupFetch(0x2863d80, 0xc00007d6c0, 0x7ffd2b5db448, 0x17, 0xc000b4e220)
	/root/go/src/github.com/wal-g/wal-g/internal/backup_fetch_handler.go:126 +0x1d6 fp=0xc000c3fc78 sp=0xc000c3fbe0 pc=0x1fc97f6
github.com/wal-g/wal-g/internal/databases/mysql.HandleBackupFetch(0x2863d80, 0xc00007d6c0, 0x7ffd2b5db448, 0x17, 0xc00021de40, 0xc000718000)
	/root/go/src/github.com/wal-g/wal-g/internal/databases/mysql/backup_fetch_handler.go:12 +0x65 fp=0xc000c3fcc8 sp=0xc000c3fc78 pc=0x1ff7925
github.com/wal-g/wal-g/cmd/mysql.glob..func3(0x37abd60, 0xc00007b130, 0x1, 0x1)
	/root/go/src/github.com/wal-g/wal-g/cmd/mysql/backup_fetch.go:28 +0x150 fp=0xc000c3fd68 sp=0xc000c3fcc8 pc=0x20034b0
github.com/spf13/cobra.(*Command).execute(0x37abd60, 0xc00007af70, 0x1, 0x1, 0x37abd60, 0xc00007af70)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2 fp=0xc000c3fe40 sp=0xc000c3fd68 pc=0x1116a42
github.com/spf13/cobra.(*Command).ExecuteC(0x37abae0, 0xf6a16a, 0x37ccb40, 0xc000000180)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b fp=0xc000c3ff18 sp=0xc000c3fe40 pc=0x111766b
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/mysql.Execute()
	/root/go/src/github.com/wal-g/wal-g/cmd/mysql/mysql.go:35 +0x31 fp=0xc000c3ff78 sp=0xc000c3ff18 pc=0x2002e91
main.main()
	/root/go/src/github.com/wal-g/wal-g/main/mysql/main.go:8 +0x25 fp=0xc000c3ff88 sp=0xc000c3ff78 pc=0x20056e5
runtime.main()
	/snap/go/6745/src/runtime/proc.go:204 +0x209 fp=0xc000c3ffe0 sp=0xc000c3ff88 pc=0xf5cf29
runtime.goexit()
	/snap/go/6745/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000c3ffe8 sp=0xc000c3ffe0 pc=0xf927c1
 
goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00034e690)
	/root/go/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
	/root/go/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
 
goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7f4b74539ae8, 0x72, 0x2834060)
	/snap/go/6745/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00032acd8, 0x72, 0x2834001, 0x37be1d0, 0x0)
	/snap/go/6745/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/6745/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00032acc0, 0xc0005aa200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/snap/go/6745/src/internal/poll/fd_unix.go:159 +0x1a5
os.(*File).read(...)
	/snap/go/6745/src/os/file_posix.go:31
os.(*File).Read(0xc000394198, 0xc0005aa200, 0x200, 0x200, 0x0, 0x7f4b7405d478, 0xc000412ea0)
	/snap/go/6745/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc0005b71d0, 0x2832100, 0xc000394198, 0x7f4b7405d478, 0xc0005b71d0, 0x1)
	/snap/go/6745/src/bytes/buffer.go:204 +0xb1
io.copyBuffer(0x28208e0, 0xc0005b71d0, 0x2832100, 0xc000394198, 0x0, 0x0, 0x0, 0xc000412fa8, 0x0, 0x0)
	/snap/go/6745/src/io/io.go:395 +0x2ff
io.Copy(...)
	/snap/go/6745/src/io/io.go:368
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0xc00040e300)
	/snap/go/6745/src/os/exec/exec.go:311 +0x65
os/exec.(*Cmd).Start.func1(0xc00021de40, 0xc000970d80)
	/snap/go/6745/src/os/exec/exec.go:441 +0x27
created by os/exec.(*Cmd).Start
	/snap/go/6745/src/os/exec/exec.go:440 +0x629
 
goroutine 27 [select]:
os/exec.(*Cmd).Start.func2(0xc00021de40)
	/snap/go/6745/src/os/exec/exec.go:449 +0xd5
created by os/exec.(*Cmd).Start
	/snap/go/6745/src/os/exec/exec.go:448 +0x6c5
 
goroutine 25 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc0008a965c, 0x9545, 0xffffffffffffffff, 0x0, 0xb)
	/snap/go/6745/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc0008a965c, 0x9545, 0x9545, 0xc000088560, 0xc000088550, 0xc0005ea1e0)
	/snap/go/6745/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
	/snap/go/6745/src/syscall/syscall_unix.go:187
internal/poll.(*FD).Read.func1(0x72, 0x0, 0x0)
	/snap/go/6745/src/internal/poll/fd_unix.go:155 +0x4c
internal/poll.ignoringEINTR(0xc000088578, 0x72, 0xdef1641ea3e95900, 0x0)
	/snap/go/6745/src/internal/poll/fd_unix.go:567 +0x27
internal/poll.(*FD).Read(0xc00039ee80, 0xc0008a965c, 0x9545, 0x9545, 0x0, 0x0, 0x0)
	/snap/go/6745/src/internal/poll/fd_unix.go:155 +0x13e
net.(*netFD).Read(0xc00039ee80, 0xc0008a965c, 0x9545, 0x9545, 0x203000, 0x11dd37b, 0xc00083cf60)
	/snap/go/6745/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000114050, 0xc0008a965c, 0x9545, 0x9545, 0x0, 0x0, 0x0)
	/snap/go/6745/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc003a98140, 0xc0008a965c, 0x9545, 0x9545, 0xc0008a8000, 0xc0008affcc, 0xc000088730)
	/snap/go/6745/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00083d080, 0x2820ac0, 0xc003a98140, 0xf2e785, 0x22fd420, 0x257a7c0)
	/snap/go/6745/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00083ce00, 0x2831d40, 0xc000114050, 0x3fe6, 0xc000114050, 0x0)
	/snap/go/6745/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00083ce00, 0x0, 0x0, 0xc000088c30)
	/snap/go/6745/src/crypto/tls/conn.go:653 +0x78c
crypto/tls.(*Conn).readRecord(...)
	/snap/go/6745/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00083ce00, 0xc0005ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/snap/go/6745/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc00032aa20, 0xc0005de3b8, 0x9, 0x9, 0xfa815c, 0xc0005e3900, 0x2250)
	/snap/go/6745/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x2820840, 0xc00032aa20, 0xc0005de3b8, 0x9, 0x9, 0x9, 0xc0005e38f0, 0x26491c8, 0xc0005e38e8)
	/snap/go/6745/src/io/io.go:314 +0x87
io.ReadFull(...)
	/snap/go/6745/src/io/io.go:333
net/http.http2readFrameHeader(0xc0005de3b8, 0x9, 0x9, 0x2820840, 0xc00032aa20, 0x0, 0x0, 0xc003a96090, 0x0)
	/snap/go/6745/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0005de380, 0xc003a96090, 0x0, 0x0, 0x0)
	/snap/go/6745/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000088fa8, 0x0, 0x0)
	/snap/go/6745/src/net/http/h2_bundle.go:8251 +0x8d
net/http.(*http2ClientConn).readLoop(0xc00040e300)
	/snap/go/6745/src/net/http/h2_bundle.go:8179 +0x6f
created by net/http.(*http2Transport).newClientConn
	/snap/go/6745/src/net/http/h2_bundle.go:7175 +0x685`
