### ISSUE TITLE
[Feature Request] Add additional metadata file to pg WAL 

### ISSUE THREAD

**Issue by rjayakri** [wal-g/wal-g#865]
##  Issue description

- Currently wal-list provides information about missing wal logs in specific timeline. But does not provide clarity of till what time PITR is possible, since the time of wal generation is missing.

- Often backups are moved to external media or alternate storage locations as time passes (NFS -> tape, or S3 to cheaper longterm storage class). In such scenarios it is important to have access to this metadata so that one can identify specific backups/wals required for a given PITR restore request to specify in the recovery_target_time. 

## Proposed solution

To provide a complete list of files for PITR, wal-push will be enhanced to add  metadata details along with the WAL backup. An additional json file will be created for every WAL and uploaded to the default metadata (WALG_FILE_PREFIX or WALG_S3_PREFIX) store with the following information.

The information is similar to "StartTime" and "FinishTime" of the backup metadata.json (https://github.com/wal-g/wal-g/blob/master/internal/backup_sentinel_dto.go#L32-L33)

File Name : 0000000200000000000000A8.json
Contents: 
{
  "CreatedTime": "2020-10-30T03:24:20.465889208Z",
  "LastWrittenTime": "2020-10-30T03:24:20.465889208Z",
  "DatetimeFormat": "%Y-%m-%dT%H:%M:%S.%fZ"
}

The CreatedTime => access time and LastWrittenTime => modify time of the wal-file generated by Postgres. 
Additional fields like timeline, name, size can be added. But most of it can be derived from the wal-file name.

Happy to help make updates and add tests as requested.

**Comment by x4m** [comment]
Hi! Thanks for your proposal.
Currently, we push WAL-delta files which describe many WAL files at once. Maybe we could use the same approach for WAL metadata?

**Comment by rjayakri** [comment]
@x4m 
Could you please elaborate on the WAL-delta files. Is this the current logic where multiple WAL files are uploaded at once by the archive_command. 
Thanks

**Comment by rjayakri** [comment]
For example , 
following will the files under the wal_005 directory
```
-rw-------  1 user  staff      167 Feb  3 21:37 0000000100000000000000B8.json
-rw-------  1 user  staff  1495286 Feb  3 21:37 0000000100000000000000B8.lz4
-rw-------  1 user  staff      167 Feb  3 21:37 0000000100000000000000B7.json
-rw-------  1 user  staff  1495435 Feb  3 21:37 0000000100000000000000B7.lz4
-rw-------  1 user  staff      167 Feb  3 21:37 0000000100000000000000B6.json
-rw-------  1 user  staff  1494998 Feb  3 21:37 0000000100000000000000B6.lz4
-rw-------  1 user  staff      167 Feb  3 21:37 0000000100000000000000B2.json
-rw-------  1 user  staff  6320262 Feb  3 21:37 0000000100000000000000B2.lz4
```

**Comment by x4m** [comment]
@rjayakri sorry for the late reply.
Can we have instead of 0000000100000000000000B8.json, 0000000100000000000000B9.json, 0000000100000000000000BA.json etc just one 0000000100000000000000B.json ? This is merely an idea to save users money on PUTs.
One more important consideration. Currently WAL-G works fine if metadata is absent. We must preserve this. Also, I think metadata upload shoud be configurable and off by default (to avoid increasing users bills again).

Besides this, I think your idea totally makes sense and PR would be welcomed.

**Comment by rjayakri** [comment]
@x4m  Thanks

I will introduce a variable (WALG_WAL_METADATA), if the parameter exists it will consider creating the metadata for wal files, if not it will fallback to the default option.

Also the WALG_WAL_METADATA can have "BULK" and "INDIVIDUAL" parameters, where "BULK" can have consolidated metadata( as you have mentioned) and "INDIVIDUAL" can have one file at a time (Depends on how users want to configure it) 

Regarding the "BULK" , currently the process wal-g wal-push runs for one file at a time (some times it also picks up remaining wal files parallel in the pg_wal directory) . In this case, should I use ${PGDATA}/walg_data directory to keep the temporary metadata for wal log before consolidating and uploading it to WALG storage.  Could you please clarify on this approach. Thanks
