### ISSUE TITLE
Add a -v or --version flag to get the version

### ISSUE THREAD

**Issue by rdunklau** [wal-g/wal-g#87]
Would it be possible to add the version information into the binary itself, and add an option to get it ?
Thanks !

**Comment by x4m** [comment]
Sure, will do this before next release.

**Comment by fayak** [comment]
bump

**Comment by x4m** [comment]
@fayak Hi!
That's already how it works now

**Comment by fayak** [comment]
@x4m Sorry mate ! I'm using kubedb and it seems that they haven't updated wall-g since a long time !
Sorry for the bother

**Comment by x4m** [comment]
@fayak version acquisition was actually broken in the last commit, thanks! We never released the broken version though.
