### ISSUE TITLE
Failed to fetch backup: No backups found on GCP

### ISSUE THREAD

**Issue by wojcikm** [wal-g/wal-g#874]
I have following error:

``` 
bash-4.4$ WALG_GS_PREFIX='gs://bucket_name/' wal-g backup-fetch /var/lib/pgsql/11/data/ LATEST
ERROR: 2021/02/12 09:55:17.040164 Failed to fetch backup: No backups found
bash-4.4$ wal-g --version
wal-g version devel     devel   devel   PostgreSQL
```

But when using `wal-e` on the same host, it works:

``` 
bash-4.4$ WALE_GS_PREFIX='gs://bucket_name/' wal-e backup-fetch /var/lib/pgsql/11/data/ LATEST
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
[...]
```

edit: base backup was done using `wal-e`, maybe that's the problem?

**Comment by x4m** [comment]
Hi! for most use-cases WAL-G should be compatible with WAL-E. Please try WALG_GS_PREFIX='gs://bucket_name' ?

**Comment by x4m** [comment]
There was an issue with slashes in WAL-G-WAL-E-in-GCP compatibility... but I do not remember shoud you add one or should you remove one.. 
There is a setting GCS_NORMALIZE_PREFIX. Please try to flip it...

**Comment by wojcikm** [comment]
When switched and used `wal-g` to make base backup - it works. So, use `wal-g` when creating base backups.

**Comment by x4m** [comment]
Thanks, @wojcikm !
We aim to support WAL-E\WAL-G setup, many users want to switch restores first. And this works fine for S3.
But S3 treats bucket path not exactly as URI. E.g. "bucket/folder" and "bucket//folder" are both allowed different locations.
WAL-G normalizes URIs before accessing while WAL-E does not. And from time to time we encounter cases when backups made by WAL-E in GCS are invisible to WAL-G. This can be tweaked to working setup, but if you are OK with switching to WAL-G - I think it's a good option. Keep in mind that storage still has old backups made by WAL-E. They will not be deleted by the WAL-G retention policy.

**Comment by ratclick** [comment]
Hello, its been a year so this might be stale, but to add some clarity

> There was an issue with slashes in WAL-G-WAL-E-in-GCP compatibility... but I do not remember shoud you add one or should you remove one.. There is a setting GCS_NORMALIZE_PREFIX. Please try to flip it...

while using the WAL_E backup from Google Cloud Storage, i had to set the wal-g flag --gcs-normalize-prefix to false 
` envdir /etc/wal-e.d/env/ wal-g --gcs-normalize-prefix false st ls`

I set the WALG_GS_PREFIX as "gs://postgres12-wal-backup//db1" (i used the envdir way by creating a file and storing this value in it but setting the flag --walg-gs-prefix works too)
