### ISSUE TITLE
ERROR: function pg_start_backup(unknown, boolean, boolean) does not exist (SQLSTATE 42883)

### ISSUE THREAD

**Issue by mudarisov566** [wal-g/wal-g#88]
postgres@beta-02:~/.ssh$ envdir /etc/wal-e.d/env wal-g backup-push /var/lib/postgresql
BUCKET: testbacku1
SERVER: 
2018/04/06 16:47:19 ERROR: function pg_start_backup(unknown, boolean, boolean) does not exist (SQLSTATE 42883)
StartBackup: pg_start_backup() failed
github.com/wal-g/wal-g.(*Bundle).StartBackup
        /home/travis/gopath/src/github.com/wal-g/wal-g/connect.go:75
github.com/wal-g/wal-g.HandleBackupPush
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:549
main.main
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:107
runtime.main
        /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/proc.go:185
runtime.goexit
        /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197

Strace:
postgres@beta-02:~/.ssh$ strace -s 256 -e write envdir /etc/wal-e.d/env wal-g backup-push /var/lib/postgresql
write(1, "BUCKET: testbacku1\n", 19BUCKET: testbacku1
)    = 19
write(1, "SERVER: \n", 9SERVER: 
)               = 9
write(3, "\0\0\0\10\4\322\26/", 8)      = 8
write(3, "\0\0\0\27\0\3\0\0user\0postgres\0\0", 23) = 23
write(3, "P\0\0\0\332\0select t.oid, t.typname\nfrom pg_type t\nleft join pg_type base_type on t.typelem=base_type.oid\nwhere (\n\t  t.typtype in('b', 'p', 'r', 'e')\n\t  and (base_type.oid is null or base_type.typtype in('b', 'p', 'r'))\n\t)\0\0\0D\0\0\0\6S\0S\0\0\0\4", 231) = 231
write(3, "B\0\0\0\20\0\0\0\0\0\0\0\2\0\1\0\1E\0\0\0\t\0\0\0\0\0S\0\0\0\4", 32) = 32
write(3, "P\0\0\0\31\0show archive_mode\0\0\0D\0\0\0\6S\0S\0\0\0\4", 38) = 38
write(3, "B\0\0\0\16\0\0\0\0\0\0\0\1\0\1E\0\0\0\t\0\0\0\0\0S\0\0\0\4", 30) = 30
write(3, "P\0\0\0\34\0show archive_command\0\0\0D\0\0\0\6S\0S\0\0\0\4", 41) = 41
write(3, "B\0\0\0\16\0\0\0\0\0\0\0\1\0\1E\0\0\0\t\0\0\0\0\0S\0\0\0\4", 30) = 30
write(3, "P\0\0\0;\0select (current_setting('server_version_num'))::int\0\0\0D\0\0\0\6S\0S\0\0\0\4", 72) = 72
write(3, "B\0\0\0\16\0\0\0\0\0\0\0\1\0\1E\0\0\0\t\0\0\0\0\0S\0\0\0\4", 30) = 30
write(3, "P\0\0\0\260\0SELECT case when pg_is_in_recovery() then '' else (pg_xlogfile_name_offset(lsn)).file_name end, lsn::text, pg_is_in_recovery() FROM pg_start_backup($1, true, false) lsn\0\0\0D\0\0\0\6S\0S\0\0\0\4", 189) = 189
write(2, "2018/04/06 16:47:39 ERROR: function pg_start_backup(unknown, boolean, boolean) does not exist (SQLSTATE 42883)\nStartBackup: pg_start_backup() failed\ngithub.com/wal-g/wal-g.(*Bundle).StartBackup\n\t/home/travis/gopath/src/github.com/wal-g/wal-g/connect.go:75\n"..., 6212018/04/06 16:47:39 ERROR: function pg_start_backup(unknown, boolean, boolean) does not exist (SQLSTATE 42883)
StartBackup: pg_start_backup() failed
github.com/wal-g/wal-g.(*Bundle).StartBackup
        /home/travis/gopath/src/github.com/wal-g/wal-g/connect.go:75
github.com/wal-g/wal-g.HandleBackupPush
        /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:549
main.main
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:107
runtime.main
        /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/proc.go:185
runtime.goexit
        /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
) = 621
+++ exited with 1 +++

postgres=# select (current_setting('server_version_num'));
 current_setting 
-----------------
 90412
(1 row)

**Comment by x4m** [comment]
Hi! Thanks for the report!
Support for 9.4 was added at #38 but it is not in current release yet.

**Comment by x4m** [comment]
I'm closing this now. Feel free to create new issues if you will have questions
