### ISSUE TITLE
user/group permission are not the same on backup-fetch

### ISSUE THREAD

**Issue by xshadowlegendx** [wal-g/wal-g#883]
hello i am developing dockerized [wal-g-sidecar](https://gitlab.com/ShadowLegend/wal-g-sidecar) for personal project. So far I am testing with `wal-push` and `backup-push` and they seems to be working and currently testing with `backup-fetch`. 

so after successsful `backup-fetch`, the user/group permission on data directory seems to be wrong or is it supposed to belongs to whoever fetch and extract them? the user/group permission are root in this case and symbolic link of `pg_wal` does not seems to be there as well and postgres container not able to read the data directory. I tried to create postgres user, link `pg_wal` and `chown -R postgres:postgres /var/lib/postgresql/data` and then restarting postgres container and it is working fine back and data seems to properly restored as well.

I went and check on `wal-e` part and after backup-fetch, the data directory does have correct user/group permission and `pg_wal` with correct link.

so my question is that is it not supposed to retain same user/group permission aftering `backup-fetch` or same behavior as  `wal-e` or the tar partitions supposed to retain same user/group permission?

**Comment by x4m** [comment]
Hi! As far as I know, WAL-G does not care about permissions much.
https://github.com/wal-g/wal-g/search?q=OpenFile
It's not clear to my why it should care? Just run it under ```postgres``` user.

**Comment by xshadowlegendx** [comment]
hello @x4m, thanks for clarify, if so then I think run it under `postgres` user or chown should be it then :)
