### ISSUE TITLE
Make S3 parameter MaxRetries configurable to avoid unnecessary waiting for unavailable S3-compatible storage

### ISSUE THREAD

**Issue by alyarskiy** [wal-g/wal-g#887]
Greetings! We are using wal-g in our setup with S3-compatible storage based on CEPH. Replicas managed by Patroni with wal-g as preferable method and fallback to basebackup.
While testing we have found that unavailable S3 leads to waiting on timeouts about 15-17 minutes with default values (`MaxRetries=15`).

Example timeouts:
```
Current:  2021-02-19 11:28:20.345168 +0300 MSK m=+30.015616865  Sleep: 46.488606ms
Current:  2021-02-19 11:28:50.403549 +0300 MSK m=+60.073339193  Sleep: 112.837344ms
Current:  2021-02-19 11:29:20.523714 +0300 MSK m=+90.192844099  Sleep: 174.290356ms
Current:  2021-02-19 11:29:50.705481 +0300 MSK m=+120.373950474  Sleep: 270.322504ms
Current:  2021-02-19 11:30:20.979665 +0300 MSK m=+150.647470707  Sleep: 876.866336ms
Current:  2021-02-19 11:30:51.865499 +0300 MSK m=+181.532628479  Sleep: 1.654165632s
Current:  2021-02-19 11:31:23.525341 +0300 MSK m=+213.191776743  Sleep: 2.17901984s
Current:  2021-02-19 11:31:55.71579 +0300 MSK m=+245.381520888  Sleep: 5.492845952s
Current:  2021-02-19 11:32:31.21047 +0300 MSK m=+280.875422756  Sleep: 13.362576128s
Current:  2021-02-19 11:33:14.581694 +0300 MSK m=+324.245697273  Sleep: 30.118050816s
Current:  2021-02-19 11:34:14.706409 +0300 MSK m=+384.369094457  Sleep: 55.077962752s
Current:  2021-02-19 11:35:39.796142 +0300 MSK m=+469.456963489  Sleep: 1m59.199647744s
Current:  2021-02-19 11:38:09.006728 +0300 MSK m=+618.664280726  Sleep: 2m15.637610496s
Current:  2021-02-19 11:40:54.647647 +0300 MSK m=+784.305237183  Sleep: 3m36.146380789s
Current:  2021-02-19 11:45:00.799189 +0300 MSK m=+1030.459699686  Sleep: 3m4.024158395s
```

Each try is - 30 second on connect timeout + exponential sleep in AWS-SDK code.

Making `MaxRetries` configurable will allow to avoid such a long waiting on unavailable S3-compatible storage.

**Comment by x4m** [comment]
Hi! This absolutely makes sense, PR would be appreciated.

**Comment by viggy28** [comment]
Ran into a similar problem with GCP where a bucket had a retention policy. so, wal-g was erroring with

`ERROR: 2021/03/04 07:24:15.541759 Failed to run a retriable func. Err: googleapi: Error 403: Object '<redacted>/000000010000000D0000002B.lz4_chunks/chunk0' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until <date redacted>, forbidden, retrying attempt 4`

One solution (in case if you use a bash script to call `wal-g` you can use the `timeout` utility. 

Anything I am missing here?

**Comment by x4m** [comment]
Maybe switch to WAL-G retention policy?

**Comment by usernamedt** [comment]
S3 max retries setting was introduced in https://github.com/wal-g/wal-g/pull/1148.
