### ISSUE TITLE
wal-g binlog-replay for MySQL is unsafe by default

### ISSUE THREAD

**Issue by jstaf** [wal-g/wal-g#888]
WAL-G is applying binlogs one at a time during MySQL PITR restores, which is not safe. From https://dev.mysql.com/doc/refman/5.7/en/mysqlbinlog.html#option_mysqlbinlog_version it is not safe to replay binlogs one at a time, they need to all be processed in a single session:

>  When mysqlbinlog is invoked with the --start-position option, it displays only those events with an offset in the binary log greater than or equal to a given position (the given position must match the start of one event). It also has options to stop and start when it sees an event with a given date and time. This enables you to perform point-in-time recovery using the --stop-datetime option (to be able to say, for example, “roll forward my databases to how they were today at 10:30 a.m.”).
>
> If you have more than one binary log to execute on the MySQL server, the safe method is to process them all using a single connection to the server. Here is an example that demonstrates what may be unsafe:
>
> mysqlbinlog binlog.000001 | mysql -u root -p # DANGER!!
> mysqlbinlog binlog.000002 | mysql -u root -p # DANGER!!
>
> Processing binary logs this way using multiple connections to the server causes problems if the first log file contains a CREATE TEMPORARY TABLE statement and the second log contains a statement that uses the temporary table. When the first mysql process terminates, the server drops the temporary table. When the second mysql process attempts to use the table, the server reports “unknown table.”
>
> To avoid problems like this, use a single mysql process to execute the contents of all binary logs that you want to process.

Though this ideally would require a code fix (so that WAL-G is applying the output of mysqlbinlog in a single MySQL session), a workaround is to change the `wal-g binlog-replay` documentation:

```bash
# unsafe
WALG_MYSQL_BINLOG_REPLAY_COMMAND='mysqlbinlog --stop-datetime="$WALG_MYSQL_BINLOG_END_TS" "$WALG_MYSQL_CURRENT_BINLOG" | mysql'
```

Should be changed to this:

```bash
WALG_MYSQL_BINLOG_REPLAY_COMMAND='mysqlbinlog --stop-datetime="$WALG_MYSQL_BINLOG_END_TS" "$WALG_MYSQL_CURRENT_BINLOG" >> /var/lib/mysql/pitr.sql'
```

And then the PITR documentation should be changed to use the new procedure:

```bash
# create a single "pitr.sql" dump to use for restore and apply it in a single session
wal-g binlog-replay --since "backup_name" --until "2006-01-02T15:04:05Z07:00"
mysql < /var/lib/mysql/pitr.sql
```

**Comment by x4m** [comment]
Thanks @jstaf ! Having all binlogs on file system simultaneously does not seem like a very robust option. If you restore PITR from backup made before the stone age, you quickly run out of space before even applying something...
Once again, I don't feel confident enough, @mialinx can you please take a look?

**Comment by mialinx** [comment]
On the other hand using temp files may cause you to run out a disk space...
`WALG_MYSQL_BINLOG_REPLAY_COMMAND` was introduced just to avoid dealing with such nuances.

We will update the README

**Comment by jstaf** [comment]
Thanks! One more potential solution may be to have WAL-G itself apply the binlog.

You can still use this as the replay command, but have it stream stdout to WAL-G, which applies the binlog directly through it's own MySQL connection. 

```bash
# new replay command just streams to stdout
mysqlbinlog --stop-datetime="$WALG_MYSQL_BINLOG_END_TS" "$WALG_MYSQL_CURRENT_BINLOG"
# wal-g applies the mysqlbinlog stdout itself instead of streaming to mysql
```
