### ISSUE TITLE
S3 only

### ISSUE THREAD

**Issue by stub42** [wal-g/wal-g#9]
Will the scope of WAL-G remain S3 only, or should it grow support for OpenStack Swift and Azure like WAL-E ?

**Comment by fdr** [comment]
Depends on what people submit. A patch with good and fairly comprehensive and consistent test methodology with the other backends is more likely to be accepted.

**Comment by sammcj** [comment]
We were interested in WAL-G for non-s3 use as well.

**Comment by andrewgy8** [comment]
Excuse the following ignorance as I know nearly nothing about the code behind wal-e or wal-g, but  how much effort would this take? Would it be more-or-less porting existing wal-e python code thats used for Azure backups to Go?  Or would the owners want a novel approach to fetching backups, WAL logs, etc. that keeps the speed of wal-g up to snuff? 

Again, sorry for the seemingly stupid question. We are using wal-e in production and forsee a shift in the near future to a faster system and wal-g looks like a good solution.
