### ISSUE TITLE
backup-push fails

### ISSUE THREAD

**Issue by gregor-rayman** [wal-g/wal-g#93]
When I run backup-push after a while it fails with the following stack trace:

```
2018/04/25 20:38:09 lstat 10/main/base/16400/88931132: no such file or directory
TarWalker: walk failed
github.com/wal-g/wal-g.(*Bundle).TarWalker
	/home/travis/gopath/src/github.com/wal-g/wal-g/walk.go:33
github.com/wal-g/wal-g.(*Bundle).TarWalker-fm
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:546
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:372
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:376
path/filepath.walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:376
path/filepath.Walk
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/path/filepath/path.go:398
github.com/wal-g/wal-g.HandleBackupPush
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:546
main.main
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:107
runtime.main
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/runtime/proc.go:185
runtime.goexit
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/runtime/asm_amd64.s:2197
```

The version of PostgreSql is:

PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

**Comment by x4m** [comment]
Hi! I suspect that you are using WAL-G version 0.1.4. It is known bug #65 which was fixed in 0.1.7

**Comment by x4m** [comment]
Starting from next release there will be flag -v to get version and -vv to get build time and revision.
The current release is https://github.com/wal-g/wal-g/releases/tag/v0.1.7
There is no easy way to to get version from binary.
It is certain that you are not using 0.1.7 since in 0.1.7
```github.com/wal-g/wal-g.HandleBackupPush
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:546```
is not HandleBackupPush call https://github.com/wal-g/wal-g/blob/v0.1.7/commands.go#L546

**Comment by gregor-rayman** [comment]
I have just tested it again making sure I have the latest release and the error is gone :) Thanks!

**Comment by x4m** [comment]
Feel free to report anything suspicious. When dealing with backup software all kinds of paranoia are justified.

**Comment by gregor-rayman** [comment]
I have tested the `backup-fetch` after a successful `backup-push`, but unfortunately it failed with the following stack trace:

```
2018/04/27 12:18:33 unexpected EOF
Interpret: copy failed
github.com/wal-g/wal-g.(*FileTarInterpreter).Interpret
	/home/travis/gopath/src/github.com/wal-g/wal-g/tar.go:86
github.com/wal-g/wal-g.extractOne
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:51
github.com/wal-g/wal-g.ExtractAll.func2.3
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
runtime.goexit
	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
extractOne: Interpret failed
github.com/wal-g/wal-g.extractOne
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:53
github.com/wal-g/wal-g.ExtractAll.func2.3
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
runtime.goexit
	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
```

The `backup-fetch` takes more than 4 hours, perhaps this error is intermittent and a re-try might work? If so, is there a way to instruct `wal-g` not to download the already downloaded files?

**Comment by x4m** [comment]
@gregor-rayman there is new release 0.1.8 with better retries. Can I ask you to test it?

**Comment by gregor-rayman** [comment]
I will next week. Our regular backups are weekly on Mondays, so on Tuesday I will be able to test. Thanks!

**Comment by gregor-rayman** [comment]
The version 0.1.8 was able to download the backup withou any issue
