### ISSUE TITLE
walg backup-push stuck

### ISSUE THREAD

**Issue by v0112358** [wal-g/wal-g#939]
wal-g was stuck at `Calling pg_stop_backup()` 
I am using:
- wal-g version v0.2.19. 
- PostgreSQL 11.11. 
- GCS 
- wal-g was performed on slave.
- archive_command = '' (on slave).

wal-g messages:
```
INFO: 2021/04/24 22:08:20.573899 Doing full backup.
INFO: 2021/04/24 22:08:20.581842 Calling pg_start_backup()
INFO: 2021/04/24 22:08:20.683140 Walking ...
INFO: 2021/04/24 22:08:20.683361 Starting part 1 ...
INFO: 2021/04/24 22:08:20.685212 Starting part 2 ...
INFO: 2021/04/24 22:08:20.685368 Starting part 3 ...
INFO: 2021/04/24 22:08:20.685529 Starting part 4 ...
INFO: 2021/04/24 22:08:20.685909 Starting part 5 ...
INFO: 2021/04/24 22:08:20.686069 Starting part 6 ...
INFO: 2021/04/24 22:08:20.686219 Starting part 7 ...
INFO: 2021/04/24 22:08:20.686363 Starting part 8 ...
INFO: 2021/04/24 22:08:20.686510 Starting part 9 ...
INFO: 2021/04/24 22:08:20.686677 Starting part 10 ...
INFO: 2021/04/24 22:08:20.686822 Starting part 11 ...
INFO: 2021/04/24 22:08:20.686961 Starting part 12 ...
INFO: 2021/04/24 22:08:24.276151 Finished writing part 4.
INFO: 2021/04/24 22:08:24.278151 Finished writing part 8.
INFO: 2021/04/24 22:08:25.227138 Finished writing part 10.
INFO: 2021/04/24 22:08:25.819769 Finished writing part 1.
INFO: 2021/04/24 22:08:26.491535 Finished writing part 9.
INFO: 2021/04/24 22:08:27.034937 Finished writing part 6.
INFO: 2021/04/24 22:08:27.775311 Finished writing part 11.
INFO: 2021/04/24 22:08:28.570201 Finished writing part 12.
INFO: 2021/04/24 22:08:29.499776 Finished writing part 5.
INFO: 2021/04/24 22:08:30.541476 Finished writing part 7.
INFO: 2021/04/24 22:08:32.224085 Finished writing part 3.
INFO: 2021/04/24 22:08:33.126335 Finished writing part 2.
INFO: 2021/04/24 22:08:36.345127 Starting part 14 ...
INFO: 2021/04/24 22:08:36.345300 /global/pg_control
INFO: 2021/04/24 22:08:36.346188 Finished writing part 14.
INFO: 2021/04/24 22:08:36.347239 Calling pg_stop_backup()
```
Strace messages:
```
strace: Process 16073 attached
futex(0x2c303c8, FUTEX_WAIT_PRIVATE, 0, NULL
```

**Comment by Samusername** [comment]
We got similar problem, with minio and wal-g v0.2.19.
It stops / hangs at: "Calling pg_stop_backup()"  

Many backup files end up to our S3 bucket, but e.g. wal-g backup-list is not able to list those basebackups.

**Comment by vy-nguyentan** [comment]
I'm going to close this issue. I was performed backup on the slave which currently has no database traffic and archive_command to empty.  I set `archive_command = /bin/true`on the slave server but backup-push still stuck. pg_stop_backup has to wait for new WAL segments to be archived. 
If I run `select pg_switch_wal();` on primary, the backup-push complete successfully.

@Samusername you can try `archive_command = /bin/true` or `archive_command = wal-g wal-push --config=/var/lib/pgsql/walg-common-config.json wal-push %p` and check again.

**Comment by v0112358** [comment]
I'm going to close this issue. I was performed backup on the slave which currently has no database traffic and archive_command to empty.  I set `archive_command = /bin/true`on the slave server but backup-push still stuck. pg_stop_backup has to wait for new WAL segments to be archived. 
If I run `select pg_switch_wal();` on primary, the backup-push complete successfully.

@Samusername you can try `archive_command = /bin/true` or `archive_command = wal-g wal-push --config=/var/lib/pgsql/walg-common-config.json wal-push %p` and check again.
