### ISSUE TITLE
wal-verify does not work from a standby

### ISSUE THREAD

**Issue by victor-sudakov** [wal-g/wal-g#946]
When trying to run wal-verify from a standby:

```
$ wal-g wal-verify
ERROR: 2021/04/28 03:53:51.713465 Failed to get current WAL segment number GetCurrentLsn: getting current LSN of the cluster failed: ERROR: recovery is in progress (SQLSTATE 55000)

```
There is truth in it:
```
postgres=# select pg_current_wal_lsn();
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
```

But maybe there is some other way to get the current LSN on a standby?

My wal-g version is v0.2.19

**Comment by x4m** [comment]
Seems like we should take  pg_last_wal_receive_lsn() if pg_is_in_recovery()

https://github.com/wal-g/wal-g/blob/0261341f03bafb48960dbb5835d2b921cbb92b14/internal/databases/postgres/queryRunner.go#L73

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1014
