### ISSUE TITLE
If Postgres is restarted during backup-push, it fails in the very end – but should fail earier

### ISSUE THREAD

**Issue by NikolayS** [wal-g/wal-g#969]
(Discussed with @x4m in Telegram)

The latest wal-g (from the master branch), large DB (13 TiB), GCS.

`backup-push` normally takes ~7 hours

~30 minutes after `backup-push` has started, we had a restart of Postgres. Of course, this means that the backup job should fail – because we don't have connection anymore, where we executed `pg_start_backup`.

The problem is WAL-G didn't stop performing `backup-push` and failed only after ~7 hours, in the very end:

```
Finished writing part 12940.
ERROR: 2021/05/08 18:16:21.132265 UploadLabelFiles: Failed to build query runner.: GetVersion: getting Postgres version failed: write tcp 127.0.0.1:56322->127.0.0.1:5432: write: broken pipe
```

-- consequences were that we didn't have a full backup for long (this was a manually invoked `backup-push` after a major PG upgrade –  so we did need a full backup ASAP). If it failed immediately, we could re-start it and lose only ~30 minutes

Proposal: implement some way of checking the state of the PG connection, if it's broken then stop `backup-push` immediately, reporting that it cannot proceed because the PG connection is broken and backup context is lost.

**Comment by x4m** [comment]
Thanks for the ping! @usernamedt, let's add this to the list of projects ideas for potential contributors?

**Comment by anikin-aa** [comment]
Folks, hi!

Can confirm that WALG_ALIVE_CHECK_INTERVAL is working as expected, tried to do the next scenario:

1. Init PG with some data (with pgbench)
2. Launch back-push via WAL-G:
```
wal-g backup-push 
```
3. Restart PG:
```
pg_ctl restart
```
4. WAL-G back-push procedure fails:
```
DEBUG: 2023/06/14 17:26:15.745941 Checking if Postgres is still alive...
ERROR: 2023/06/14 17:26:15.747753 Error: PG alive check failed: failed to check if the Postgres connection is alive: conn is dead, gracefully stopping the running backup...
INFO: 2023/06/14 17:26:15.747766 Calling pg_stop_backup()
WARNING: 2023/06/14 17:26:15.747948 Failed to stop backup: QueryRunner StopBackup: transaction begin failed: set tcp 127.0.0.1:60091: use of closed network connection
ERROR: 2023/06/14 17:26:15.747954 Finished backup termination, will now exit
```
