### ISSUE TITLE
Alternative to lz4 compression algorithms

### ISSUE THREAD

**Issue by x4m** [wal-g/wal-g#97]
Currently, WAL-G significantly outperforms WAL-E in CPU and disk-constrained environments (especially with delta backups, but that's another story). But when the network throughput is a bottleneck - WAL-E is faster. WAL-G backups are simply bigger since it uses lz4 - faster but less efficient compression algorithm (than lzo).
Meanwhile, In many cases, CPU usage of WAL-G is neglectable small. Many CPU cores are simply sleeping, and it worth utilizing them to reduce usage of network bandwidth and storage size.
Which compression formats could be a most viable alternative?
It is highly preferred to use Go implementation with broad usage.

**Comment by dev1ant** [comment]
Zstd?

**Comment by x4m** [comment]
At first glance, I do not see Go implementations, only C-Go bindings. But I think it worth trying.

**Comment by patsevanton** [comment]
wal-g support zstd?

**Comment by AlexGluck** [comment]
How to disable compression? Anyone knows?
