### ISSUE TITLE
New pre-release/incremental release?

### ISSUE THREAD

**Issue by rocket357** [wal-g/wal-g#970]
Would it be possible to get a new incremental/"pre-release" release for further testing of:

https://github.com/wal-g/storages/pull/45

The last pre-release (https://github.com/wal-g/wal-g/releases/tag/v0.2.21) was made the day before the above PR was merged, so I've been running on internal builds at $DAYJOB without issue.  That said, I'd rather point back to upstream if possible for long-term use.  =)

Also, there was mention of moving storages back under wal-g (https://github.com/wal-g/storages/pull/15#issuecomment-587300108), so I don't know if that is a current blocker or not.  Please advise if there's anything I can do to assist if that is still planned.

Thanks!

**Comment by agadelshin** [comment]
We would appreciate new release also

**Comment by x4m** [comment]
Ok, here's the pre-release if you wish to try out the current version.
https://github.com/wal-g/wal-g/releases/tag/v0.2.22
Meanwhile, I will appreciate help with composing a feature list for release notes. What are most prominent features we made so far? I remember remote backup. And many many fixes... And it would be great to merge #950 before release...

**Comment by agadelshin** [comment]
@x4m I'm going to build and test pre-release, thanks.

We're missing bug fix for #840 and we're currently trying to make it work together with https://github.com/sorintlab/stolon/blob/master/doc/pitr_wal-g.md.

Unfortunately restore to point-in-time doesn't work for me so I'm trying to dig and understand is it stolon or wal-g issue.

After I'll figure out this I can help you with release preparation if you need.

**Comment by agadelshin** [comment]
v0.2.22 looks good. Created separate issue (for PiTR), in the meantime I looked through the diff and found interesting features/fixes (at least from my perspective).

* #840 "Value out of range" in wal-show was fixed
* #824 New option was added to wal-verify, now it requires an argument timeline|integrity
* #780 PostgreSQL remote backups
* #905 Improve compatibility with PostgreSQL 13, introduced WALG_PREFETCH_DIR option 
* #903 It's now not allowed to create delta backups from permanent backups
* huge amount of bug fixes, tests and imporvements for Redis/Mongodb/SQLServer/etc

**Comment by agadelshin** [comment]
meanwhile I understood that problem wasn't in wal-g, but lack of knowledge about PostgreSQL! @x4m how can we proceed?:)

**Comment by Vampouille** [comment]
I'm happy to see that a new release is planned. With 0.2.19, restoration is not working from s3 like service because pagination on list object v2 is broken. The following merge request should fix the issue and is included since 0.2.20
https://github.com/wal-g/storages/pull/42
Thanks :-)

**Comment by x4m** [comment]
@agadelshin @Vampouille  this looks like decent release notes, many thanks!
The last thing we wait for before release is Redis ```backup-fetch```, and then we a ready to bless the new release.

**Comment by x4m** [comment]
Thanks, everyone! v1.0 released
