### ISSUE TITLE
Broken contributors link in docs

### ISSUE THREAD

**Issue by jlosito** [wal-g/wal-g#971]
# Issue description

The contributors link in the docs seems to be broken. In both cases, the link leads to a 404. Below are the links I'm referring to.

https://wal-g.readthedocs.io/CONTRIBUTORS

https://github.com/wal-g/wal-g/blob/master/docs/README.md#authors

I'm not entirely sure if this link is simply supposed to point to one of the following link instead.

https://github.com/wal-g/wal-g/graphs/contributors
https://github.com/wal-g/wal-g/blob/master/CONTRIBUTORS

**Comment by usernamedt** [comment]
@qkeypechenka can you have a look?
