### ISSUE TITLE
Versioning for readthedocs

### ISSUE THREAD

**Issue by jlosito** [wal-g/wal-g#972]
# Issue description

I believe the current documentation which is hosted in readthedocs only has a single version of wal-g. I'd like to look at historical versions, such as 0.2.13. This looks possible according to the link below.

https://docs.readthedocs.io/en/stable/versions.html

**Comment by usernamedt** [comment]
Since the readthedocs.io version of the WAL-G documentation was introduced not so long time ago, I guess that we can't use it for old versions because they are not compatible with readthedocs. But we certainly are able to do it for the new versions, after the future releases, thanks for this idea!
