### ISSUE TITLE
Unconventional LSN format in wal-g output

### ISSUE THREAD

**Issue by victor-sudakov** [wal-g/wal-g#987]
"wal-g backup-push" (version v0.2.19, Debian10) generates a message looking like this:

Delta backup from base_0000000200001D4B00000017_D_0000000200001D2400000013 with LSN 1d4b17068128.
 
It would be nice if the reference to the LSN should be in the standard PostgreSQL format: XXXX/YYYY (string consisting of two strings of hexadecimal characters, each with a length of between 1 and 8, separated by a slash).

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1259

**Comment by victor-sudakov** [comment]
It now looks great in v2.0.1, thank you!
