### ISSUE TITLE
wal-g backup-push -> error trouble shooting

### ISSUE THREAD

**Issue by ibayer** [wal-g/wal-g#988]
Thanks for this nice tool, I was running wal-e for a long time and am now trying to switch to wal-g.

```
wal-g version v0.2.19	8dba4f4	2020.11.30_09:18:01	PostgreSQL
postgres:10.3
```

# Issue description

### Describe your problem

From the docs it's unclear to me which path `backup-push` expects or what's expected
in term of a `pg_control` file.

```
wal-g backup-push /var/lib/postgresql/
ERROR: 2021/05/21 16:02:28.112989 It looks like you are trying to backup not pg_data. PgControl file not found: open /var/lib/postgresql/global/pg_control: no such file or directory
```

I use the official postgres docker file with the following mount points:

```
  63           "/srv/postgres/data:/var/lib/postgresql/data",$                      
  64           "/srv/postgres/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf",$
  65           "/srv/postgres/conf/pg_hba.conf:/etc/pg_hba.conf",$                  
  66         ]$                                                    
```

I read the docs but somehow can't make sense of this error message. Any hints are very much appreciated.

**Comment by ibayer** [comment]
I can see that wal files are sucessfully uploaded to the s3 bucket

<span><span>
00000002000001EA000000C7.lz4 | lz4 | May 21, 2021, 09:37:36 (UTC+02:00) | 388.5 KB | Standard
-- | -- | -- | -- | --
&nbsp;

</span></span>
&nbsp; | &nbsp;
-- | --


</span></span>
00000002000001EA000000C8.lz4 | lz4 | May 21, 2021, 09:47:37 (UTC+02:00) | 185.1 KB | Standard
-- | -- | -- | -- | --
&nbsp;

</span></span>
&nbsp; | &nbsp;
-- | --


</span></span><span><span>
00000002000001EA000000C9.lz4 | lz4 | May 21, 2021, 09:57:37 (UTC+02:00) | 128.4 KB | Standard
-- | -- | -- | -- | --

**Comment by gsmol** [comment]
Hello!
You must provide the path to PGDATA via `--pgdata` option

**Comment by ibayer** [comment]
@gsmol thanks for the suggestions.
```
psql -U postgres -c "show data_directory;"
      data_directory      
--------------------------
 /var/lib/postgresql/data
```
I tried the following:
`wal-g backup-push --pgdata /var/lib/postgresql/data/` -> `Error: accepts 1 arg(s), received 0`

and then
```
wal-g backup-push --pgdata /var/lib/postgresql/data/ /var/lib/postgresql
ERROR: 2021/05/21 16:41:56.032733 It looks like you are trying to backup not pg_data. PgControl file not found: open /var/lib/postgresql/global/pg_control: no such file or directory
```

but I get the same error. :-(

**Comment by gsmol** [comment]
Sorry for misleading comment, path to pgdata is an argument to `backup-push`
```
wal-g backup-push /var/lib/postgresql/data/
```

**Comment by ibayer** [comment]
@gsmol 

this gives me indeed a different result but it's still an error

```
wal-g backup-push /var/lib/postgresql/data/
INFO: 2021/05/21 17:17:59.983298 Doing full backup.
ERROR: 2021/05/21 17:17:59.987643 FATAL: database "root" does not exist (SQLSTATE 3D000)
ERROR: 2021/05/21 17:17:59.987663 Failed to connect using provided PGHOST and PGPORT, trying localhost:5432
ERROR: 2021/05/21 17:17:59.992229 Connect: postgres connection failed: FATAL: database "root" does not exist (SQLSTATE 3D000)
```

**Comment by ibayer** [comment]
one step further, `docker exec -it -u postgres postgres-50ad9a8f-78d0-2703-61b9-1bb594f74103 bash` use
docker with user `postgres` and then run the backup command

```bash
 wal-g backup-push /var/lib/postgresql/data/
INFO: 2021/05/21 18:22:17.933865 Doing full backup.
INFO: 2021/05/21 18:22:17.988114 Calling pg_start_backup()
INFO: 2021/05/21 18:22:18.127391 Walking ...
INFO: 2021/05/21 18:22:18.127672 Starting part 1 ...
Killed
```

I found the following in the postgres logs

```bash
2021-05-21 18:25:10.977 UTC [1752] WARNING:  aborting backup due to backend exiting before pg_stop_backup was called
```

**Comment by ibayer** [comment]
# fixed

I run into 3 different errors:

- ` wal-g backup-push /var/lib/postgresql/data/` -> `/data` was missing
- command needs to be run as `postgres` user
- backup has high memory requirements and gets killed (docker memory limit) if they are not satisfied

**Comment by ibayer** [comment]
@gsmol Thanks for you comment, I got pointed me in the right direction!
